### ISSUE TITLE
Randomized referencing

### ISSUE THREAD

**Issue by umpirsky** [nelmio/alice#1]
There is a reference example in readme:

``` yaml
Nelmio\Entity\Group:
    group1:
        name: Admins
        owner: @user1
```

It would be nice to be able to reference random useer with something like:

``` yaml
Nelmio\Entity\Group:
    group1:
        name: Admins
        owner: @user*
```

Is this possible?
