### ISSUE TITLE
[Help] Control when fixtures are persisted

### ISSUE THREAD

**Issue by michaelgracious** [nelmio/alice#1002]
I'm having the following issue, for certain fixtures i need to have an entity that has an ID. So that `getId()` doesn't return NULL.

```
App\Entity\Category:
  category_root_a:
    title: 'a'

  category_root_b:
    title: 'b'

  category_root_c:
    title: 'c'
```
This all works fine, but then we get to the tricky part

```
  category_sub{1..10}:
    products: '[@product_1, @product_random*,@product_random*,@product_random*]'
    __calls:
      - setChildNodeOf:
          1: '@category_root_a'
```

Using KnpLabs "tree" we make a tree of the categories. To fill the materialized_path in the entities we need to either call `$child->setChildNodeOf($root)` or `$root->addChildNode($child)`. Both of which do not work because at the moment of calling, the entities aren't flushed yet, so have no ID. And i will get an error telling me i can't add nodes to the tree without an ID present in them.

How do i make sure the root categories are saved before i try to add a (sub)category to them?

This is on Symfony 4.3 with the `hautelook/AliceBundle`
