### ISSUE TITLE
Fixture YML using several time the same {@ref}

### ISSUE THREAD

**Issue by Ashk2a** [nelmio/alice#1004]
Hi, in this example we have : 
```
event_1:
  id: 1
  name: "event 1"
event_2:
  id: 2
  name: "event_2"
```

When I try this, only one record is register inside the database (I use SQLite)
```
something_{@event_1}:
  id: 1
  event: <current()>
something_{@event_1}_test:
  id: 2
  event: <current()>
```
But it's working when this : 
```
something_{@event_1}:
  id: 1
  event: <current()>
something_event_1_test:
  id: 2
  event: '@event_1'
```

Something is wrong with my usage ?

**Comment by theofidry** [comment]
I'm not quite sure `<current>` refers to `@event_1` or the string `'@event_1'` in this case... I think it should refer to the fixture instance though. So your usage should work just fine, meaning this is a bug.

**Comment by Ashk2a** [comment]
When we have **something_{@event_1}**  _<current()>_ is the same thing than _'@event_1'_ 
Like if we have **something_event_{1}** with _'@event_$current'_ (or _'@event_<current()>_, both work i guess) it's again the same thing. BUT i can't use several time {@event_1} in the same call

**Comment by mac503** [comment]
I'm experiencing something similar.

Given that these fixtures exist:

```
fixture_1:
    id: 1
fixture_2:
    id: 2
...etc
```

Then when those fixtures are used in two sets of later fixtures, like this, only the second set is created:

```
group_{@fixture*}:
    fixture: <current()>
    property: <getValue()>
group_{@fixture*}_alternative:
    fixture: <current()>
    property: <getAlternativeValue()>
```

In fact, the custom provider function getValue(), used in the first set, is never called.

However, just by changing the beginning of the name for the second set of fixtures, instead of the end of the name, this works:

```
group_{@fixture*}:
    fixture: <current()>
    property: <getValue()>
alternate_group_{@fixture*}:
    fixture: <current()>
    property: <getAlternativeValue()>
```

Both sets are created correctly.
