### ISSUE TITLE
Can not use references (@) in PHP expressions

### ISSUE THREAD

**Issue by arnaud-lb** [nelmio/alice#1006]
Using a reference (`@...`) in a PHP expression (`<(...)>`) results in the following error:

```
In EvaluatedValueResolver.php(74) : eval()'d code line 1:

  [Symfony\Component\Debug\Exception\ContextErrorException]
  Notice: Undefined variable: _instances
```

**Comment by theofidry** [comment]
Hm I think it needs to be escaped with `\`

**Comment by Kocal** [comment]
Hi :wave: 

I've got the same issue when using this `__construct` like this:
```yaml
App\Entity\UserEstablishment:
    user_establishement_foo_1:
        __construct: [<(@franchiseur_foo)>, <(@etablissement_foo)>]
    user_establishement_foo_2:
        __construct: [<(@franchisé_foo_lyon)>, <(@etablissement_foo)>]
    user_establishement_foo_3:
        __construct: [<(@franchisé_foo_paris)>, <(@etablissement_foo)>]
```

Since `<(@fixture)>` is working with `__calls()`, I thought it would work with `__construct()` but it does not.

After changing to `'@fixture'` syntax, it's now working properly:
```yaml
App\Entity\UserEstablishment:
    user_establishement_foo_1:
        __construct: ['@franchiseur_foo', '@etablissement_foo']
    user_establishement_foo_2:
        __construct: ['@franchisé_foo_lyon', '@etablissement_foo']
    user_establishement_foo_3:
        __construct: ['@franchisé_foo_paris', '@etablissement_foo']
```
