### ISSUE TITLE
Got array instead of reference

### ISSUE THREAD

**Issue by alegout** [nelmio/alice#1018]
Hello,

https://github.com/nelmio/alice/blob/v3.5.8/doc/advanced-guide.md#references

`@user_{alice, bob} => @user_alice or @user_bob`

If i:

client_type:

```
AppBundle\Entity\ClientType:
    client_type_{1..10}:
        name: '<name()>'
```

```
include:
    - client_type.yaml

AppBundle\Entity\Client:
    client_{1..20}:
        name: '<name()>'
        client_type: '@client_type_{1..10}'
```

I got:

`Expected argument of type "AppBundle\Entity\ClientType or null", "array" given`

It gives me an array with the 10 ClientType for the client_type field.

Is it normal?

Thank you

**Comment by AyrtonRicardo** [comment]
Which version are you using?
I think you are receiving a list of `AppBundle\Entity\ClientType` when you request using `{1..10}` operator.

In any case you can try out like this:
```yaml
include:
    - client_type.yaml

AppBundle\Entity\Client:
    client_{1..20}:
        name: '<name()>'
        client_type:"<randomElement([@client_type_*])>"
```

**Comment by AyrtonRicardo** [comment]
Which version are you using?
I think you are receiving a list of AppBundle\Entity\ClientType when you request using {1..10} operator.

You have option to do like this:
```yaml
include:
    - client_type.yaml

AppBundle\Entity\Client:
    client_{1..20}:
        name: '<name()>'
        client_type: '<randomElement(@client_type_{1..10})>'
```

or simply like this:
```yaml
include:
    - client_type.yaml

AppBundle\Entity\Client:
    client_{1..20}:
        name: '<name()>'
        client_type: '@client_type_*'
```

**Comment by alegout** [comment]
Thank you for your help. I am using the version 3.5.8.

With `@client_type_{1, 2, 3}` i should have @client_type_1 or @client_type_2 or @client_type_3 but it gives me an array with the three, sounds like a bug to me.

**Comment by AyrtonRicardo** [comment]
Actually whenever you use the operator `{}` you automatically is creating a collection.
In you creation you define `@client_type_{1, 2, 3}` => then it's available to use `@client_type_1` or `@client_type_2` or `@client_type_3`.
The operator to get a random one is `@client_type_*`

To solve your problem you can follow the comment above it will be fine for you.
```yaml
include:
    - client_type.yaml

AppBundle\Entity\Client:
    client_{1..20}:
        name: '<name()>'
        client_type: '<randomElement(@client_type_{1..10})>'
```
