### ISSUE TITLE
Declaration of ManyToMany relationship throwing Nelmio\Alice\Throwable\Exception\Generator\DebugUnexpectedValueException

### ISSUE THREAD

**Issue by Saeven** [nelmio/alice#1020]
Hi everyone.

First, thank you for this project.  It looks like precisely what I've been longing for.  This is a usage question, I appreciate your insight.

I am trying to fake a user, with a role relationship.  Nelmio YAML looks like so:

```
CirclicalUser\Entity\Role:
  user:
    id: 1
    name: 'user'
  admin:
    id: 2
    parent: '@user'
    name: 'admin'

Application\Entity\User:
  user1:
    id: 1
    email: 'user@email.com'
    roles: ['@admin']
```

If I remove the User::roles member, it works -- but adding it causes that exception.  That member is declared like so:

```
    /**
     * @ORM\ManyToMany(targetEntity="CirclicalUser\Entity\Role")
     * @ORM\JoinTable(
     *     name="users_roles",
     *     joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id", onDelete="CASCADE")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="role_id", referencedColumnName="id")}
     * )
     */
    private $roles;
```

Interestingly, if I change the private to public, it works -- but being public is not an option.  How do I properly do this?

Thank you for your help!
