### ISSUE TITLE
Email fixtures fail

### ISSUE THREAD

**Issue by tacman** [nelmio/alice#1031]
The @ is being interpreted as a related fixture.  This comes directly from the documentation.

```yaml
  user_{alice, beth, carol, dawn, ed, fiona, george, kath, mike, robb} (extends user_template):
    email: '<current()>@example.org'
    fullname: <current()> <lastname()>
```

```                                                                                                                                         
  An error occurred while generating the fixture "user_alice" (App\Entity\User): Could not resolve value during the generation process.  
                                                                                                                                         

In UnresolvableValueDuringGenerationExceptionFactory.php line 25:
                                                          
  Could not resolve value during the generation process.  
                                                          

In FixtureNotFoundExceptionFactory.php line 23:
                                             
  Could not find the fixture "example.org".  
                                             
```

**Comment by alcalyn** [comment]
Had the same issue, fixed it by using `$current` instead of `<current()>`:

``` yml
user_{alice, beth, carol, dawn, ed, fiona, george, kath, mike, robb} (extends user_template):
    email: '$current@example.org'
    fullname: <current()> <lastname()>
```
