### ISSUE TITLE
Assign by reference

### ISSUE THREAD

**Issue by ScreamingDev** [nelmio/alice#1037]
```yaml
Foo:
  someFoo:
    abc: "source and solution to all our problems"
Bar:
  someBar:
    beer: "@someFoo->abc"
```

The value resolver usually copy a value from one item to another when using  `@someFoo->abc` here. But instead of a copy I may want to have a [reference](https://www.php.net/manual/en/language.references.php) to the other field.

So what Alice does is:

```
$someBar->beer = $someFoo->abc
```

But how to achieve this?

```
$someBar->beer =& $someFoo->abc
```

This feels missing when generating objects.

**Please note**: This is not a discussion about references, how valuable they are and when to do them. I do not want to chat about the pro and cons of references neither about specific use-cases. This is a plain simple note that Alice does not seem to be able to [assign by reference](https://www.php.net/manual/en/language.references.whatdo.php#language.references.whatdo.assign) and I hope for some solution to that.

**Comment by ScreamingDev** [comment]
So in the end there may be

1. an adapter from YAML to the new Alice API structure as described in #998 
2. An additional syntax for creating references like

```yaml
Foo:
  someFoo:
    abc: "source and solution to all our problems"
Bar:
  someBar:
    beer: "@&someFoo->abc"
    # note the ampersand above
```

or something else.

So I like to change this issue to:

> Please allow references in the new Alice API
