### ISSUE TITLE
Empty when 

### ISSUE THREAD

**Issue by videni** [nelmio/alice#1042]
```
 <entity name="Acme\Component\Tag\Model\Tagging" table="Acme_tagging">
        <id name="id" column="id" type="integer">
            <generator strategy="AUTO" />
        </id>

        <field name="resourceType"  column="resource_type"  type="string" length="50" />
        <field name="resourceId"    column="resource_id"    type="string" length="50" />

        <field name="createdAt"     column="created_at"     type="datetime" />
        <field name="updatedAt"     column="updated_at"     type="datetime" />

        <many-to-one field="tag" target-entity="Acme\Component\Tag\Model\TagInterface">
            <join-columns>
                <join-column name="tag_id" referenced-column-name="id" />
            </join-columns>
        </many-to-one>

        <unique-constraints>
            <unique-constraint columns="tag_id,resource_type,resource_id" name="tagging_idx" />
        </unique-constraints>
    </entity>
```

```
Acme\Component\Project\Model\Project:
project1:
    title: project1
    description: project1

Acme\Component\Tag\Model\Tag:
    project_tag1:
        name: 'test'
        slug: 'test'

Acme\Component\Tag\Model\Tagging:
    project_tagging1:
        __construct:
            - '@project_tag1'
            - '@project1'
       
```
```
class Tagging 
{

    /**
     * Constructor
     */
    public function __construct(Tag $tag = null, Taggable $resource = null)
    {
        if ($tag != null) {
            $this->setTag($tag);
        }

        if ($resource != null) {
            $this->setResource($resource);
        }

        $this->setCreatedAt(new \DateTime('now'));
        $this->setUpdatedAt(new \DateTime('now'));
    }
}
```

the tag property of Tagging is  a relation, but the `resource` property is not. anyway to resolve this issue？ currently I create the tagging object manually.
