### ISSUE TITLE
Inability to use faker function in construct for YAML fixtures

### ISSUE THREAD

**Issue by Mx-Glitter** [nelmio/alice#105]
As an example, trying to load a YAML file with this fixture will fail:

```
Example:
  __construct: [<fun_with_args(1, 2)>]
  foo: 1
  bar: 'oof'
```

I've tried to dig a bit where the problem was, and in YAML component of Symfony in Inline.php file, the comma is interpreted as a separator for the elements of the array.

I'm a little bit clueless on how to fix this though, as I cannot propose huge changes to the YAML parser of Symfony, so if you have any idea, I'd be very happy to help implement something.
