### ISSUE TITLE
Could not instantiate "authUser1", the constructor has mandatory parameters but no parameters have been given.

### ISSUE THREAD

**Issue by Mariyo** [nelmio/alice#1073]
Hello,

could you please help me with this exception?

```
Could not instantiate "authUser1", the constructor has mandatory parameters but no parameters have been given.
```

Fixtures are defined like this:

```yaml
B2C\Authentication\Infrastructure\Doctrine\Entity\UserEntity:
  authUser1:
    userId: <uuid()>
    profesiaId: <randomDigitNotNull()>

  authUser2:
    userId: <uuid()>
    profesiaId: <randomDigitNotNull()>
```

however using factory it works:

```yaml
B2C\Authentication\Infrastructure\Doctrine\Entity\UserEntity:
  authUser1:
    __factory: {
      'createFromPrimitives': [
          <uuid()>,
          <randomDigitNotNull()>
      ]
    }
  authUser2:
    __factory: {
      'createFromPrimitives': [
          <uuid()>,
          <randomDigitNotNull()>
      ]
    }
```

I tried to debug the code and stucked on this, I can see fixtures with data:

![image](https://user-images.githubusercontent.com/1678254/104348605-34db1280-5502-11eb-8e56-379aa94281a6.png)

Thx for any help

**Comment by Mariyo** [comment]
Closing, constructor required arguments must be provided in this way:

```yaml
B2C\Authentication\Infrastructure\Doctrine\Entity\UserEntity:
  authUser1:
    __construct: [
        <uuid()>,
        <randomDigitNotNull()>
    ]

  authUser2:
    __construct:
      - <uuid()>
      - <randomDigitNotNull()>
```
