### ISSUE TITLE
An error occurred while generating the fixture

### ISSUE THREAD

**Issue by holhp** [nelmio/alice#1086]
Hi, i just updated my php from 7.2 to 7.4 and i had this issue:

```
[Nelmio\Alice\Throwable\Exception\Generator\DebugUnexpectedValueException] An error occurred while generating the fixture "document1" (\App\Entity\Document\SupplierEducationDocu
ment): Could not instantiate fixture "document1".
```

```
\App\Entity\Supplier:
  supplier_with_education (extends supplier):
    userId: 901
  supplier_without_education (extends supplier):
    userId: 902

\App\Entity\SupplierEducation:
  education_with_no_documents (extends education):
    __construct:
      supplier: '@supplier_with_education'
      countryId: '<numberBetween(1, 100)>'
      name: '<company()>'
      degree: '<jobTitle()>'
      yearOfGraduation: '<numberBetween(1980, 2020)>'
    institution: '<realText(20)>'

  education_with_documents (extends education):
    __construct:
      supplier: '@supplier_with_education'
      countryId: '<numberBetween(1, 100)>'
      name: '<company()>'
      degree: '<jobTitle()>'
      yearOfGraduation: '<numberBetween(1980, 2020)>'
    institution: '<realText(20)>'

  education{1..101} (extends education):
    __construct:
      supplier: '@supplier_with_education'
      countryId: '<numberBetween(1, 100)>'
      name: '<company()>'
      degree: '<jobTitle()>'
      yearOfGraduation: '<numberBetween(1980, 2020)>'
    institution: '<realText(20)>'

\App\Entity\Document\SupplierEducationDocument:
  document{1..2} (extends education_document):
    __construct:
      education: '@education_with_documents'
      filename: '<realText(20)>'

```

This test worked fine before upgrading. Do you have how to fix it?
Many thanks.
