### ISSUE TITLE
Referencing from fixture file 2 to fixture file 1

### ISSUE THREAD

**Issue by luebbert42** [nelmio/alice#110]
I am referencing to this part of the documentation: "Let's get back to the Group. Ideally a group should have members, and Alice allows you to reference one object from another one. You can do that with the @name notation, where name is a fixture name from any class."

I am using "1.7.*@dev" and load two fixtures:

```
#father.yml
MyApp\AppBundle\Entity\Father:
    father1:
        name: "Dad"
        someProperty: true

```

```
#children.yml
MyApp\AppBundle\Entity\Child:
    child1:
        name: "Loveley child"
        father: @father1
```

This works only if I load the fixtures from one class extending AbstractFixture or if the definitions are in one file. It took me a moment to understand that as I got confused by the "from any class" statement. Eventually you want to clarify this in the documentation?
