### ISSUE TITLE
Get the Id of an entity in another entity

### ISSUE THREAD

**Issue by jmbianca** [nelmio/alice#1125]
Hi,

I'm trying to get the id of an entity in another one, without success. Let say, my entities are:
```
user:
  - with an id (autogenerated by the database)
  - a username

document:
  - with an id (autogenerated by the database)
  - some label
  - a json field, where I want to list the id of a user
```
  
What I have already tried:

```
App\Entity\User:
  user_1:
    username: 'johndoe'

App\Entity\Document:
  doc_1:
    docname: 'mydoc'
    json_field: [ { 'test': '@user_1->id' } ]
```
  
But it return null. I also tried to create a new Provider, like that:
```
class IdProvider
{
    public function getId(AbstractEntity $entity): int
    {
        return $entity->getId();
    }
}
```

with: 
```
App\Entity\Document:
  doc_1:
    docname: 'mydoc'
    json_field: [ { 'test': <getId(@user_1)> } ]
```

But it return null too. Because the entity it not saved yet, so it do not have an id.

How can I proceed to get this Id in this Json field?

Thank you!
