### ISSUE TITLE
bring back the named constructor

### ISSUE THREAD

**Issue by c33s** [nelmio/alice#1162]
i am migrating an older symfony project to 7.0 where i also updated alice.

sadly alice made a big step back, according the readme the constructor now has to be an array
```
    service_text:
        __construct:
            name: Name
            short_name: editorial
            percent: 93
            icon: basic-book-pen
            description: Description
            visible: true
            rank: 60
vvv
    service_text:
        __construct:
            - Name
            - editorial
            - 93
            - basic-book-pen
            - Description
            - true
            - 60
```
rewriting all the fixtures and removing valuable information to have a result which is much less readable feels more than wrong. having php supporting named arguments while removing names from alice feels wrong for me.

any chance to get back name constructor?
