### ISSUE TITLE
Force __construct even without parameters

### ISSUE THREAD

**Issue by jverdeyen** [nelmio/alice#123]
I'm using an extended User class from the FOSUserBundle.
In the __construct of this class multiple data members are initiated.

This __construct function has no arguments.

The following fixture doesn't call the constructor, although it should call it.

```
ProjectBundle\AppBundle\Entity\User:
    admin_user:
        username: admin
        email: admin@project.com
        plainPassword: admin
        roles: ['ROLE_SUPER_ADMIN']
        enabled: true
        expiresAt: <dateTimeBetween('+100days', '+200 days')>
        registrationDate: <dateTimeBetween('-100days', '-1 days')>
        step: null
```

When looping through the initiators, the `ReflectionWithoutConstructor` is first in row.
And this function will return true. So initiation is made, without constructor.

```
    /**
     * {@inheritDoc}
     */
    public function canInstantiate(Fixture $fixture)
    {
        return !$fixture->shouldUseConstructor() && !version_compare(PHP_VERSION, '5.4', '<');
    }

```

I'm now forcing this by passing a dummy parameter in the constructor. But that's really ugly :)
Any idea how I can fix this?

Thanks!
