### ISSUE TITLE
Working with array elements

### ISSUE THREAD

**Issue by reypm** [nelmio/alice#139]
It's possible to pass an array as value for some elements? For example in my case I'm trying to set roles for a FOSUserBundle `User` entity that takes `roles` as an array of values and not plain values. I have this in my fixture:

```
UserBundle\Entity\User:
    User0:
        username: admin
        email: admin@local.com
        enabled: 1
        plainPassword: admin
        roles: [ROLE_ADMIN]
        groups: @Group0

    User{1..10}:
        username: <firstNameMale>
        email: <companyEmail>
        enabled: <boolean(35)>
        plainPassword: <lexify>
        roles: 35%? [ROLE_ADMIN, ROLE_USER, ROLE_PROFILE_ONE, ROLE_PROFILE_TWO]
        groups: @Group*
```

But it's not working and I'm getting this error:

> [Symfony\Component\Debug\Exception\ContextErrorException]
> Catchable Fatal Error: Argument 1 passed to FOS\UserBundle\Model\User::setRoles() must be of 
> the type array, string given, called in 
> /var/www/html/vendor/nelmio/alice/src/Nelmio/Alice/Loader/Base.php on line 483 and defined in 
> /var/www/html/vendor/friendsofsymfony/user-bundle/FOS/UserBundle/Model/User.php line 530

Any advice around this?
