### ISSUE TITLE
Setting up parameter as array in fixture generator

### ISSUE THREAD

**Issue by reypm** [nelmio/alice#140]
I'll open this issue since I've tried a lot of things and without success. Coming from [this](http://stackoverflow.com/questions/26050825/setting-up-parameter-as-array-in-nelmio-alice-fixture-generator) well discussed  topic I come here to ask for help. I'll try to describe as best as I can what is already explained in the topic in Stackoverflow.

**The beginning (first test whithout ask for help yet)**
I try to set `roles` for a FOSUserBundle `User` entity that takes this var as an array of values and not plain values so I did this in my fixture:

```
UserBundle\Entity\User:
    User0:
        username: admin
        email: admin@local.com
        enabled: 1
        plainPassword: admin
        roles: [ROLE_ADMIN]
        groups: @Group0

    User{1..10}:
        username: <firstNameMale>
        email: <companyEmail>
        enabled: <boolean(35)>
        plainPassword: <lexify>
        roles: 35%? [ROLE_ADMIN, ROLE_USER, ROLE_PROFILE_ONE, ROLE_PROFILE_TWO]
        groups: @Group*
```

But that did not work because I got this error:

> [Symfony\Component\Debug\Exception\ContextErrorException]
> Catchable Fatal Error: Argument 1 passed to FOS\UserBundle\Model\User::setRoles() must be of 
> the type array, string given, called in 
> /var/www/html/vendor/nelmio/alice/src/Nelmio/Alice/Loader/Base.php on line 483 and defined in 
> /var/www/html/vendor/friendsofsymfony/user-bundle/FOS/UserBundle/Model/User.php line 530

Then from there I ask for help and thanks to Stackoverflow users I got some ideas/suggestions and I started to try them, below the details:

**Using first approach with plain array in YAML file:**

After made some changes as user suggested the fixture now has this content:

```
UserBundle\Entity\User:
    User0:
        username: admin
        email: admin@local.com
        enabled: 1
        plainPassword: admin
        roles: [ROLE_ADMIN]
        groups: @Group0

    User{1..10}:
        username: <firstNameMale>
        email: <companyEmail>
        enabled: <boolean(35)>
        plainPassword: <lexify>
        roles: [ROLE_PROFILE_ONE, ROLE_PROFILE_TWO]
        groups: @Group*
```

But any time I try to execute the set by calling:

```
h4cc_alice_fixtures:load:sets ./src/CommonBundle/DataFixtures/TananeSet.php
```

I got this error:

> [ErrorException]   Catchable Fatal Error: Argument 1 passed to
> Doctrine\Common\Collections\ArrayCollection::__construct() must be of
> the type array, object given, called in
> /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php o  
> n line 555 and defined in
> /var/www/html/vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php
> line 47

Which makes me think the problem here is related to `$groups` variable in `User` entity. This is a piece of code on that entity:

```
/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 * @ORM\Entity(repositoryClass="UserBundle\Entity\Repository\UserRepository")
 */
class User extends BaseUser {
    /**
     * Hook timestampable behavior
     * updates createdAt, updatedAt fields
     */
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToMany(targetEntity="Group")
     * @ORM\JoinTable(name="fos_user_user_group",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="group_id", referencedColumnName="id")}
     * )
     */
    protected $groups;

    /**
     * @ORM\Column(name="deletedAt", type="datetime", nullable=true)
     */
    protected $deletedAt;

}
```

I'm already fixed that one or maybe not, but now I've changed my fixture to this one instead:

```
UserBundle\Entity\User:
    User0:
        username: admin
        email: admin@local.com
        enabled: 1
        plainPassword: admin
        roles: [ROLE_ADMIN]
        groups: [@Group0]

    User{1..10}:
        username (unique): <text(15)>
        email: <companyEmail>
        enabled: <boolean(35)>
        plainPassword: <lexify>
        roles: [ROLE_PROFILE_ONE, ROLE_PROFILE_TWO]
        groups: [@Group*]
```

But again when I ran the command other error appeared, now is this one:

```
[RuntimeException]
  Couldn't generate random unique value for Tanane\UserBundle\Entity\User: email in 128 tries.
```

I tried also this way:

**Using second approach: defining a service**

I've tried to define my own Faker (I should mention that I got no clear example of code or in the README of this Bundle, much less in the documentation of the Faker bundle around this) and I did this:

```
services:
    roles.faker.provider:
        class: CommonBundle\Tools\RolesFakerProvider
        tags:
            -  { name: h4cc_alice_fixtures.provider }
```

**RolesFakerProvider.php**

```
namespace CommonBundle\Tools;

class RolesFakerProvider {

    public function randomRoles()
    {
        $names = ['ROLE_USER', 'ROLE_PROFILE_ONE', 'ROLE_PROFILE_TWO'];

        return [$names[array_rand($names)]];
    }

}
```

**User.yml**

```
UserBundle\Entity\User:
    User0:
        username: admin
        email: admin@local.com
        enabled: 1
        plainPassword: admin
        roles: [ROLE_ADMIN]
        groups: [@Group0]

    User{1..10}:
        username (unique): <text(15)>
        email: <companyEmail>
        enabled: <boolean(35)>
        plainPassword: <lexify>
        # BEFORE
        #roles: [ROLE_PROFILE_ONE, ROLE_PROFILE_TWO]
        # AFTER
        roles: <randomRoles>
        groups: [@Group*]
```

And this one is returning this error instead:

> [Symfony\Component\Debug\Exception\ContextErrorException]   Catchable
> Fatal Error: Argument 1 passed to
> FOS\UserBundle\Model\User::setRoles() must be of the type array,
> string given, called in
> /var/www/html/vendor/nelmio/alice/src/Nelmio/Alice/Loader/Base.php
> on line 483 and defin   ed in
> /var/www/html/vendor/friendsofsymfony/user-bundle/FOS/UserBundle/Model/User.php
> line 530

Which makes me think the function isn't returning an `array` so I go back and change this on the function:

```
class RolesFakerProvider {

    public function randomRoles()
    {
        $names = ['ROLE_USER', 'ROLE_PROFILE_ONE', 'ROLE_PROFILE_TWO'];
        return [$names[array_rand($names)]];
    }

}
```

But once again another error:

> [Symfony\Component\Debug\Exception\ContextErrorException]
>  Catchable Fatal Error: Argument 1 passed to FOS\UserBundle\Model\User::setRoles() must be of the type array, string given, called in /var/www/html/tanane/vendor/nelmio/alice/src/Nelmio/Alice/Loader/Base.php 
> on line 483 and defined in /var/www/html/tanane/vendor/friendsofsymfony/user-bundle/Model/User.php line 525

I don't know what else to do or where is the error in all that I have and the tests I've done? Any clue? Help? Advice?
