### ISSUE TITLE
NelmioAlice is confusing references

### ISSUE THREAD

**Issue by reypm** [nelmio/alice#146]
I have this set:

```
$set = new h4cc\AliceFixturesBundle\Fixtures\FixtureSet(array(
    'locale' => 'es_ES',
    'seed' => 42,
    'do_drop' => true,
    'do_persist' => true
        ));

#ComunBundle
... some fixtures
$set->addFile(__DIR__ . '/Estado.yml', 'yaml');
... some fixtures
$set->addFile(__DIR__ . '/EstadoSolicitud.yml', 'yaml');
... some fixtures

#UsuarioBundle
... some fixtures
$set->addFile(__DIR__ . '/Usuario.yml', 'yaml');

return $set;
```

That's fine and I execute trough the command:

```
h4cc_alice_fixtures:load:sets ./src/ComunBundle/DataFixtures/SencamerSet.php
```

But I'm getting this error:

> [Symfony\Component\Debug\Exception\ContextErrorException]
>  Catchable Fatal Error: Argument 1 passed to UsuarioBundle\Entity\Usuario::setEstado() must be an instance of ComunBundle\Entity\Estado, instance of ComunBundle\Entity\EstadoSolicitud given, called in /
>  var/www/html/vendor/nelmio/alice/src/Nelmio/Alice/Loader/Base.php on line 498 and defined in /var/www/html/src/UsuarioBundle/Entity/Usuario.php line 188

And I can't find where this is failing. I check all the fixtures and apparently are fine, anyway here are the three involve files:

**Estado.yml**

```
ComunBundle\Entity\Estado:
    Estado{1..50}:
        nombre (unique): <text(15)>
        pais: @Pais*
        activo: <boolean(35)>
```

**EstadoSolicitud.yml**

```
ComunBundle\Entity\EstadoSolicitud:
    EstadoSolicitud{1..5}:
        nombre (unique): <text(15)>
```

**Usuario.yml**

```
UsuarioBundle\Entity\Usuario:
    Usuario0:
        pais: @Pais*
        estado: @Estado*
        municipio: @Municipio*
        ciudad: @Ciudad*
        parroquia: @Parroquia*
        persona: f
        correo_alternativo: admin_alternative@admin.com
        telefono: <formatPhoneNumber($this->fake('phoneNumber'))>
        telefono_movil: <formatPhoneNumber($this->fake('phoneNumber'))>
        direccion: <address()>
        representativeName: <firstNameMale()> <lastName()>
        username: admin
        email: admin@admin.com
        enabled: 1
        plainPassword: 1qazxsw2
        roles: [ROLE_ADMIN]
        grupos: [@Grupos0]

    Usuario{1..10}:
        pais: @Pais*
        estado: @Estado*
        municipio: @Municipio*
        ciudad: @Ciudad*
        parroquia: @Parroquia*
        persona: <boolean(35)>
        correo_alternativo: <safeEmail()>
        telefono: <phoneNumber()>
        telefono_movil: <phoneNumber()>
        direccion: <address()>
        representativeName: <firstNameMale()> <lastName()>
        username (unique): <firstNameMale()>
        email (unique): <companyEmail()>
        enabled: <boolean(35)>
        plainPassword: <lexify()>
        grupos: [@Grupos*]
```

Is Alice confusing about `Estado` reference? What could be wrong there?
