### ISSUE TITLE
How to handle ManyToMany relationships in fixtures

### ISSUE THREAD

**Issue by reypm** [nelmio/alice#155]
Hi, I've a problem trying to get this working since I don't have any idea or clue in how to do it. See I have this `n:m` relationship defined in my entity:

```
class TipoTramite
{
    use IdentifierAutogeneratedEntityTrait;
    use NamedEntityTrait;
    use ActiveEntityTrait;

    /**
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\OficinaRegional", inversedBy="tipoTramites", cascade={"persist"})
     * @ORM\JoinTable(name="negocio.solicitud_usuario_oficina_regional", schema="negocio",
     *      joinColumns={@ORM\JoinColumn(name="tipo_tramite_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="oficina_regional_id", referencedColumnName="id")}
     * )
     */
    protected $oficinaRegionals;

    public function __construct() {
        $this->oficinaRegionals = new ArrayCollection();
    }

    public function addOficinaRegionals(OficinaRegional $oficinaRegional) {
        $this->oficinaRegionals[] = $oficinaRegional;
    }
}
```

And this is how my fixtures file looks like:

```
AppBundle\Entity\TipoTramite:
    TipoTramite1:
        nombre: Inscripción
        activo: t
    TipoTramite2:
        nombre: Renovación
        activo: t
    TipoTramite3:
        nombre: Corrección
        activo: t
    TipoTramite4:
        nombre: Inclusión
        activo: t
```

Now, how do I set the relationship in the fixture? It's possible? Any example?
