### ISSUE TITLE
 Could not determine how to assign __set on CLASS

### ISSUE THREAD

**Issue by tristanbes** [nelmio/alice#158]
Hi,

I'm using the latest version of this bundle, and in a fixture file, i want to call a custom setter (`setExtensions`) on my Object called `Site`

The problem is that it throws me an error : 
```
[UnexpectedValueException]                                            
  Could not determine how to assign __set to a Site object
```

My fixture looks like : 
```yml
Site:
    site_1:
        __set: setExtensions
        extensions: [extension_team, extension_article, extension_site_navigation, extension_contact_form, extension_image_slider, extension_location, extension_newsletter, extension_ylly_services, extension_reminder]
```

Do you have an idea on what can cause this please ?
