### ISSUE TITLE
[question] Handling CMF localized fixture objects

### ISSUE THREAD

**Issue by yann-eugone** [nelmio/alice#160]
Hi, before I explain my problem I'd like to thank the contributors of this usefull repository.

I prefixed this issue with `[question]` because I will be very happy that you tell me that there is a way to handle my problem with something existing in this repository.

I'm facing a problem in the following context : 
- Working on a `Symfony2` project
- A project that rely on the `CMF`
- A project with objects that can be translated

I need to load data fixtures, and I need some properties to get translated in several locales.

The problem is : **how** ?

I'm sad to say that I had to implement my own loader to handle objects properties translation with a pattern like this : 

``` yml
My\Bundle\Entity\Object:
    my_object:
        fields:
            aFieldNotTranslated: Hello
            anOtherFieldNotTranslated: World
        i18n:
            en:
                aFieldTranslated: Hello
            fr:
                aFieldTranslated: Bonjour
```

Under the hood, my loader do something like this : 

``` php
public function createObject($object, $data)
{
    foreach ($data['fields'] as $field => $value) {
        $this->setValue($object, $field, $value);
        $this->manager->persist($object);
    }
    foreach ($data['i18n'] as $locale => $fields) {
        $object->setLocale($locale);
        foreach ($fields as $field => $value) {
            $this->setValue($object, $field, $value);
        }
        $this->manager->bindTranslation($object, $locale);
        $this->manager->persist($object);
    }
}
```

I said that I'm sad to do this because this loader is not as powerfull as the Alice's loader (no faker integration for example), and I rather prefer to use always the same loader against all my projects.

Please, if I missed something in the documentation, tell me, and I will test it.

If there is nothing that suit my need here, and if you are interested in, I can try to make a pull request with some features addition to do the job.

Best regards,
Yann
