### ISSUE TITLE
DateTime with fixed date/time

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [nelmio/alice#169]
The documentation seems to suggest that you can enter a fixed date for a DateTime property:
```
Nelmio\Entity\User:
    user:
        username: bob
        birthDate: 1980-10-10
```
This doesn't work if ```birthDate``` is a DateTime property.

The only thing that i've discovered that works is:
```
Nelmio\Entity\User:
    user:
        username: bob
        birthDate: <dateTimeBetween('1980-10-10', '1980-10-10')>
```

As far as I can see, Faker doesn't have a similar function for fixed dates (which I assume this isn't necessary as the Faker library is always used from PHP code). I don't know if this is an issue with Faker or Alice, but the Alice documentation is misleading. 

Or am I missing something?
