### ISSUE TITLE
How work the parameters?

### ISSUE THREAD

**Issue by fchris82** [nelmio/alice#170]
https://github.com/nelmio/alice#parameters

My code:
```yml
parameters:
    type1: <constant('Class::CONST1')>
    type2: <constant('Class::CONST2')>
    type3: <constant('Class::CONST3')>

Entity:
    item{1..20}:
        type: <{type<numberBetween(1, 3)>}>
        date: <dateTimeBetween('2014-01-01', '2014-12-01')>
```

It fails: `Catchable Fatal Error: Argument 3 passed to Nelmio\Alice\Loader\Base::createInstance() must be of the type array, string given, called in vendor/nelmio/alice/src/Nelmio/Alice/Loader/Base.php on line 211 and defined in vendor/nelmio/alice/src/Nelmio/Alice/Loader/Base.php line 315`

With xdebug on Base.php 211. line:
```php
$class = "parameters";
$name = "type1";
$spec = "<constant('Class::CONST1')>"; // This isn't array!
```

What am I doing wrong?
