### ISSUE TITLE
pass multiple providers for one attribute

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#171]
Let's say we have the following data provider:

```yaml
Nelmio\Entity\User:
    user{1..10}:
        username: <username()>
        fullname: <firstName()> <lastName()>
        birthDate: <date()>
        email: <email()>
        favoriteNumber: 50%? <numberBetween(1, 200)>
```

Now, would it be possible to add another data provider for the fullname? For instance in some cases it uses the `<firstName()> <lastName()>`, and in another case, <sentence($nbWords = 6)>? It may seem a little bit strange in this example, but if we have an entity which can be a person or a legal entity, the name is the full name in the first case and a random name in the second one.
