### ISSUE TITLE
Using Custom Faker Data Providers

### ISSUE THREAD

**Issue by Sly36** [nelmio/alice#173]
Hello, first of all thank you for this powerful bundle !

I'm trying to use custom function for my fixtures, i follow the doc in this way : 

```php

class LoadProfileData extends AbstractFixture implements OrderedFixtureInterface
{

    public function load(ObjectManager $manager)
    {
        // load objects from a yaml file
        $loader = new \Nelmio\Alice\Loader\Yaml();
        $objects = $loader->load(__DIR__.'/../DataSets/profiles.yml', $manager, array('providers' => array($this)));

        $persister = new \Nelmio\Alice\ORM\Doctrine($manager);
        $persister->persist($objects);
    }
    
    public function sex()
    {
    	$names = array(
    			'Male',
    			'Female'
    	);
    
    	return $names[array_rand($names)];
    }
    
    public function division()
    {
    	$names = array(
    			'1st division',
    			'2nd division',
    			'3rd division',
    			'4th division',
    	);
    
    	return $names[array_rand($names)];
    }
    
    public function bestFoot()
    {
    	$names = array(
    			'Right',
    			'Left',
    			'Two-footed'
    	);
    
    	return $names[array_rand($names)];
    }
    
    public function contractType()
    {
    	$names = array(
    			'Transfer',
    			'Loan',
    			'Third-party ownership'
    	);
    
    	return $names[array_rand($names)];
    }
    
    public function transferFee()
    {
    	$names = array(
    			'Yes',
    			'No',
    			'To negociate'
    	);
    
    	return $names[array_rand($names)];
    }

    public function getOrder()
    {
        return 6; // the order in which fixtures will be loaded
    }
}
```

and using it in my yaml file this way : 

```yaml
ACME\DemoBundle\Entity\Profile:    
    profile{1..10}:
        firstname: <firstName()>
        lastname: <lastName()>
        birthdate: <dateTimeBetween('-30 years', 'now')>
        height: <numberBetween(165, 200)>
        weight: <numberBetween(65, 110)>
        sex: <sex()>
        nationality: @country_<numberBetween(1, 178)>
        championship: @country_<numberBetween(1, 178)>
        division: <division()>
        position: @position_<numberBetween(1, 17)>
        otherPositions: null
        bestFoot: <bestFoot()>
        injuries: <sentence(15)>
        languages: @language_<numberBetween(1, 17)>
        availability: <dateTimeBetween('now', '+2 years')>
        mobilities: @region_<numberBetween(1, 9)>
        contractType: <contractType()>
        salary: <numberBetween(3000, 20000)>
        transferFee: <transferFee()>
        agent: @agent<current()>->id
```

but i got this error : Unknow formatter sex
