### ISSUE TITLE
Password faker generate a password that alice think it's a reference

### ISSUE THREAD

**Issue by dagio** [nelmio/alice#176]
Hello

I run into a problem using version 1.7.2 of nelmio/alice

UnexpectedValueException: Reference mask "1*hDQ" did not match any existing reference, make sure the object is created after its references in src/Nelmio/Alice/Loader/Base.php:703

It's also here : https://github.com/nelmio/alice/blob/1.x/src/Nelmio/Alice/Loader/Base.php#L723

**Comment by Seldaek** [comment]
Can you paste the fixture definition?

**Comment by dag-io** [comment]
The fixture definition was : 

```
Acme\Bundle\UserBundle\Entity\User:
   user_{1..10}:
        username: <firstName()> <lastName()>
        email: <email()>
        plainPassword: <password()>
        enabled: true
        group: @default_group
        timezone: <timezone()>
        createdAt: <dateTimeBetween('1999-01-01', '1999-01-01')>
        updatedAt: <dateTimeBetween($startDate = '-1 years', $endDate = 'now')>
        locale: <locale()>
```

**Comment by Seldaek** [comment]
oh ok. I guess password returned something like: `@1*hDQ` and then it tried to evaluate that as a reference. Not quite sure how we can fix that.

**Comment by dag-io** [comment]
Maybe we could check the property type. For example here we are talking about password which is a string. We could presume that we do not expect an object reference ?

**Comment by tshelburne** [comment]
Not crazy about this idea, but maybe flag the property as plaintext:

`plainPassword (plaintext): <password()>`

**Comment by theofidry** [comment]
We could check for `@@` to escape the `@` character:

```
'@user' => reference to the fixture 'user'
'@@user' => string 'user'
```

Then you could have a custom provider to secure you password, i.e. it takes the password as an argument and if it begins by `@`, you add an additional `@@` to escape it:

```yaml
Acme\Bundle\UserBundle\Entity\User:
   user_{1..10}:
        username: <firstName()> <lastName()>
        email: <email()>
        plainPassword: <escape(password())>
        enabled: true
        group: @default_group
        timezone: <timezone()>
        createdAt: <dateTimeBetween('1999-01-01', '1999-01-01')>
        updatedAt: <dateTimeBetween($startDate = '-1 years', $endDate = 'now')>
        locale: <locale()>
```

Could potentially be a provided added to Alice as the same way Alice provides a way to refer to another fixture, it should be able to provide a way to escape it.
