### ISSUE TITLE
How to make a data provider

### ISSUE THREAD

**Issue by eschwartz** [nelmio/alice#181]
I'm trying to create a custom data provider which converts fixture objects into doctrine `ArrayCollection` objects. Here's what I've got:

```yml
// fixtures.yml
MyApp\Model\Book:
  bookA: 
   name: 'Book A'
  bookB:
   name: 'Book B'

MyApp\Model\Library:
  books: <ArrayCollection(@bookA, @bookB)>
```

```php
namespace MyApp\Model;

class Library {
   private $books;
   public function setBooks(ArrayCollection $books) {
     $this->books = $books
   }
}
```

```php
class FixtureDataProvider {

	public function ArrayCollection($var_objects) {
		$objects = func_get_args();
		return new ArrayCollection($objects);
	}

}
```

Then in my test case:

```php
class MyTest {
  public function loadFixtures() {
    $loader         = new \Nelmio\Alice\Loader\Yaml('en_US', [new FixtureDataProvider()]);
    return $loader->load(__DIR__ . '/fixtures.yml');
  }
}
```

When I try to load my fixtures, I get
``` 
LogicException : To reference objects by id you must first set a Nelmio\Alice\ORMInterface object on this instance
```

The stack trace brings me to \Loader\Base.php:615 (`checkTypeHints` method)

```php
        if ($hintedClass) {
            if (!$this->manager) {
                throw new \LogicException('To reference objects by id you must first set a Nelmio\Alice\ORMInterface object on this instance');
            }
            $value = $this->manager->find($hintedClass, $value);
        }

        return $value;
```

Any idea what's going on here? Is this the correct way to add custom data providers?
