### ISSUE TITLE
Cant make array of non-entity items

### ISSUE THREAD

**Issue by aequasi** [nelmio/alice#191]
I have a `person` entity, that i'm trying to give `aliases`, but when i try to do the following:

```yml
Acme\Document\Person:
    person{1..100}:
        name: <name()>
        aliases: 5x <name()>
```

`aliases` is getting set as a string. Something like `3x Prof. Neoma Vandervort V`

Is there a way around this, without making a custom provider....?
