### ISSUE TITLE
Add $current variable support in <identity()> provider

### ISSUE THREAD

**Issue by c1tru55** [nelmio/alice#193]
Hey,

it will be very useful if I can use syntax like this:

```yaml
Acme\DemoBundle\Entity\StakeholderFeeTier:
    stakeholderFeeTier{1..15}:
        stakeholder: @stakeholder<current()>
        factorRateMin: 1.01
        factorRateMax: <randomFloat(2, $factorRateMin, 1.50)>
        arrangementPercent: <randomFloat(2, 10, 20)>

    stakeholderFeeTier{16..30}:
        stakeholder: @stakeholder<identity($current - 15)>
        factorRateMin: <randomFloat(2, @stakeholderFeeTier<identity($current - 15)>->factorRateMax, 1.50)>
        factorRateMax: 1.99
        arrangementPercent: <randomFloat(2, 10, 20)>
```
So I can create one-to-many relationships, but I will be able to get reference from one StakeholderFeeTier instance to another for same stakeholder. Thanks
