### ISSUE TITLE
Data Provider: fails to call provider method with arg `0`

### ISSUE THREAD

**Issue by eschwartz** [nelmio/alice#196]
I have a [custom data provider](https://github.com/nelmio/alice/blob/2.x/doc/customizing-data-generation.md#custom-faker-data-providers) which I use to help generate DateTime objects:

```php
class FixtureDataProvider {

	public function DateTime($timeString) {
		return new \DateTime($timeString);
	}

	public function DateTimeTimestamp($timestamp) {
		return new \DateTime('@'.$timestamp);
	}

}
```

It generally works, except if I pass `0` as an argument. For example

```yaml
MyApp\MyModel\User:
  # this calls DateTimeTimestamp with `12345`
  dateModified: <DateTimeTimestamp(12345)>
  # this calls DateTimeTimestamp with no arguments
  dateCreated: <DateTimeTimestamp(0)>
```

When the fixture argument is `0`, no arguments are passed to the `DateTimeTimestamp` method. I would expect `DateTimeTimestamp` to be called with `0`.

Thanks!
