### ISSUE TITLE
How to reference other files' entities

### ISSUE THREAD

**Issue by gouaille** [nelmio/alice#197]
I have a problem regarding entities in my project. 

Given I have two entities such as User and Product. A Product is created by a user.

I decide to create a user.yml loaded by my provider LoadUserData : 

```yaml
Foo\UserBundle\Entity\User:
    user_1:
        name: 'Jean-Mouillette'
    user_2:
        name: 'Gwendoline-Giselle'
```

```php
    public function load(ObjectManager $manager)
    {
        \Nelmio\Alice\Fixtures::load(__DIR__.'/../../Resources/fixtures/user.yml', $manager);
    }

    public function getOrder()
    {
        return 1; 
    }
```

Then i create a product.yml, loaded by the LoadProductData : 

```yaml
Foo\ProductBundle\Entity\Product:
    product_1:
        name: 'Foo XXL'
        user: @user_1
    product_2:
        name: 'Bar XS'
        user: @user_2
```

```php
    public function load(ObjectManager $manager)
    {
        \Nelmio\Alice\Fixtures::load(__DIR__.'/../../Resources/fixtures/products.yml', $manager);
    }

    public function getOrder()
    {
        return 2; 
    }
```

When i load my fixtures, the users are created twice. The first time by the LoadUserData provider, the second time because the LoadProductData can't find the existing items in database but successfully retrieve them from the users.yml.

Is there any option to reference object from other files without passing the real ID ?

Thank's.
