### ISSUE TITLE
Use fixture template

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#198]
Is it possible to declared a template and use it as it is without altering a property?

I mean I have the following template:

```yml
Nelmio\Entity\User:
    user (template):
        username: <username()>
        name: <firstName()>
        lastname: <lastName()>
        city: <city()>
```

I use this template to override a property ok fine: that's  the usual use case. Now besides that, I which to use the template as it is to generate X users. At the moment I did not find another way than using the template while overriding a property:

```
    user{0..50} (extends template):
        username: <username()>
```
