### ISSUE TITLE
Data inheritance

### ISSUE THREAD

**Issue by fspillner** [nelmio/alice#20]
I think, it isn't possible yet to do a data inheritance between data sets. 

Use case: 

You have an User with complex structure and you have to do a lot of duplicates for "basic" data. The solution is to create a base user data for re-usage. The other User data can inherit the data from this base data set. 

Example: 

``` yaml
User: 
    base: 
        username: <username()>
        email: <email()>
        is_admin: 0

    admin: 
        @inherits: base
        is_admin: 1
```

What do you think about this feature?
