### ISSUE TITLE
How setup fixtures for ArrayCollection at entity constructor

### ISSUE THREAD

**Issue by paquitodev** [nelmio/alice#211]
I have read and tried all the things described in [this][1] section of docs but I can't get this working. This is the constructor at entity:

    public function __construct()
    {
        $this->targets = new ArrayCollection();
        $this->targetBrand = new ArrayCollection();
    }

And I tried to bypass using `__construct: false` but get this error:

> [Symfony\Component\Yaml\Exception\ParseException]
>   Unable to parse at line 11 (near " name: <text()>").

This is how the fixtures looks like:

    \PDI\PDOneBundle\Entity\Brand:
        # 3 Brand per Company
        brand{1..3}:
           __construct: false
           name: <name()>
           generic_name: <name()>
           logo_url: <imageUrl(128,128)>
           description: <paragraph()>
           isi_required: <boolean(35)>
           isi_text: <realText()>
           isi_pdf_url: <url()>
           pi_required: <boolean(35)>
           pi_text: <realText()>
           pi_pdf_url: <url()>
           inactive: <boolean(35)>
           company: @company*
           createdAt: <dateTimeThisYear()>
           updatedAt: <dateTimeThisYear()>

If I not set `__construct` then the error turns into this other:

> [Symfony\Component\Debug\Exception\ContextErrorException]
>  Catchable Fatal Error: Argument 1 passed to 
> Doctrine\Common\Collections\ArrayCollection::__construct() must be of the type array, object 
> given, called in /var/www/html/magnific/reptooln_admin/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 555 and defined
 
What is wrong? How I should setup the fixture?

__EDIT:__ I have found [this][2] but how I can use that approach on the fixture I am trying to setup, can any give me some advice?

 [1]: https://github.com/nelmio/alice#specifying-constructor-arguments
 [2]: https://github.com/nelmio/alice/issues/114

**Comment by paquitodev** [comment]
Any advice on this guys @Seldaek @tshelburne? I'm frustrated and can't find a way to move forward at this point so need your help (sorry for ask almost directly when shouldn't be)

**Comment by tshelburne** [comment]
Hi @paquitodev, I would suggest you post questions in a place like StackOverflow where the attention is on finding answers to problems immediately. We will be available to help when we can, but this is really just a list of issues and bugs. 

That said, I appreciate that you're pointing out these particular bugs and problems.

**Comment by paquitodev** [comment]
Hi there, post is already posted at StackOverflow under nelmio-alice tag,
can you take a look? Nobody has answered yet and I'm stucked

**Comment by fschaeffer** [comment]
Hello @paquitodev, which version ofalice are you using?

I'm at 1.x and have no issues to use the arrayCollection.

```php
/**
     * Constructor
     */
    public function __construct()
    {
        $this->media = new ArrayCollection();
        $this->productRelations = new ArrayCollection();
        $this->texts = new ArrayCollection();
        $this->brands = new ArrayCollection();
        $this->subbrands = new ArrayCollection();
        $this->priority = 99;
    }
```

and in fixture.yml
```yaml
AppBundle\Entity\Common\Asset\Asset:
    asset_bare (template):
        priority: 1
        brands: [@brand*]
        subbrands: [@subbrand*]
        group: @assetGroupImage
        filename (unique): <numberBetween(11000000, 11500000)>.eps
        filesize: <numberBetween(12000, 400000)>
        fileextension: eps
        filedate: <dateTimeBetween('-5 years', 'now')>
        isDisplayedInCatalogue: true
        released: <numberBetween(1998,2015)>
        
    assetInstanceIn{1..<?php echo $numberOfItems; ?>} (extends asset_bare):
        name: Private Asset Current <current()>
```
The yaml-file does use the brands relation which was initialized in the constructor but leaves text without any assignment.

So in 1.x it works as one would expect (without setting construct:false)

**Comment by paquitodev** [comment]
I leave this away due to rush and will close the issue for now since I have not time to test this at this moment but I will be back with some test later, anyway thanks @fschaeffer for your support and heads up

**Comment by AlaeddineMessadi** [comment]
I had this issue before, I think you have a `OnetToMany` relation, if yes
change the setter parameter to array and the getter return to `youEntity[] | ArrayCollection`
then in your fixtures put the data in in an array `[]`

**Comment by garak** [comment]
Got the same issue. My entity constructor needs an `ArrayCollection` of related objects, so I created following provider:
```php
<?php

namespace App\DataFixturesProvider;

use Doctrine\Common\Collections\ArrayCollection;

final class CollectionProvider
{
    public static function collection(array $objects): ArrayCollection
    {
        return new ArrayCollection($objects);
    }
}
```

and my fixture is something like:

```yaml
App\Entity\Product:
    product_1:
        __construct:
            id: '<id()>'
            name: 'A product'
            items: '<collection([@item_1])>'
```

But I'm getting the following exception

>[Doctrine\ORM\ORMInvalidArgumentException]                                   
  Expected value of type "App\Entity\Item" for association field "App\Entity\Product#$items",
  got "Nelmio\Alice\Definition\Value\FixtureReferenceValue" instead.

**Comment by beyerz** [comment]
Not sure if this is still relevant as the issue is closed, but I used the built-in identity provider to overcome this.
```yml
App\Entity\MyEntity
  entity1:
    items: '<identity(new Doctrine\Common\Collections\ArrayCollection([@item1,@item2]))>'
```

**Comment by eradionov** [comment]
Seems, that nothing work described above

**Comment by petski** [comment]
Stating the obvious, but just for reference for people getting here:

```
Doctrine\Common\Collections\ArrayCollection:
  items_as_array_collection:
    __construct:
      - ['@item1', '@item2']

App\Entity\MyEntity:
  entity1:
    __construct:
      items: '@items_as_array_collection'
```
