### ISSUE TITLE
Value Objects in included yml files come up as undefined

### ISSUE THREAD

**Issue by kminh** [nelmio/alice#213]
Currently I'm putting all my value object references in a yml file called `vo.yml`, its content is similar to this:
```yaml
Acme\ValueObjects\Email:
    email1:
        value: email@domain.com
```

Then, in my `clients.yml` (in same directory as `vo.yml`), I have the following:
```yaml
include:
    - vo.yml
Acme\AcmeBundle\Entity\Client:
    client1:
        email: @email1
```

This is my fixture class:
```php
<?php

use Nelmio\Alice\Fixtures;

class UserFixtures implements FixtureInterface
{
    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        Fixtures::load([
            '/absolute/path/to/clients.yml'
        ], $manager);
    }
}
```

The error I'm getting is `reference email1 is not defined`. If I move the value objects into clients.yml, it works.

Any insight is appreciated.
