### ISSUE TITLE
Wrong calculation of "adder" method?

### ISSUE THREAD

**Issue by cmfcmf** [nelmio/alice#218]
My yaml looks like so:

``` yml
EventManager_Entity_Event:
  event{1..3} (extends base_event):
    datePeriods: [@dp_event<current()>]
    questions: [@q_lastname_event<current()>, @q_firstname_event<current()>, @q_email_event<current()>]

EventManager_Entity_Question_String:
  q_lastname_event{1..3} (extends lastname_question): {}
  q_firstname_event{1..3} (extends firstname_question): {}

EventManager_Entity_Question_Email:
  q_email_event{1..3} (extends email_question): {}

EventManager_Entity_DatePeriod:
  dp_event{1..3} (extends base_dateperiod): {}
```

My Event entity has the following setters:

``` php
    // There is no addDatePeriods method.


    public function addDatePeriod(EventManager_Entity_DatePeriod $datePeriod)
    {
        $this->datePeriods->add($datePeriod);
    }

    /**
     * @param EventManager_Entity_Question $question
     */
    public function addQuestion($question)
    {
        $question->setEvent($this);
        $this->questions->add($question);
    }

    /**
     * @param EventManager_Entity_Question[] $questions
     */
    public function addQuestions($questions)
    {
        /** @var EventManager_Entity_Question $question */
        foreach ($questions as $question) {
            $this->addQuestion($question);
        }
    }
```

The date periods work just fine, but when Alice tries to add the questions, it uses the wrong method `addQuestions` instead of `addQuestion`.

The method is calculated [here](https://github.com/nelmio/alice/blob/master/src/Nelmio/Alice/Instances/Populator/Methods/ArrayAdd.php#L45) which results in `addQuestions`, which would be fine if Alice passed the array of questions to it, but it does so one by one in [the following foreach loop](https://github.com/nelmio/alice/blob/master/src/Nelmio/Alice/Instances/Populator/Methods/ArrayAdd.php#L46-L49):

``` php
       foreach ($value as $val) {
            $val = $this->typeHintChecker->check($object, $method, $val);
            $object->{$method}($val);
        }
```

Is there something I can do without removing the `addQuestions` setter?

As a sidenote: The variable `$key` is not defined in line 82: https://github.com/nelmio/alice/blob/master/src/Nelmio/Alice/Instances/Populator/Methods/ArrayAdd.php#L82
