### ISSUE TITLE
__construct nested array does not work

### ISSUE THREAD

**Issue by paq85** [nelmio/alice#246]
Running this code:
```yaml
Club\Employee:
  club_employee{1..300}:
    __construct: [<name()>, <randomElement(['trainer', 'other'])>, <randomElement(['trener', 'główny manager', 'manager'])>]
```

Results in following error:
```
[Symfony\Component\Yaml\Exception\ParseException]                                                                                                                                                                                         
  Unexpected characters near ")>, <randomElement(['trener', 'główny manager', 'manager'])>]" at line 59 (near "__construct: [<name()>, <randomElement(['trainer', 'other'])>, <randomElement(['trener', 'główny manager', 'manager'])>]"). 
```

I suspect there's no support for nested arrays by __construct. 
Or am I doing something wrong?

**Comment by ogizanagi** [comment]
I may have encountered a similar / related issue, where this works as expected:

```yml
App\Product\Attribute:
    foo:
        __construct:
            - '@bar'
            - <enum('AttributeName', 'CONTENT_QUANTITY')>
            - 40.0
```

but this does not:
```yml
App\Product\Attribute:
    foo:
        __construct: ['@bar',  <enum('AttributeName', 'CONTENT_QUANTITY')>, 40.0]
```

>                
  [Doctrine\Common\Persistence\Mapping\MappingException]                                                                          
  No mapping file found named 'AttributeNameEnum.orm.yml' for class 'App\Product\Enum\AttributeNameEnum'. 

**This only fails when using a provider with more than one argument, like my enum provider**

However, if you think it is not related to your issue, I'll create a new one.
