### ISSUE TITLE
Optional method call

### ISSUE THREAD

**Issue by appeltaert** [nelmio/alice#249]
Hi, 

Is the [optional data](https://github.com/nelmio/alice/blob/master/doc/complete-reference.md#optional-data) syntax possible for setters? Something like:

```yaml
Nelmio\Entity\User:
    user1:
        username: <username()>
        setLocation: 50% [40.689269, -74.044737]
```

The reason im asking is because this example as shown in the docs is a perfect example, if you were to have User entities with a location or not, where location is 2 separate fields of long/latitude--then i want either both or none of them set.

Another example is companies where some have poboxes or not, and again where you want all of the pobox fields filled in or none of them.

I can think of some hacky solution though a [custom setter](https://github.com/nelmio/alice/blob/master/doc/complete-reference.md#custom-setter), but using the ternary operator for method calls would be awesome.
