### ISSUE TITLE
Syntax for passing parameters to a function

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#253]
In [Alice parameters](https://github.com/nelmio/alice/blob/master/doc/fixtures-refactoring.md#parameters) it shows how to declare parameters, but what's the syntax to pass a parameter to a function?

Exemple of what I would like to achieve:
```yml
parameters:
    myParam: someValue

MyApp\Dummy:
    dummy_0:
        aProp: <words(%myParam%)>
```
