### ISSUE TITLE
Make fixtures with only default value of a template

### ISSUE THREAD

**Issue by Soullivaneuh** [nelmio/alice#277]
If I configure this:

```yaml
AppBundle\Entity\Domain:
    domain (template):
        name: <domainName()>
        server: @server_*
        ftpLogin: <userName()>
        mysqlLogin: <userName()>
    domain_{0..500} (extends domain): ~
```

And load fixtures, I get this error:

```
Catchable Fatal Error: Argument 3 passed to Nelmio\Alice\Fixtures\Builder\Builder::build() must be of the type array, null given, called in /home/sullivan/projects/nexylan/n-admin/vendor/nelmio/alice/src/Nelmio/Alice/Fixtures/Loader.php on line 269 and defined
```

I have to specify at least one property to get it working.

It should work as is IMHO.

Using nelmio/alice `2.1.0`.
