### ISSUE TITLE
Calling PHP expressions

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#283]
Can't we call PHP functions like we do for Faker ones?

```yaml
Dummy:
    dummy_0:
         myDate: <DateTime::createFromFormat(DateTime::ATOM, '2005-06-25T16:43:30+00:00')>
```
