### ISSUE TITLE
Object IDs with slashes

### ISSUE THREAD

**Issue by Soullivaneuh** [nelmio/alice#284]
With the following fixtures file:

```yml
AppBundle\Entity\PuppetPackage:
    puppet_package_app-admin/puppet:
        name: app-admin/puppet
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_dev-db/mysql:
        name: dev-db/mysql
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_dev-db/phpmyadmin:
        name: dev-db/phpmyadmin
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_dev-db/postgresql-server:
        name: dev-db/postgresql-server
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_dev-lang/php:
        name: dev-lang/php
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_kernel:
        name: kernel
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_mail-filter/spamassassin:
        name: mail-filter/spamassassin
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_mail-mta/postfix:
        name: mail-mta/postfix
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_net-dns/bind:
        name: net-dns/bind
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_net-misc/openssh:
        name: net-misc/openssh
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_sys-apps/baselayout:
        name: sys-apps/baselayout
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_sys-apps/openrc:
        name: sys-apps/openrc
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_sys-apps/portage:
        name: sys-apps/portage
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_sys-boot/grub:
        name: sys-boot/grub
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_www-servers/apache:
        name: www-servers/apache
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_www-servers/nginx:
        name: www-servers/nginx
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0

AppBundle\Entity\PuppetClass:
    puppet_class_apache:
        name: Apache
        packages:
            - @puppet_package_www-servers/apache
    puppet_class_php:
        name: PHP
        packages:
            - @puppet_package_dev-lang/php
    puppet_class_mysql:
        name: Mysql
        packages:
            - @puppet_package_dev-db/mysql
            - @puppet_package_dev-db/phpmyadmin
```

I got errors like:

```
Entity with Id @puppet_package_www-servers/apache and Class AppBundle\Entity\PuppetPackage not found
```

If I use `@kernel` package reference, it works. I think there is an issue with IDs containing a `/`.

I dumped IDs on `Loader::populateObjects()` and I get corrects one.

Is that a bug?
