### ISSUE TITLE
Phone number in yml file interpreted as octal

### ISSUE THREAD

**Issue by Yanncha** [nelmio/alice#286]
Hello !
For this sample yml file:
```yml
Nelmio\Entity\User:
    user0:
        username: bob
        phone: 0606
 ```
It seems that the 'phone' field is interpreted as an octal number (turns out to 390 in database - if I use a phone number using some 8 and 9, I don't know how php deals with it but result is modified anyway). Happily, everything is normal with ```phone: '0606'``` and I find the correct 0606 string in database. 

I don't mind this behaviour if it is useful (it looks even possible to enter hex  values with 0x prefix - binary with 0b don't seem to work), but I think it should be documented somewhere to avoid surprises.
