### ISSUE TITLE
how to pass function inside of parameter

### ISSUE THREAD

**Issue by hbakhtiyor** [nelmio/alice#292]
e.g.
```yaml
    parameters:
         address_one: bar
         address_two: foo
         address_three: fizz
         ....
 
    user_{one, two, three, ....}:
        name: bob
        address:  <{address_<current()>}>
```

want to pass like this `<{address_one}>, <{address_two}>, ...` inside of the array

how to achieve this without any duplication?
