### ISSUE TITLE
How to call a setter after the construct 

### ISSUE THREAD

**Issue by petegore** [nelmio/alice#293]
Hey,

I want to create an entity using the __construct() method. 
But then, I immediately want to set another attribute of this entity, but using a setter (because I don't want the constructor to support that attribute creation).
I tried that but, of course, it does not work : 

```yaml
person1:
    __construct:
        - <username()>
        - <password()>
        - etc...
    setPostalAddress(@postalAddress*)
```

Any idea to do that ?
