### ISSUE TITLE
Dealing with MySQL Reserved Terms

### ISSUE THREAD

**Issue by msypes** [nelmio/alice#297]
I just hit a snag of the following nature. Suppose my YAML file has
```
farmboy:
        name: Luke Skywalker
        ship: X-Wing
        group: red
        number: 5
```
This creates the MySQL statement
```    INSERT INTO rebel (name, ship, group, number) VALUES ("Luke Skywalker", "X-Wing", "red", 5) ```
which fails due to a syntax error.
The problem is that **"group"** is a reserved term.
Is there a way to escape such items, such that backticks are inserted appropriately? Or is this a feature request, that backticks should be inserted around everything to be safe? Or should I never use a reserved term as a column name, as it causes a great disturbance in the force, and leads to the dark side?
