### ISSUE TITLE
One to many persist and different quantity

### ISSUE THREAD

**Issue by Wolframcheg** [nelmio/alice#298]
I have problem. I have some Entities as: Team, Coach, Player. I try use fixtures. First I generate players and coaches

```yaml
AppBundle\Entity\Player:
player{1..350}:
    __construct: false
    name: <name()>
    lastName: <lastName()>
    description: <text()>
```
```yaml
AppBundle\Entity\Coach:
coach{1..100}:
    __construct: false
    name: <name()>
    lastName: <lastName()>
    description: <text()>
```
Secondly I generate teams as:
```yaml
AppBundle\Entity\Team:
team{1..25}:
    __construct: false
    description: <text()>
    country (unique): @country*
    players (unique): 14x @player*
    coaches (unique): 4x @coach*
```
I expect that each team will have 14 players and 4 coach. But I have crazy result. Teams have different quantity players and coaches. And some players and coaches doesn't have team. What I doing wrong? Sorry for my bad English
