### ISSUE TITLE
Using dot in the fixtures keys cause referencing to wrong entity

### ISSUE THREAD

**Issue by toonjanssens** [nelmio/alice#309]
Are dots treated a special way in YAML or in this library?

The problem is on the Widget entity. It should pass a WidgetContent object to the Widget entity, but instead it passes a WidgetTranslation object.
It should search for widget_content.* and widget_content_ should be ignored. It looks like the .* part is treated as a regular expression, which means that the _ will also match and the wrong object is passed.

I know using underscores solves the issue, but I want to understand why the dots causes this issue. I prefer to use the dot notation because I find it more readable.

I simplified my fixtures to demonstrate the issue. 

```yml
Entity\WidgetContent:
    widget_content.{1..10}:
        translations:
            - @widget_content_translation.en
            - @widget_content_translation.nl

Entity\WidgetContentTranslation:
    widget_content_translation.en:
        key: value
    widget_content_translation.nl:
        key: value
        
Entity\Widget:
    widget.1:
        content: @widget_content.*
```
