### ISSUE TITLE
Q: It's possible to access current iteration value starting on zero?

### ISSUE THREAD

**Issue by reypm** [nelmio/alice#310]
I am working on a fixture and I need some advice. `carrierId` should take the value of each iteration as in `for` cycle. For example:

```
for ($i=0;$i<10;$i++)  {
   $carrier = new Carrier();
   $carrier->setCarrierId($i);
}
```

It's possible to pass the current iteration value to the fixture to achieve the same as the code above? How? Here is the fixture as I have now but I am missing that iteration value:

```
PlatformAdminBundle\Entity\Carrier:
    carrier{UNKNOW,VIVO,CLARO,TELEMIG,OI,TIM,CTBC,SERCOMTEL,BRT,}:
        name: <current()>
        description: <text()>
        carrierId: 
        createdAt: <dateTimeThisYear()>
        updatedAt: <dateTimeThisYear()>
```

**Comment by tshelburne** [comment]
Hm - if it's important that you have those values as the `current()` value, I'm not totally sure. It would probably be best to do this post-generation and manually persist. Something along the lines of:

```php
// load objects from a yaml file
$loader = new \Nelmio\Alice\Fixtures\Loader();
$carriers = $loader->load(__DIR__.'/carriers.yml');
for ($i=0;$i<count($carriers);$i++)  {
   $carriers[$i]->setCarrierId($i);
}

// optional persistence
$persister = new \Nelmio\Alice\Persister\Doctrine($objectManager);
$persister->persist($carriers);
```

@theofidry Better ideas?

**Comment by theofidry** [comment]
`current()` works fine if I remember right. Otherwise there always a custom provider available although looks overkill.

**Comment by reypm** [comment]
@tshelburne no, it's not important to have those values in there, I just put them because was the best way I found but you tell me which is the best way and I can change my fixture, no problem

**Comment by tshelburne** [comment]
I usually use the range approach: 

```yml
PlatformAdminBundle\Entity\Carrier:
    carrier{1..15}:
        name: <word()>
        description: <text()>
        carrierId: <current()>
        createdAt: <dateTimeThisYear()>
        updatedAt: <dateTimeThisYear()>
```
