### ISSUE TITLE
Multiple method call (adders)

### ISSUE THREAD

**Issue by ogizanagi** [nelmio/alice#313]
Hi !

Is there a way to properly call multiple times a method, like an adder method for instance ?

For instance, the snippet below won't work, because you can't use the same key multiple times in yaml:
```yaml
Catalog\Product\Product:
    foo:
       # [...]
        addImage: ['foo-image', 0]
        addImage: ['bar-image', 1]
```

This adder method accepts multiple arguments, which seems to be a problem for the `ArrayAdd` class, so the snippet below won't work either:

```yaml
Catalog\Product\Product:
    foo:
       # [...]
        images: 
            - ['foo-image', 0]
            - ['bar-image', 1]
```
> Missing argument 2 for Catalog\Product\Product::addImage(), called in [...]/vendor/nelmio/alice/src/Nelmio/Alice/Instances/Populator/Methods/ArrayAdd.php on line 48 and defined 

Is there a simple solution to this ?

**Comment by theofidry** [comment]
I doubt you can do that :( However you could certainly use a [custom faker provider](https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md#custom-faker-data-providers) as a workaround.

**Comment by ogizanagi** [comment]
Actually I don't see how a custom provider could help ? :confused:

**Comment by theofidry** [comment]
Ah soz indeed miserad. Err did you try the `x4` notation?

```yaml
Catalog\Product\Product:
    foo:
       # [...]
        addImage: x5 <image()>
```

**Comment by ogizanagi** [comment]
I've just tried and got:
> Could not determine how to assign addImage to a Catalog\Product\Product object

But anyway I doubt this would have worked like I expected. I don't want to call `addImage` with multiple images as arguments, but call `addImage` multiple times with the necessary arguments to build the image (an `Image` is a simple value object build by the `Product` entity).

**Comment by theofidry** [comment]
Indeed I don't think it would be doable then :/ Interesting feature still.

**Comment by ogizanagi** [comment]
Thanks for your answers anyway. :)

Might be interesting to have a special `_method_calls` key as below in order to solve this:

```yaml
Catalog\Product\Product:
    foo:
       # [...]
       _method_calls:
            - addImage: ['foo-image', 0]
            - addImage: ['bar-image', 1]
```

Any advice on how to achieve this ?

**Comment by theofidry** [comment]
I'm not familiar with this part of the internals sadly so you'll have to wait for @tshelburne :(

That being said, something you could actually do have a little fixtures generator for this one and create a custom loader to add them besides the files you want to load. A bit hacky and brittle though. If you're using Symfony you could get [HautelookAliceBundle](https://github.com/hautelook/AliceBundle) and decorate [the loader](https://github.com/hautelook/AliceBundle/blob/1.x/src/Alice/DataFixtures/Loader.php#L25) to do that.

**Comment by tshelburne** [comment]
@ogizanagi As of right now, I would handle your image population after having loaded all the instances:

```php
$loader = new \Nelmio\Alice\Fixtures\Loader();
$products = $loader->load(__DIR__.'/products.yml');
for ($i=0;$i<count($products);$i++)  {
   $products[$i]->addImage(/* logic for image */);
}
```

Your images here might be other fixtures, value objects, strings, etc. - basically, it's just a bit of hard-coding to set up the auto-load. It's obviously not ideal, but it will get you moving for now.

As for your suggestion, the method calls approach would need to be spec'd quite carefully, and would probably require a much more nuanced notion of lifecycle to be a successful addition. Without that, it sounds like a pretty high risk of stateful nightmares.

**Comment by theofidry** [comment]
@ogizanagi I know it's unlikely to solve your problem at hand (plus it's already an old issue), but I would like to integrate this feature for v3.

We would just need to agree on the syntax. @tshelburne Why not going for `__calls`? That would be consistent with the `__constructor` notation:

```yaml
Catalog\Product\Product:
    foo:
       # [...]
       __calls:
            - setLocation: [0.49, 0.5]
            - addImage: ['foo-image', 0]
            - addImage: ['bar-image', 1]
```

And then we could deprecate the current method call notation: `setLocation: [0.49, 0.5]`.

**Comment by tshelburne** [comment]
@theofidry Cool idea - the only question in my mind is related to timing. Are these calls that happen in the order specified after all the property setters? Or before properties? Or should we be able to specify that? It seems like a really useful feature.

**Comment by theofidry** [comment]
I would go with after the object has been instantiated and populated.

**Comment by tshelburne** [comment]
Cool - I like this idea, let's roll it in to v3.

**Comment by theofidry** [comment]
Design notes:

- method calls should support `(unique)` flags, cf. #387
- method calls should support optional call, cf. #275

Another thing I would like to support is `with*` methods, which returns a new instance instead of mutating the object.

**Comment by ogizanagi** [comment]
I haven't though about the `with*` method of immutable objects, but I'd love to have it, too. 👍

**Comment by hhamon** [comment]
I'm facing the same issue. Do you know when v3 will be released please?

**Comment by theofidry** [comment]
There is no release date yet sadly. I would expect a couple of weeks before
the first beta release and then in depends on how much issues are reported
and how quick they are solved

**Comment by hhamon** [comment]
Thanks! I've just made the following ugly workaround while waiting for the upcoming v3.

```yaml
AppBundle\Entity\Product:
    product_1:
        # ...
        _1_addTag: [foo]
        _2_addTag: [bar]
        _3_addTag: [baz]
        _4_addAttribute: [width, 120]
        _5_addAttribute: [height, 120]
        _6_addAttribute: [size, 3000]
        # ...
```

And in my PHP class.

```php
<?php

class Product
{
    // ...

    public function addTag($name)
    {
        // ...
    }

    public function addAttribute($key, $val)
    {
        // ...
    }

    /**
     * Temporary workaround to be able to call the same method multiple times
     * with Alice. Current Alice version doesn't support calling the same method
     * multiple times and will be implemented in the next upcoming major release.
     *
     * @todo remove this method when Alice library will be >= 3.0
     *
     * @param string $method    The magic invoked method name
     * @param array  $arguments The arguments to pass to the magic invoked method
     */
    public function __call($method, $arguments)
    {
        if (!preg_match('/^(?:set)?\_(?:\d+)?\_(?P<method>[a-z][a-zA-Z0-9]+)$/', $method, $matches)) {
            throw new \BadMethodCallException(sprintf('Trying to call an unsupported method "%s()" on an object of type "%s".', $method, get_class($this)));
        }

        $invokable = $matches['method'];
        $callable = [$this, $invokable];
        if (!method_exists($this, $invokable) || !is_callable($callable)) {
            throw new \BadMethodCallException(sprintf('Method "%s()" does not exist or is not invokable on an object of type "%s".', $invokable, get_class($this)));
        }

        call_user_func_array($callable, $arguments[0]);
    }
}
```

Ugly but works for now...
