### ISSUE TITLE
dateTimes not working with doctrine

### ISSUE THREAD

**Issue by krcrawford** [nelmio/alice#319]
I have a doctrine mapping:
```
subscribeDt:
    type: datetime
    nullable: true
    column: subscribeDT
```
In a Fixture .yml import, I have the following:
```
...
subscribeDt: <dateTime()>
...
```
All manners of dateTime setting results in:
```
PHP Fatal error:  Call to a member function format() on string in /home/vagrant/points-service/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/DateTimeType.php on line 53

[Symfony\Component\Debug\Exception\FatalErrorException]
Error: Call to a member function format() on string
```

I have tried:
`<dateTime()>` and `<(new \DateTime())>` and `<(new DateTime())>`
All result in the same error

I have also tried:
`<dateTime($fake('dateTime', null)>`

**Comment by reinfi** [comment]
I have tested it with <dateTime()> and it works as expected.
Could you show the resulting entity class?

**Comment by krcrawford** [comment]
```
<?php

namespace ****\CurrencyBundle\Entity;

/**
 * User
 */
class User
{
    /**
     * @var integer
     */
    private $uId;

    /**
     * @var string
     */
    private $uuid;

    /**
     * @var integer
     */
    private $userLevelId = '1';

    /**
     * @var integer
     */
    private $kbUuid = '0';

    /**
     * @var string
     */
    private $uEmail;

    /**
     * @var boolean
     */
    private $isUEmailconfirmed = '0';

    /**
     * @var integer
     */
    private $uRegIpLong;

    /**
     * @var string
     */
    private $uCountry = 'US';

    /**
     * @var \DateTime
     */
    private $subscribeDt;

    /**
     * @var string
     */
    private $passwd;

    /**
     * @var string
     */
    private $firstName;

    /**
     * @var string
     */
    private $lastName;

    /**
     * @var string
     */
    private $fullName;

    /**
     * @var integer
     */
    private $facebookUserId;

    /**
     * @var string
     */
    private $facebookAccessToken;

    /**
     * @var string
     */
    private $zip;

    /**
     * @var string
     */
    private $addressStreet;

    /**
     * @var string
     */
    private $addressStreet2;

    /**
     * @var string
     */
    private $addressCity;

    /**
     * @var string
     */
    private $addressState;

    /**
     * @var string
     */
    private $country;

    /**
     * @var string
     */
    private $phone;

    /**
     * @var \DateTime
     */
    private $lastLoginDt;

    /**
     * @var string
     */
    private $lastLoginUa;

    /**
     * @var string
     */
    private $fbEmail;

    /**
     * @var string
     */
    private $fbUsername;

    /**
     * @var \DateTime
     */
    private $passwordModifyDt;

    /**
     * @var boolean
     */
    private $fbConnect = '0';

    /**
     * @var boolean
     */
    private $showSearchOverlay = '1';

    /**
     * @var boolean
     */
    private $showStoreOverlay = '1';

    /**
     * @var boolean
     */
    private $showSweepOverlay = '1';

    /**
     * @var integer
     */
    private $hideStoreOverlay = '0';

    /**
     * @var boolean
     */
    private $flagged = '0';

    /**
     * @var integer
     */
    private $lastLoginIp;

    /**
     * @var boolean
     */
    private $dontDisplayPic = '0';

    /**
     * @var boolean
     */
    private $suspended = '0';

    /**
     * @var string
     */
    private $partnerId;

    /**
     * @var boolean
     */
    private $unsubscribed = '0';

    /**
     * @var boolean
     */
    private $inactive = '0';

    /**
     * @var boolean
     */
    private $is****** = '0';

    /**
     * @var string
     */
    private $userSignupType = 'web_browser';

    /**
     * @var \DateTime
     */
    private $lastActivityDate = 'CURRENT_TIMESTAMP';

    /**
     * @var boolean
     */
    private $firstPurchase = '0';

    /**
     * @var boolean
     */
    private $fbLike = '0';

    /**
     * @var string
     */
    private $activationCode;

    /**
     * @var string
     */
    private $defaultSearch;

    /**
     * @var \DateTime
     */
    private $fbUserBirthday;

    /**
     * @var string
     */
    private $subBrand;

    /**
     * @var string
     */
    private $selectedGiftCards;

    /**
     * @var string
     */
    private $selectedCategories;

    /**
     * @var string
     */
    private $referralId;

    /**
     * @var string
     */
    private $apnToken;

    /**
     * @var string
     */
    private $clickId;

    /**
     * @var integer
     */
    private $postBackPing = '0';

    /**
     * @var integer
     */
    private $invitedBy = '0';

    /**
     * @var string
     */
    private $fbProfileData;

    /**
     * @var boolean
     */
    private $paypalVerified = '0';

    /**
     * @var string
     */
    private $paypalEmail;

    /**
     * @var string
     */
    private $inviteType;

    /**
     * @var string
     */
    private $gender;

    /**
     * @var string
     */
    private $ageRange;

    /**
     * @var string
     */
    private $givenReferralPoints = '0';

    /**
     * @var boolean
     */
    private $loggedInHome = '0';


    /**
     * Get uId
     *
     * @return integer
     */
    public function getUId()
    {
        return $this->uId;
    }

    /**
     * Set uuid
     *
     * @param string $uuid
     *
     * @return User
     */
    public function setUuid($uuid)
    {
        $this->uuid = $uuid;

        return $this;
    }

    /**
     * Get uuid
     *
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Set userLevelId
     *
     * @param integer $userLevelId
     *
     * @return User
     */
    public function setUserLevelId($userLevelId)
    {
        $this->userLevelId = $userLevelId;

        return $this;
    }

    /**
     * Get userLevelId
     *
     * @return integer
     */
    public function getUserLevelId()
    {
        return $this->userLevelId;
    }

    /**
     * Set kbUuid
     *
     * @param integer $kbUuid
     *
     * @return User
     */
    public function setKbUuid($kbUuid)
    {
        $this->kbUuid = $kbUuid;

        return $this;
    }

    /**
     * Get kbUuid
     *
     * @return integer
     */
    public function getKbUuid()
    {
        return $this->kbUuid;
    }

    /**
     * Set uEmail
     *
     * @param string $uEmail
     *
     * @return User
     */
    public function setUEmail($uEmail)
    {
        $this->uEmail = $uEmail;

        return $this;
    }

    /**
     * Get uEmail
     *
     * @return string
     */
    public function getUEmail()
    {
        return $this->uEmail;
    }

    /**
     * Set isUEmailconfirmed
     *
     * @param boolean $isUEmailconfirmed
     *
     * @return User
     */
    public function setIsUEmailconfirmed($isUEmailconfirmed)
    {
        $this->isUEmailconfirmed = $isUEmailconfirmed;

        return $this;
    }

    /**
     * Get isUEmailconfirmed
     *
     * @return boolean
     */
    public function getIsUEmailconfirmed()
    {
        return $this->isUEmailconfirmed;
    }

    /**
     * Set uRegIpLong
     *
     * @param integer $uRegIpLong
     *
     * @return User
     */
    public function setURegIpLong($uRegIpLong)
    {
        $this->uRegIpLong = $uRegIpLong;

        return $this;
    }

    /**
     * Get uRegIpLong
     *
     * @return integer
     */
    public function getURegIpLong()
    {
        return $this->uRegIpLong;
    }

    /**
     * Set uCountry
     *
     * @param string $uCountry
     *
     * @return User
     */
    public function setUCountry($uCountry)
    {
        $this->uCountry = $uCountry;

        return $this;
    }

    /**
     * Get uCountry
     *
     * @return string
     */
    public function getUCountry()
    {
        return $this->uCountry;
    }

    /**
     * Set subscribeDt
     *
     * @param \DateTime $subscribeDt
     *
     * @return User
     */
    public function setSubscribeDt($subscribeDt)
    {
        $this->subscribeDt = $subscribeDt;

        return $this;
    }

    /**
     * Get subscribeDt
     *
     * @return \DateTime
     */
    public function getSubscribeDt()
    {
        return $this->subscribeDt;
    }

    /**
     * Set passwd
     *
     * @param string $passwd
     *
     * @return User
     */
    public function setPasswd($passwd)
    {
        $this->passwd = $passwd;

        return $this;
    }

    /**
     * Get passwd
     *
     * @return string
     */
    public function getPasswd()
    {
        return $this->passwd;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     *
     * @return User
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     *
     * @return User
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Get lastName
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set fullName
     *
     * @param string $fullName
     *
     * @return User
     */
    public function setFullName($fullName)
    {
        $this->fullName = $fullName;

        return $this;
    }

    /**
     * Get fullName
     *
     * @return string
     */
    public function getFullName()
    {
        return $this->fullName;
    }

    /**
     * Set facebookUserId
     *
     * @param integer $facebookUserId
     *
     * @return User
     */
    public function setFacebookUserId($facebookUserId)
    {
        $this->facebookUserId = $facebookUserId;

        return $this;
    }

    /**
     * Get facebookUserId
     *
     * @return integer
     */
    public function getFacebookUserId()
    {
        return $this->facebookUserId;
    }

    /**
     * Set facebookAccessToken
     *
     * @param string $facebookAccessToken
     *
     * @return User
     */
    public function setFacebookAccessToken($facebookAccessToken)
    {
        $this->facebookAccessToken = $facebookAccessToken;

        return $this;
    }

    /**
     * Get facebookAccessToken
     *
     * @return string
     */
    public function getFacebookAccessToken()
    {
        return $this->facebookAccessToken;
    }

    /**
     * Set zip
     *
     * @param string $zip
     *
     * @return User
     */
    public function setZip($zip)
    {
        $this->zip = $zip;

        return $this;
    }

    /**
     * Get zip
     *
     * @return string
     */
    public function getZip()
    {
        return $this->zip;
    }

    /**
     * Set addressStreet
     *
     * @param string $addressStreet
     *
     * @return User
     */
    public function setAddressStreet($addressStreet)
    {
        $this->addressStreet = $addressStreet;

        return $this;
    }

    /**
     * Get addressStreet
     *
     * @return string
     */
    public function getAddressStreet()
    {
        return $this->addressStreet;
    }

    /**
     * Set addressStreet2
     *
     * @param string $addressStreet2
     *
     * @return User
     */
    public function setAddressStreet2($addressStreet2)
    {
        $this->addressStreet2 = $addressStreet2;

        return $this;
    }

    /**
     * Get addressStreet2
     *
     * @return string
     */
    public function getAddressStreet2()
    {
        return $this->addressStreet2;
    }

    /**
     * Set addressCity
     *
     * @param string $addressCity
     *
     * @return User
     */
    public function setAddressCity($addressCity)
    {
        $this->addressCity = $addressCity;

        return $this;
    }

    /**
     * Get addressCity
     *
     * @return string
     */
    public function getAddressCity()
    {
        return $this->addressCity;
    }

    /**
     * Set addressState
     *
     * @param string $addressState
     *
     * @return User
     */
    public function setAddressState($addressState)
    {
        $this->addressState = $addressState;

        return $this;
    }

    /**
     * Get addressState
     *
     * @return string
     */
    public function getAddressState()
    {
        return $this->addressState;
    }

    /**
     * Set country
     *
     * @param string $country
     *
     * @return User
     */
    public function setCountry($country)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Get country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Set phone
     *
     * @param string $phone
     *
     * @return User
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Get phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Set lastLoginDt
     *
     * @param \DateTime $lastLoginDt
     *
     * @return User
     */
    public function setLastLoginDt($lastLoginDt)
    {
        $this->lastLoginDt = $lastLoginDt;

        return $this;
    }

    /**
     * Get lastLoginDt
     *
     * @return \DateTime
     */
    public function getLastLoginDt()
    {
        return $this->lastLoginDt;
    }

    /**
     * Set lastLoginUa
     *
     * @param string $lastLoginUa
     *
     * @return User
     */
    public function setLastLoginUa($lastLoginUa)
    {
        $this->lastLoginUa = $lastLoginUa;

        return $this;
    }

    /**
     * Get lastLoginUa
     *
     * @return string
     */
    public function getLastLoginUa()
    {
        return $this->lastLoginUa;
    }

    /**
     * Set fbEmail
     *
     * @param string $fbEmail
     *
     * @return User
     */
    public function setFbEmail($fbEmail)
    {
        $this->fbEmail = $fbEmail;

        return $this;
    }

    /**
     * Get fbEmail
     *
     * @return string
     */
    public function getFbEmail()
    {
        return $this->fbEmail;
    }

    /**
     * Set fbUsername
     *
     * @param string $fbUsername
     *
     * @return User
     */
    public function setFbUsername($fbUsername)
    {
        $this->fbUsername = $fbUsername;

        return $this;
    }

    /**
     * Get fbUsername
     *
     * @return string
     */
    public function getFbUsername()
    {
        return $this->fbUsername;
    }

    /**
     * Set passwordModifyDt
     *
     * @param \DateTime $passwordModifyDt
     *
     * @return User
     */
    public function setPasswordModifyDt($passwordModifyDt)
    {
        $this->passwordModifyDt = $passwordModifyDt;

        return $this;
    }

    /**
     * Get passwordModifyDt
     *
     * @return \DateTime
     */
    public function getPasswordModifyDt()
    {
        return $this->passwordModifyDt;
    }

    /**
     * Set fbConnect
     *
     * @param boolean $fbConnect
     *
     * @return User
     */
    public function setFbConnect($fbConnect)
    {
        $this->fbConnect = $fbConnect;

        return $this;
    }

    /**
     * Get fbConnect
     *
     * @return boolean
     */
    public function getFbConnect()
    {
        return $this->fbConnect;
    }

    /**
     * Set showSearchOverlay
     *
     * @param boolean $showSearchOverlay
     *
     * @return User
     */
    public function setShowSearchOverlay($showSearchOverlay)
    {
        $this->showSearchOverlay = $showSearchOverlay;

        return $this;
    }

    /**
     * Get showSearchOverlay
     *
     * @return boolean
     */
    public function getShowSearchOverlay()
    {
        return $this->showSearchOverlay;
    }

    /**
     * Set showStoreOverlay
     *
     * @param boolean $showStoreOverlay
     *
     * @return User
     */
    public function setShowStoreOverlay($showStoreOverlay)
    {
        $this->showStoreOverlay = $showStoreOverlay;

        return $this;
    }

    /**
     * Get showStoreOverlay
     *
     * @return boolean
     */
    public function getShowStoreOverlay()
    {
        return $this->showStoreOverlay;
    }

    /**
     * Set showSweepOverlay
     *
     * @param boolean $showSweepOverlay
     *
     * @return User
     */
    public function setShowSweepOverlay($showSweepOverlay)
    {
        $this->showSweepOverlay = $showSweepOverlay;

        return $this;
    }

    /**
     * Get showSweepOverlay
     *
     * @return boolean
     */
    public function getShowSweepOverlay()
    {
        return $this->showSweepOverlay;
    }

    /**
     * Set hideStoreOverlay
     *
     * @param integer $hideStoreOverlay
     *
     * @return User
     */
    public function setHideStoreOverlay($hideStoreOverlay)
    {
        $this->hideStoreOverlay = $hideStoreOverlay;

        return $this;
    }

    /**
     * Get hideStoreOverlay
     *
     * @return integer
     */
    public function getHideStoreOverlay()
    {
        return $this->hideStoreOverlay;
    }

    /**
     * Set flagged
     *
     * @param boolean $flagged
     *
     * @return User
     */
    public function setFlagged($flagged)
    {
        $this->flagged = $flagged;

        return $this;
    }

    /**
     * Get flagged
     *
     * @return boolean
     */
    public function getFlagged()
    {
        return $this->flagged;
    }

    /**
     * Set lastLoginIp
     *
     * @param integer $lastLoginIp
     *
     * @return User
     */
    public function setLastLoginIp($lastLoginIp)
    {
        $this->lastLoginIp = $lastLoginIp;

        return $this;
    }

    /**
     * Get lastLoginIp
     *
     * @return integer
     */
    public function getLastLoginIp()
    {
        return $this->lastLoginIp;
    }

    /**
     * Set dontDisplayPic
     *
     * @param boolean $dontDisplayPic
     *
     * @return User
     */
    public function setDontDisplayPic($dontDisplayPic)
    {
        $this->dontDisplayPic = $dontDisplayPic;

        return $this;
    }

    /**
     * Get dontDisplayPic
     *
     * @return boolean
     */
    public function getDontDisplayPic()
    {
        return $this->dontDisplayPic;
    }

    /**
     * Set suspended
     *
     * @param boolean $suspended
     *
     * @return User
     */
    public function setSuspended($suspended)
    {
        $this->suspended = $suspended;

        return $this;
    }

    /**
     * Get suspended
     *
     * @return boolean
     */
    public function getSuspended()
    {
        return $this->suspended;
    }

    /**
     * Set partnerId
     *
     * @param string $partnerId
     *
     * @return User
     */
    public function setPartnerId($partnerId)
    {
        $this->partnerId = $partnerId;

        return $this;
    }

    /**
     * Get partnerId
     *
     * @return string
     */
    public function getPartnerId()
    {
        return $this->partnerId;
    }

    /**
     * Set unsubscribed
     *
     * @param boolean $unsubscribed
     *
     * @return User
     */
    public function setUnsubscribed($unsubscribed)
    {
        $this->unsubscribed = $unsubscribed;

        return $this;
    }

    /**
     * Get unsubscribed
     *
     * @return boolean
     */
    public function getUnsubscribed()
    {
        return $this->unsubscribed;
    }

    /**
     * Set inactive
     *
     * @param boolean $inactive
     *
     * @return User
     */
    public function setInactive($inactive)
    {
        $this->inactive = $inactive;

        return $this;
    }

    /**
     * Get inactive
     *
     * @return boolean
     */
    public function getInactive()
    {
        return $this->inactive;
    }

    /**
     * Set is******
     *
     * @param boolean $is******
     *
     * @return User
     */
    public function setIs******($is******)
    {
        $this->is****** = $is******;

        return $this;
    }

    /**
     * Get is******
     *
     * @return boolean
     */
    public function getIs******()
    {
        return $this->is******;
    }

    /**
     * Set userSignupType
     *
     * @param string $userSignupType
     *
     * @return User
     */
    public function setUserSignupType($userSignupType)
    {
        $this->userSignupType = $userSignupType;

        return $this;
    }

    /**
     * Get userSignupType
     *
     * @return string
     */
    public function getUserSignupType()
    {
        return $this->userSignupType;
    }

    /**
     * Set lastActivityDate
     *
     * @param \DateTime $lastActivityDate
     *
     * @return User
     */
    public function setLastActivityDate($lastActivityDate)
    {
        $this->lastActivityDate = $lastActivityDate;

        return $this;
    }

    /**
     * Get lastActivityDate
     *
     * @return \DateTime
     */
    public function getLastActivityDate()
    {
        return $this->lastActivityDate;
    }

    /**
     * Set firstPurchase
     *
     * @param boolean $firstPurchase
     *
     * @return User
     */
    public function setFirstPurchase($firstPurchase)
    {
        $this->firstPurchase = $firstPurchase;

        return $this;
    }

    /**
     * Get firstPurchase
     *
     * @return boolean
     */
    public function getFirstPurchase()
    {
        return $this->firstPurchase;
    }

    /**
     * Set fbLike
     *
     * @param boolean $fbLike
     *
     * @return User
     */
    public function setFbLike($fbLike)
    {
        $this->fbLike = $fbLike;

        return $this;
    }

    /**
     * Get fbLike
     *
     * @return boolean
     */
    public function getFbLike()
    {
        return $this->fbLike;
    }

    /**
     * Set activationCode
     *
     * @param string $activationCode
     *
     * @return User
     */
    public function setActivationCode($activationCode)
    {
        $this->activationCode = $activationCode;

        return $this;
    }

    /**
     * Get activationCode
     *
     * @return string
     */
    public function getActivationCode()
    {
        return $this->activationCode;
    }

    /**
     * Set defaultSearch
     *
     * @param string $defaultSearch
     *
     * @return User
     */
    public function setDefaultSearch($defaultSearch)
    {
        $this->defaultSearch = $defaultSearch;

        return $this;
    }

    /**
     * Get defaultSearch
     *
     * @return string
     */
    public function getDefaultSearch()
    {
        return $this->defaultSearch;
    }

    /**
     * Set fbUserBirthday
     *
     * @param \DateTime $fbUserBirthday
     *
     * @return User
     */
    public function setFbUserBirthday($fbUserBirthday)
    {
        $this->fbUserBirthday = $fbUserBirthday;

        return $this;
    }

    /**
     * Get fbUserBirthday
     *
     * @return \DateTime
     */
    public function getFbUserBirthday()
    {
        return $this->fbUserBirthday;
    }

    /**
     * Set subBrand
     *
     * @param string $subBrand
     *
     * @return User
     */
    public function setSubBrand($subBrand)
    {
        $this->subBrand = $subBrand;

        return $this;
    }

    /**
     * Get subBrand
     *
     * @return string
     */
    public function getSubBrand()
    {
        return $this->subBrand;
    }

    /**
     * Set selectedGiftCards
     *
     * @param string $selectedGiftCards
     *
     * @return User
     */
    public function setSelectedGiftCards($selectedGiftCards)
    {
        $this->selectedGiftCards = $selectedGiftCards;

        return $this;
    }

    /**
     * Get selectedGiftCards
     *
     * @return string
     */
    public function getSelectedGiftCards()
    {
        return $this->selectedGiftCards;
    }

    /**
     * Set selectedCategories
     *
     * @param string $selectedCategories
     *
     * @return User
     */
    public function setSelectedCategories($selectedCategories)
    {
        $this->selectedCategories = $selectedCategories;

        return $this;
    }

    /**
     * Get selectedCategories
     *
     * @return string
     */
    public function getSelectedCategories()
    {
        return $this->selectedCategories;
    }

    /**
     * Set referralId
     *
     * @param string $referralId
     *
     * @return User
     */
    public function setReferralId($referralId)
    {
        $this->referralId = $referralId;

        return $this;
    }

    /**
     * Get referralId
     *
     * @return string
     */
    public function getReferralId()
    {
        return $this->referralId;
    }

    /**
     * Set apnToken
     *
     * @param string $apnToken
     *
     * @return User
     */
    public function setApnToken($apnToken)
    {
        $this->apnToken = $apnToken;

        return $this;
    }

    /**
     * Get apnToken
     *
     * @return string
     */
    public function getApnToken()
    {
        return $this->apnToken;
    }

    /**
     * Set clickId
     *
     * @param string $clickId
     *
     * @return User
     */
    public function setClickId($clickId)
    {
        $this->clickId = $clickId;

        return $this;
    }

    /**
     * Get clickId
     *
     * @return string
     */
    public function getClickId()
    {
        return $this->clickId;
    }

    /**
     * Set postBackPing
     *
     * @param integer $postBackPing
     *
     * @return User
     */
    public function setPostBackPing($postBackPing)
    {
        $this->postBackPing = $postBackPing;

        return $this;
    }

    /**
     * Get postBackPing
     *
     * @return integer
     */
    public function getPostBackPing()
    {
        return $this->postBackPing;
    }

    /**
     * Set invitedBy
     *
     * @param integer $invitedBy
     *
     * @return User
     */
    public function setInvitedBy($invitedBy)
    {
        $this->invitedBy = $invitedBy;

        return $this;
    }

    /**
     * Get invitedBy
     *
     * @return integer
     */
    public function getInvitedBy()
    {
        return $this->invitedBy;
    }

    /**
     * Set fbProfileData
     *
     * @param string $fbProfileData
     *
     * @return User
     */
    public function setFbProfileData($fbProfileData)
    {
        $this->fbProfileData = $fbProfileData;

        return $this;
    }

    /**
     * Get fbProfileData
     *
     * @return string
     */
    public function getFbProfileData()
    {
        return $this->fbProfileData;
    }

    /**
     * Set paypalVerified
     *
     * @param boolean $paypalVerified
     *
     * @return User
     */
    public function setPaypalVerified($paypalVerified)
    {
        $this->paypalVerified = $paypalVerified;

        return $this;
    }

    /**
     * Get paypalVerified
     *
     * @return boolean
     */
    public function getPaypalVerified()
    {
        return $this->paypalVerified;
    }

    /**
     * Set paypalEmail
     *
     * @param string $paypalEmail
     *
     * @return User
     */
    public function setPaypalEmail($paypalEmail)
    {
        $this->paypalEmail = $paypalEmail;

        return $this;
    }

    /**
     * Get paypalEmail
     *
     * @return string
     */
    public function getPaypalEmail()
    {
        return $this->paypalEmail;
    }

    /**
     * Set inviteType
     *
     * @param string $inviteType
     *
     * @return User
     */
    public function setInviteType($inviteType)
    {
        $this->inviteType = $inviteType;

        return $this;
    }

    /**
     * Get inviteType
     *
     * @return string
     */
    public function getInviteType()
    {
        return $this->inviteType;
    }

    /**
     * Set gender
     *
     * @param string $gender
     *
     * @return User
     */
    public function setGender($gender)
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Get gender
     *
     * @return string
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Set ageRange
     *
     * @param string $ageRange
     *
     * @return User
     */
    public function setAgeRange($ageRange)
    {
        $this->ageRange = $ageRange;

        return $this;
    }

    /**
     * Get ageRange
     *
     * @return string
     */
    public function getAgeRange()
    {
        return $this->ageRange;
    }

    /**
     * Set givenReferralPoints
     *
     * @param string $givenReferralPoints
     *
     * @return User
     */
    public function setGivenReferralPoints($givenReferralPoints)
    {
        $this->givenReferralPoints = $givenReferralPoints;

        return $this;
    }

    /**
     * Get givenReferralPoints
     *
     * @return string
     */
    public function getGivenReferralPoints()
    {
        return $this->givenReferralPoints;
    }

    /**
     * Set loggedInHome
     *
     * @param boolean $loggedInHome
     *
     * @return User
     */
    public function setLoggedInHome($loggedInHome)
    {
        $this->loggedInHome = $loggedInHome;

        return $this;
    }

    /**
     * Get loggedInHome
     *
     * @return boolean
     */
    public function getLoggedInHome()
    {
        return $this->loggedInHome;
    }
}

**Comment by krcrawford** [comment]
Doctrine Mapping:
```
****\CurrencyBundle\Entity\User:
    type: entity
    table: u
    indexes:
        uuid:
            columns:
                - uuid
        firstName:
            columns:
                - firstName
        lastName:
            columns:
                - lastName
        addressCity:
            columns:
                - addressCity
        addressState:
            columns:
                - addressState
        country:
            columns:
                - country
        activattion_code:
            columns:
                - activation_code
    uniqueConstraints:
        uEmail:
            columns:
                - uEmail
        fbEmail:
            columns:
                - fbEmail
    id:
        uId:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: uID
            generator:
                strategy: IDENTITY
    fields:
        uuid:
            type: string
            nullable: true
            length: 36
            options:
                fixed: true
        userLevelId:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
            column: user_level_id
        kbUuid:
            type: bigint
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: kbUUID
        uEmail:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: uEmail
        isUEmailconfirmed:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: isuEmailConfirmed
        uRegIpLong:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: uRegIPLong
        uCountry:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: US
            column: uCountry
        subscribeDt:
            type: datetime
            nullable: true
            column: subscribeDT
        passwd:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        firstName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: firstName
        lastName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: lastName
        fullName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: fullName
        facebookUserId:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: facebookUserID
        facebookAccessToken:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: facebookAccessToken
        zip:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        addressStreet:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: addressStreet
        addressStreet2:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: addressStreet2
        addressCity:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: addressCity
        addressState:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: addressState
        country:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        phone:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        lastLoginDt:
            type: datetime
            nullable: true
            column: lastLoginDT
        lastLoginUa:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: lastLoginUA
        fbEmail:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: fbEmail
        fbUsername:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: fbUsername
        passwordModifyDt:
            type: datetime
            nullable: false
            column: passwordModifyDT
        fbConnect:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: fbConnect
        showSearchOverlay:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: showSearchOverlay
        showStoreOverlay:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: showStoreOverlay
        showSweepOverlay:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: showSweepOverlay
        hideStoreOverlay:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: hideStoreOverlay
        flagged:
            type: boolean
            nullable: false
            options:
                default: '0'
        lastLoginIp:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: lastLoginIp
        dontDisplayPic:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: dontDisplayPic
        suspended:
            type: boolean
            nullable: false
            options:
                default: '0'
        partnerId:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: partnerId
        unsubscribed:
            type: boolean
            nullable: false
            options:
                default: '0'
        inactive:
            type: boolean
            nullable: false
            options:
                default: '0'
        is******:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is******
        userSignupType:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: web_browser
            column: userSignupType
        lastActivityDate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: lastActivityDate
        firstPurchase:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: firstPurchase
        fbLike:
            type: boolean
            nullable: false
            options:
                default: '0'
        activationCode:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: activation_code
        defaultSearch:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: defaultSearch
        fbUserBirthday:
            type: date
            nullable: true
            column: fb_user_birthday
        subBrand:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: sub_brand
        selectedGiftCards:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
            column: selected_gift_cards
        selectedCategories:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
            column: selected_categories
        referralId:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: referral_id
        apnToken:
            type: string
            nullable: false
            length: 64
            options:
                fixed: true
            column: apntoken
        clickId:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: click_id
        postBackPing:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: postBackPing
        invitedBy:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: invited_by
        fbProfileData:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: fb_profile_data
        paypalVerified:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: paypal_verified
        paypalEmail:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: paypal_email
        inviteType:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: invite_type
        gender:
            type: string
            nullable: false
            length: 1
            options:
                fixed: true
        ageRange:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: age_range
        givenReferralPoints:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: '0'
            column: given_referral_points
        loggedInHome:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: loggedInHome
    lifecycleCallbacks: {  }
    repositoryClass: ****\CurrencyBundle\Entity\UserRepository
```
