### ISSUE TITLE
id = 0 for all references persisted

### ISSUE THREAD

**Issue by cordoval** [nelmio/alice#33]
my tables are persisting like:

``` yml
VendorBundle\Entity\SummaryClassification:
    classification1:
        name: 'thank you Jordi'
```

and

``` yml
CordovalBundle\Entity\Summary:
    Summary1:
        name: 'King''s Pawn Game'
        classification: @classification1->getId()
        parentid: 0
```

but the problem is i am getting classification 0 in the table

what could it be? why?

I am dumping the object right before ORM\Dorctrine

``` php
 /**
     * {@inheritDoc}
     */
    public function persist(array $objects)
    {
        foreach ($objects as $object) {
            if (get_class($object) == 'CordovalBundle\Entity\Summary') {
                ladybug_dump_die($object);
            }

            $this->om->persist($object);
        }

        if ($this->flush) {
            $this->om->flush();
        }
    }
```

and I am getting the column value has a string:

```
\[CordovalBundle\Entity\Summaryclassification\]: string(24) "@classification1->getId()"
```

with or without @ it does not pick the actual id value
