### ISSUE TITLE
Document ListName feature

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#330]
``` yaml
Dummy:
  dummy{first, second, third}:
    # ...
```

is equivalent to:

``` yaml
Dummy:
  dummy_first:
    # ...
  dummy_second:
    # ...
  dummy_third:
    # ...
```
