### ISSUE TITLE
Deprecate parser context for v3

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#342]
After working on the parsers (#340), I noticed that a context, accessible in the parsed files, can be set at the parsers level.

For example:

```php
use Nelmio\Alice\Fixtures\Parser\Methods\Php as PhpParser;

$context = ['foo' => 'bar'];
$parser = new PhpParser($context);
```

```php
// parsed_file.php
// has access to $context
return [
  'Dummy' => [
    'dummy0' => [
      'id' => 0,
      'name' => $context['foo'],
    ]
  ]
]
```

In YAML it is a bit more tricky as you cannot use raw PHP. Instead you have to convert your yaml file into a PHP one first:

```php
use Nelmio\Alice\Fixtures\Parser\Methods\Yaml as YamlParser;

$context = ['foo' => 'bar'];
$parser = new YamlParser($context);
```

```yaml
# parsed_file.yml.php
# has access to $context
Dummy:
    dummy0:
      id: 0
      name: <?php echo $context['foo']; ?> # has to be followed by a blank line... ugly workaround

# ...
```

I find this feature questionable and it requires some workaround to make it possible. Removing it would be much simpler. The only useful usage I found was in the code base to inject the loader itself to inject the parameters. Taking a look at [this diagram](https://github.com/nelmio/alice/issues/265#issuecomment-217417501), this could be handled in the `Builder` instead.

@tshelburne WDYT?
