### ISSUE TITLE
Composite and Dynamic parameters

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#354]
As of now, the following won't work:

```yaml
parameters:
    username_alice: Alice
    username_bob: Bob

Nelmio\Alice\support\models\User:
    user_{alice, bob}:
        username: '<{username_<current()>}>' # expect respectively 'Alice' and 'Bob'
```

```yaml
parameters:
    key1: NaN
    key2: Bat
    composite: '<{key1}> <{key2>!'

Nelmio\Alice\support\models\User:
    user0:
        username: '<{composite}>' # expect 'Nan Bat!'
```
