### ISSUE TITLE
current() usage in identity()?

### ISSUE THREAD

**Issue by matt-usurp** [nelmio/alice#360]
Is it possible (and if so its not clear from the documentation) to make use of the `<current()>` syntax within something like `<(strtolower(??))>`?

Essentially I want to be able to be able to get this:

```YAML
SomeClass:
  SomeReference{Name}:
    name: <current()>
    alias: <(strtolower($current))>
```
