### ISSUE TITLE
Unique values handling

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#387]
As of now, [from the doc](https://github.com/nelmio/alice/blob/2.x/doc/complete-reference.md#handling-unique-constraints), the only usage allowed of `(unique)` is in properties:

```yaml
Nelmio\Entity\User:
    user{1..10}:
        username (unique): <username()>
```

There is several problems to that.

### Handling unique with arrays

As reported in #172, when applied to an array, `(unique)` is applied only to the serialized array value, i.e. the following will not work as you might expect:

```yaml
Nelmio\Entity\User:
    user_{1..100}:
        phones (unique): <numberBetween(0, 3)>x @phone_*
```

I suggest the keep the current behaviour if the array notation is given, but change the behaviour for applying the unique constraint to the array elements instead, i.e. in the case above, if the first value is `@phone_1`, the second cannot be `@phone_1` anymore.

**This is a user-land breaking change**, but I would still like to do it for the following reasons:

- This looks like a more common use case
- Having "unique" arrays is bothersome: what is unique for an array? Strict equality or equivalent?

I would love to have it obviously, but I would prefer to be more pragmatic for now and eventually think about it later, either after v3 is almost finished or for v4 otherwise.

### Handling unique with function calls

We have to cases where there is "function calls", the first one is when specifying a constructor:

And the other one is by adding the calls feature (cf. #313):

```yaml
Nelmio\Entity\User:
    user_{1..100}:
        __construct:
            create: [ ... ]
```

```yaml
Nelmio\Entity\User:
    user_{1..100}:
       __calls:
            - setLocation: [ ... ]
```

One trick would be to it like so:

```yaml
Nelmio\Entity\User:
    user_{1..100}:
       __calls:
            - setLocation:
                - 0 (unique): arg0
                - 1: arg1
                - 2 (unique): arg2
```
