### ISSUE TITLE
How do I check if fixtures include reference?

### ISSUE THREAD

**Issue by Artem-Panasenko** [nelmio/alice#391]
I have some files with fixtures. For example:
- posts.yml
```yaml
Model\User:
  userMain:
    name: Test
Model\Post:
  post1:
    user: '@userMain'
    title: Test title
```
- "independent_post.yml"
```yaml
### I want to check existing reference @userMain 
### if we load 2 files (posts.yml and independent_post.yml)
### And if we load only second file I want to create/overwrite entity @userMain
Model\Post:
  post2:
    user: '@userMain'
    title: Test title 2
```
My question in comments. Thank you for answer.
