### ISSUE TITLE
Doctrine Associations Problem

### ISSUE THREAD

**Issue by tloeffler** [nelmio/alice#418]
Hello,

I dont't know if this a problem with alice or faker or doctrine, but I found this:

In my tests I create fixtures with Yaml file(s). No problem and very easy. I created some entities with relations and in the database these relations are stored fine.

In the test can receive an entity (findOneBy). When I want to lazy load the bound entities by an oeration like ->count() these bound entities are not loaded.

My solution is to call entitymanager->clear() after creation of the fixtures. Then all relations does function properly and the entities are loaded when I call an operation on it.

I don't think it is a problem with Alice because this problem occured before I used Alice when I wrote my own fixtures directly with doctrine.

**Comment by theofidry** [comment]
The Doctrine layer is very thing: https://github.com/nelmio/alice/blob/2.x/src/Nelmio/Alice/Fixtures.php#L162-L177 and [`Doctrine::persist()`](https://github.com/nelmio/alice/blob/2.x/src/Nelmio/Alice/Persister/Doctrine.php#L50-L63) only do a `persist()` then `flush()`.

That said I'm having a bit of trouble to see what you're doing exactly, so I may miss something.

**Comment by tloeffler** [comment]
OK, then here are some code:

A snippet of my fixtures:

```yaml
AppBundle\Entity\Service:
    random_service_{1..5}:
        name (unique): <serviceName()>
        description: 50%? <sentence()>
        created: <dateTimeBetween('-365 days', 'now')>
        changed: <dateTimeBetween($created, 'now')>
        roles: <numberBetween(1,5)>x @random_role_*

AppBundle\Entity\Role:
    random_role_{1..5}:
        name (unique): <roleName()>
        description: 50%? <sentence()>
        created: <dateTimeBetween('-365 days', 'now')>
        changed: <dateTimeBetween($created, 'now')>

AppBundle\Entity\Account:
    random_account_{1..3}:
        name (unique): <accountName()>
        description: 50%? <sentence()>
        password: <createPassword(@random_account*)>
        expires: <dateTimeBetween('+14 days', '+365 days')>
        locked: <boolean(10)>
        enabled: <boolean(75)>
        created: <dateTimeBetween('-365 days', 'now')>
        changed: <dateTimeBetween($created, 'now')>
        roles: <numberBetween(1,5)>x @random_role_*
```

The methods roleName, serviceName or accountName are simple string creator functions and placed ion the fixture provider.


This is the important thing, the fixture creation in my test base class:

```php
/**
     * Load fixtures.
     *
     * @param bool $purge
     * @return array Referenceobjects
     */
    protected function loadTestFixtures(bool $purge = false): array
    {
        if ($purge) {
            $this->purge();
        }
        $ref = Fixtures::load(
            $this->container->get('kernel')
                ->locateResource('@AppBundle/DataFixtures/TestFixtures/TestSuiteFixtures.yml'),
            $this->em,
            [
                'providers' => [new FixtureProvider($this->container)]
            ]
        );

        $this->em->clear(); //<-- this is important

        return $ref;
    }
```

And here the code which leads to ignoring the mappedBy-Mappings:

```php
//...
return Fixtures::load(
            $this->container->get('kernel')
                ->locateResource('@AppBundle/DataFixtures/TestFixtures/TestSuiteFixtures.yml'),
            $this->em,
            [
                'providers' => [new FixtureProvider($this->container)]
            ]
        );
```

Here are a mapping example:

```php
//... Mapping in Role.php
/**
     * @var ArrayCollection<Account>
     *
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Account", mappedBy="roles", cascade={"all"})
     *
     */
    protected $accounts;
```

```php
//...Mapping in Account.php
/**
     * @var ArrayCollection<Role>
     *
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Role", inversedBy="accounts")
     * @ORM\JoinTable(name="account_roles")
     */
    protected $roles;
```
