### ISSUE TITLE
Reference conflicts

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#420]
For a given fixture set:

```yaml
Nelmio\Entity\User:
  user1: {}

Nelmio\Entity\Group:
  group1: {}
```

The array of objects you get from the loader will be:

```php
[
  'user1' => Nelmio\Entity\User#object,
  'group1' => Nelmio\Entity\Group#object,
]
```

This lead to a very simple problem, if you have:

```yaml
Nelmio\Entity\User:
  user1: {}

Nelmio\Entity\Group:
  user1: {} # same key as for Nelmio\Entity\User
```

Then you will get:

```php
[
  'user1' => Nelmio\Entity\Group#object,
]
```

As it is now, I'm not sure if we can do anything about it, we could potentially change it to have references relative to the class, e.g.:

```php
[
  'Nelmio\Entity\User#user1' => Nelmio\Entity\User#object,
  'Nelmio\Entity\Group#group1' => Nelmio\Entity\Group#object,
]
```

But that's potentially a big BC. Another solution is to keep it as it is, but then it would be nice to have a warning somewhere about this conflict... Also another thing worth mentioning is that the problem is greatly mitigated by the fact that you naturally tend to repeat a bit of the class name (e.g. `userX` for `Nelmio\Entity\User`, `groupX` for `Nelmio\Entity\Group`, etc.). But the problem is more likely to occur if you have the same class declared in different namespaces, e.g. `Nelmio\Entity\User` and `Nelmio\Bundle\FosUserBundle\Entity\User`).

@tshelburne WDYT?
