### ISSUE TITLE
Version 2.2 fails loading fixtures

### ISSUE THREAD

**Issue by overgapo** [nelmio/alice#421]
After recent update to 2.2 version i've got this:

>
[Hautelook\AliceBundle\Alice\DataFixtures\LoadingLimitException]                            
  Loading files limit of 50 reached. Could not load the following files 
/code/src/AppBundle/DataFixtures/ORM/changelogs.yml:                                        
   - Entity with ID @user-1 and class Mailer\AuthBundle\Entity\User not found

And the same for every fixtures file, where references are present.

Version 2.1.4 works fine. Has anyone faced this problem too?

**Comment by user-1** [comment]
My user id, but I don't know anything about it!

**Comment by theofidry** [comment]
@overgapo will look into it tonight

**Comment by theofidry** [comment]
I see that HautelookAliceBundle is indeed failing: https://travis-ci.org/hautelook/AliceBundle/jobs/143354359. I have an idea on what may cause this I may be able to fix that soon :)

**Comment by Soullivaneuh** [comment]
Can confirm the issue with hautelook/alice-bundle too:

```bash
$ ./docker-console make app_fixtures
./app/console --no-interaction --env=dev hautelook_alice:doctrine:fixtures:load --purge-with-truncate --bundle=AppBundle --manager=default
  > fixtures found:
      - /code/src/AppBundle/DataFixtures/ORM/incident.yml
      - /code/src/AppBundle/DataFixtures/ORM/changelog.yml
      - /code/src/AppBundle/DataFixtures/ORM/ticket.yml
      - /code/src/AppBundle/DataFixtures/ORM/payment_method.yml
      - /code/src/AppBundle/DataFixtures/ORM/puppet.yml
      - /code/src/AppBundle/DataFixtures/ORM/valid_tld.yml
      - /code/src/AppBundle/DataFixtures/ORM/package.yml
      - /code/src/AppBundle/DataFixtures/ORM/credit_card.yml
      - /code/src/AppBundle/DataFixtures/ORM/operation.yml
      - /code/src/AppBundle/DataFixtures/ORM/cron.yml
      - /code/src/AppBundle/DataFixtures/ORM/news.yml
      - /code/src/AppBundle/DataFixtures/ORM/email.yml
      - /code/src/AppBundle/DataFixtures/ORM/group.yml
      - /code/src/AppBundle/DataFixtures/ORM/server.yml
      - /code/src/AppBundle/DataFixtures/ORM/user_browser.yml
      - /code/src/AppBundle/DataFixtures/ORM/organization.yml
      - /code/src/AppBundle/DataFixtures/ORM/accounting.yml
      - /code/src/AppBundle/DataFixtures/ORM/ip_v4.yml
      - /code/src/AppBundle/DataFixtures/ORM/os.yml
      - /code/src/AppBundle/DataFixtures/ORM/purchase.yml
      - /code/src/AppBundle/DataFixtures/ORM/api_key.yml
      - /code/src/AppBundle/DataFixtures/ORM/invoice.yml
      - /code/src/AppBundle/DataFixtures/ORM/alert.yml
      - /code/src/AppBundle/DataFixtures/ORM/bank_account.yml
      - /code/src/AppBundle/DataFixtures/ORM/server_service.yml
      - /code/src/AppBundle/DataFixtures/ORM/service_ip.yml
      - /code/src/AppBundle/DataFixtures/ORM/domain.yml
      - /code/src/AppBundle/DataFixtures/ORM/country.yml
      - /code/src/AppBundle/DataFixtures/ORM/user.yml
      - /code/src/AppBundle/DataFixtures/ORM/backup_model.yml
      - /code/src/AppBundle/DataFixtures/ORM/product.yml
      - /code/src/AppBundle/DataFixtures/ORM/ip_group.yml
      - /code/src/AppBundle/DataFixtures/ORM/ip_v6.yml
  > purging database

                                                                                                                               
  [Hautelook\AliceBundle\Alice\DataFixtures\LoadingLimitException]                                                             
  Loading files limit of 5 reached. Could not load the following files:                                                        
  /code/src/AppBundle/DataFixtures/ORM/cron.yml:                                                                               
   - Instance mask "domain_*" did not match any existing instance, make sure the object is created after its references        
  /code/src/AppBundle/DataFixtures/ORM/domain.yml:                                                                             
   - Instance mask "server_nx102*" did not match any existing instance, make sure the object is created after its references   
  /code/src/AppBundle/DataFixtures/ORM/incident.yml:                                                                           
   - Instance mask "server_*" did not match any existing instance, make sure the object is created after its references        
  /code/src/AppBundle/DataFixtures/ORM/ip_v4.yml:                                                                              
   - Instance server_default is not defined                                                                                    
  /code/src/AppBundle/DataFixtures/ORM/operation.yml:                                                                          
   - Instance cron_98 is not defined                                                                                           
   - Instance cron_95 is not defined                                                                                           
   - Instance cron_6 is not defined                                                                                            
   - Instance cron_99 is not defined                                                                                           
   - Instance cron_49 is not defined                                                                                           
   - Instance cron_41 is not defined                                                                                           
  /code/src/AppBundle/DataFixtures/ORM/package.yml:                                                                            
   - Instance mask "server_*" did not match any existing instance, make sure the object is created after its references        
  /code/src/AppBundle/DataFixtures/ORM/puppet.yml:                                                                             
   - Entity with ID @puppet_package_www-servers_apache and class AppBundle\Entity\PuppetPackage not found                      
  /code/src/AppBundle/DataFixtures/ORM/server.yml:                                                                             
   - Instance os_gentoo is not defined                                                                                         
   - Instance mask "puppet_class_*" did not match any existing instance, make sure the object is created after its references  
  /code/src/AppBundle/DataFixtures/ORM/service_ip.yml:                                                                         
   - Instance mask "server_*" did not match any existing instance, make sure the object is created after its references        
                                                                                                                               

hautelook_alice:doctrine:fixtures:load [-b|--bundle [BUNDLE]] [-em|--manager MANAGER] [--append] [--shard SHARD] [--purge-with-truncate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

Makefile:55: recipe for target 'app_fixtures' failed
make: *** [app_fixtures] Error 1
```

@theofidry Can we have a clue of the reason of this bug? :-)

**Comment by theofidry** [comment]
Could you guys try with https://github.com/nelmio/alice/pull/423?

**Comment by Soullivaneuh** [comment]
@theofidry This is now what I have using `nelmio/alice` dev-master and https://github.com/hautelook/AliceBundle/pull/238: 

```bash
$ ./docker-console make app_fixtures
./app/console --no-interaction --env=dev hautelook_alice:doctrine:fixtures:load --purge-with-truncate --bundle=AppBundle --manager=default
  > fixtures found:
      - /code/src/AppBundle/DataFixtures/ORM/incident.yml
      - /code/src/AppBundle/DataFixtures/ORM/changelog.yml
      - /code/src/AppBundle/DataFixtures/ORM/ticket.yml
      - /code/src/AppBundle/DataFixtures/ORM/payment_method.yml
      - /code/src/AppBundle/DataFixtures/ORM/puppet.yml
      - /code/src/AppBundle/DataFixtures/ORM/valid_tld.yml
      - /code/src/AppBundle/DataFixtures/ORM/package.yml
      - /code/src/AppBundle/DataFixtures/ORM/credit_card.yml
      - /code/src/AppBundle/DataFixtures/ORM/operation.yml
      - /code/src/AppBundle/DataFixtures/ORM/cron.yml
      - /code/src/AppBundle/DataFixtures/ORM/news.yml
      - /code/src/AppBundle/DataFixtures/ORM/email.yml
      - /code/src/AppBundle/DataFixtures/ORM/group.yml
      - /code/src/AppBundle/DataFixtures/ORM/server.yml
      - /code/src/AppBundle/DataFixtures/ORM/user_browser.yml
      - /code/src/AppBundle/DataFixtures/ORM/organization.yml
      - /code/src/AppBundle/DataFixtures/ORM/accounting.yml
      - /code/src/AppBundle/DataFixtures/ORM/ip_v4.yml
      - /code/src/AppBundle/DataFixtures/ORM/os.yml
      - /code/src/AppBundle/DataFixtures/ORM/purchase.yml
      - /code/src/AppBundle/DataFixtures/ORM/api_key.yml
      - /code/src/AppBundle/DataFixtures/ORM/invoice.yml
      - /code/src/AppBundle/DataFixtures/ORM/alert.yml
      - /code/src/AppBundle/DataFixtures/ORM/bank_account.yml
      - /code/src/AppBundle/DataFixtures/ORM/server_service.yml
      - /code/src/AppBundle/DataFixtures/ORM/service_ip.yml
      - /code/src/AppBundle/DataFixtures/ORM/domain.yml
      - /code/src/AppBundle/DataFixtures/ORM/country.yml
      - /code/src/AppBundle/DataFixtures/ORM/user.yml
      - /code/src/AppBundle/DataFixtures/ORM/backup_model.yml
      - /code/src/AppBundle/DataFixtures/ORM/product.yml
      - /code/src/AppBundle/DataFixtures/ORM/ip_group.yml
      - /code/src/AppBundle/DataFixtures/ORM/ip_v6.yml
  > purging database

                                                                                                        
  [UnexpectedValueException]                                                                            
  Entity with ID @puppet_package_www-servers_apache and class AppBundle\Entity\PuppetPackage not found  
                                                                                                        

hautelook_alice:doctrine:fixtures:load [-b|--bundle [BUNDLE]] [-em|--manager MANAGER] [--append] [--shard SHARD] [--purge-with-truncate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

Makefile:55: recipe for target 'app_fixtures' failed
make: *** [app_fixtures] Error 1
```

**Comment by egeloen** [comment]
I also dig into this issue. Seems the reference are not resolved before being populated into the object resulting the typehint checker tries to resolve the entity by ID.

**Comment by theofidry** [comment]
Ah, https://github.com/hautelook/AliceBundle/pull/238 is letting this one pass so it doesn't even try to reload it.

**Comment by theofidry** [comment]
@egeloen do you have a scenario to reproduce it? At that point I'm just guessing what the issue is but have no idea if that's really the problem

**Comment by egeloen** [comment]
I will give a try to #423 and see if it fixes the issue or not and will come back here.

**Comment by theofidry** [comment]
Cheers

**Comment by egeloen** [comment]
@theofidry Unfortunatelly, #423 does not fix the issue. Here my simplified use case:

A user fixture (extending the FOS User):

```
Acme\AppBundle\Entity\User:
    user-admin:
        email: user-admin@example.com
        plainPassword: pass
        roles: [ROLE_ADMIN]
```

A OAuth client (extending the FOS OAuth Server):

```
Acme\AppBundle\Entity\Client:
    client:
        randomId: 123456789
        secret: 987654321
        allowedGrantTypes:
            - password
            - refresh_token
```

And an access token (extending the FOS OAuth Server):

```
Nexity\AppBundle\Entity\AccessToken:
    access-token:
        token: access-token
        expiresAt: <dateTimeBetween('+3600 seconds', '+3600 seconds')->getTimestamp()>
        client: "@client"
        user: "@user-admin"
```

When loading these fixtures via https://github.com/hautelook/AliceBundle I got:

```
  [Doctrine\Common\Persistence\Mapping\MappingException]                     
  Class 'Symfony\Component\Security\Core\User\UserInterface' does not exist
```

And the stack trace, if it can help:

```
Exception trace:                                                                                                                                                                                                                              
 () at /home/gelo/Workspace/project/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:96                                                                                             
 Doctrine\Common\Persistence\Mapping\MappingException::nonExistingClass() at /home/gelo/Workspace/project/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php:41               
 Doctrine\Common\Persistence\Mapping\RuntimeReflectionService->getParentClasses() at /home/gelo/Workspace/project/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:281  
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getParentClasses() at /home/gelo/Workspace/project/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:311                                                                                                                                                                                                                                            
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata() at /home/gelo/Workspace/project/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:78                             
 Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata() at /home/gelo/Workspace/project/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:216                         
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor() at /home/gelo/Workspace/project/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:379                                         
 Doctrine\ORM\EntityManager->find() at /home/gelo/Workspace/project/vendor/nelmio/alice/src/Nelmio/Alice/Persister/Doctrine.php:70                                                                                     
 Nelmio\Alice\Persister\Doctrine->find() at /home/gelo/Workspace/project/vendor/nelmio/alice/src/Nelmio/Alice/Util/TypeHintChecker.php:75                                                                              
 Nelmio\Alice\Util\TypeHintChecker->check() at /home/gelo/Workspace/project/vendor/nelmio/alice/src/Nelmio/Alice/Instances/Populator/Methods/Direct.php:43                                                             
 Nelmio\Alice\Instances\Populator\Methods\Direct->set() at /home/gelo/Workspace/project/vendor/nelmio/alice/src/Nelmio/Alice/Instances/Populator/Populator.php:96                                                      
 Nelmio\Alice\Instances\Populator\Populator->populate() at /home/gelo/Workspace/project/vendor/nelmio/alice/src/Nelmio/Alice/Fixtures/Loader.php:309                                                                   
 Nelmio\Alice\Fixtures\Loader->populateObjects() at /home/gelo/Workspace/project/vendor/nelmio/alice/src/Nelmio/Alice/Fixtures/Loader.php:147                                                                          
 Nelmio\Alice\Fixtures\Loader->load() at /home/gelo/Workspace/project/vendor/hautelook/alice-bundle/src/Alice/DataFixtures/Fixtures/Loader.php:50                                                                      
 Hautelook\AliceBundle\Alice\DataFixtures\Fixtures\Loader->load() at /home/gelo/Workspace/project/vendor/hautelook/alice-bundle/src/Alice/DataFixtures/Loader.php:193                                                  
 Hautelook\AliceBundle\Alice\DataFixtures\Loader->tryToLoadFiles() at /home/gelo/Workspace/project/vendor/hautelook/alice-bundle/src/Alice/DataFixtures/Loader.php:90                                                  
 Hautelook\AliceBundle\Alice\DataFixtures\Loader->load() at /home/gelo/Workspace/project/vendor/hautelook/alice-bundle/src/Doctrine/DataFixtures/Executor/ExecutorTrait.php:41                                         
 Hautelook\AliceBundle\Doctrine\DataFixtures\Executor\ORMExecutor->Hautelook\AliceBundle\Doctrine\DataFixtures\Executor\{closure}() at n/a:n/a                                                                                                
 call_user_func() at /home/gelo/Workspace/project/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:233                                                                                                           
 Doctrine\ORM\EntityManager->transactional() at /home/gelo/Workspace/project/vendor/hautelook/alice-bundle/src/Doctrine/DataFixtures/Executor/ExecutorTrait.php:45                                                     
 Hautelook\AliceBundle\Doctrine\DataFixtures\Executor\ORMExecutor->executeExecutor() at /home/gelo/Workspace/project/vendor/hautelook/alice-bundle/src/Doctrine/DataFixtures/Executor/ORMExecutor.php:72               
 Hautelook\AliceBundle\Doctrine\DataFixtures\Executor\ORMExecutor->execute() at /home/gelo/Workspace/project/vendor/hautelook/alice-bundle/src/Doctrine/DataFixtures/Executor/FixturesExecutor.php:44                  
 Hautelook\AliceBundle\Doctrine\DataFixtures\Executor\FixturesExecutor->execute() at /home/gelo/Workspace/project/app/cache/test/appTestDebugProjectContainer.php:13774                                                
 HautelookAliceBundleDoctrineDataFixturesExecutorFixturesExecutor_000000004520b2e400000000565008ef9f8b77c73e45472b7cd13278c0bc076a->execute() at /home/gelo/Workspace/project/vendor/hautelook/alice-bundle/src/Doctrine/Command/LoadDataFixturesCommand.php:223                                                                                                                                                                                                     
 Hautelook\AliceBundle\Doctrine\Command\LoadDataFixturesCommand->execute() at /home/gelo/Workspace/project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /home/gelo/Workspace/project/app/cache/test/appTestDebugProjectContainer.php:14784
 HautelookAliceBundleDoctrineCommandLoadDataFixturesCommand_000000004520b42c00000000565008ef9f8b77c73e45472b7cd13278c0bc076a->run() at /home/gelo/Workspace/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:860
 Symfony\Component\Console\Application->doRunCommand() at /home/gelo/Workspace/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /home/gelo/Workspace/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/gelo/Workspace/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:123
 Symfony\Component\Console\Application->run() at /home/gelo/Workspace/project/app/console:22
```

**Comment by theofidry** [comment]
I'm afraid you are getting very different errors. Just to confirm, you have both using AliceBundle with `nelmio/alice:2.x-dev` right?

@Soullivaneuh could you please retry without hautelook/AliceBundle#238?

@egeloen I see nothing wrong with your fixtures. It's more like a mapping error of doctrine than alice fault. Maybe what is happening is that you have a `UserInterface` somewhere which alice tries to find via the doctrine manager, but because the interface is not mapped throws an error.

**Comment by egeloen** [comment]
@theofidry If I use alice 2.1.4 everything is working fine so IMO, it's not a doctrine mapping issue but an alice one for sure.

**Comment by theofidry** [comment]
@egeloen the problem is that it's clearly not from those fixtures only, but rather about the entities and the doctrine mapping, and that I can't reproduce it either on alice or AliceBundle. Alice doctrine bridge did change in 2.2.0 to support embeddables, so it's not that far fetch to suspect it or the doctrine configuration.

**Comment by theofidry** [comment]
[2.2.1](https://github.com/nelmio/alice/releases/tag/2.2.1) has been released. I'm aware it's unlikely to solve the problem for all of you, but it still fixes a major BC which solves the problem for most users.

Reviewing the changes of the 2.2.0, the bug you are encountering now (with the 2.2.1), are likely related to Doctrine, to add the support of embeddables. The other changes are mostly adding tests (~80% of the changes) and small bugfixes which have been well covered. **[There is also a couple of small "BC breaks"](https://github.com/nelmio/alice/blob/2.2.1/CHANGELOG.md#bugfixes-1)**, which have been introduced because they 1. were clearly bugs 2. generating very weird results.

If you still encounter an issue, please double check first that your fixtures are ok. Then try to provide the following informations:

- identify the small set of fixtures causing this issue and provide it if possible
- provide your entities (the important part are if your properties are public or the typehint of your setters)
- your stack trace (HautelookAliceBundle users)
- your doctrine configuration

Note for HautelookAliceBundle users: do **NOT** use https://github.com/hautelook/AliceBundle/pull/238. It's an optimization but fear I'm missing a case which will cause to throw an exception where it should instead continue to try to load files.

The ideal obviously would be to have access to a repo where the issue occur so that I can freely debug this issue.

**Comment by Soullivaneuh** [comment]
@theofidry OK I found the problem. This is the hypen (`-`).

This is the concerned fixture file:

```yaml
AppBundle\Entity\PuppetFlagGroup:
    puppet_flag_group_use:
        name: USE
    puppet_flag_group_kernel:
        name: KERNEL
    puppet_flag_group_php_targets:
        name: PHP_TARGETS

AppBundle\Entity\PuppetFlag:
    puppet_flag_use_api:
        name: api
        group: '@puppet_flag_group_use'
    puppet_flag_use_ncurses:
        name: ncurses
        group: '@puppet_flag_group_use'
    puppet_flag_use_debug:
        name: debug
        group: '@puppet_flag_group_use'
    puppet_flag_kernel_linux:
        name: linux
        group: '@puppet_flag_group_kernel'
    puppet_flag_kernel_darwin:
        name: darwin
        group: '@puppet_flag_group_kernel'
    puppet_flag_kernel_freebsd:
        name: freebsd
        group: '@puppet_flag_group_kernel'
    puppet_flag_php_targets_php54:
        name: php54
        group: '@puppet_flag_group_php_targets'
    puppet_flag_php_targets_php55:
        name: php55
        group: '@puppet_flag_group_php_targets'
    puppet_flag_php_targets_php56:
        name: php56
        group: '@puppet_flag_group_php_targets'
    puppet_flag_php_targets_php70:
        name: php70
        group: '@puppet_flag_group_php_targets'

# TODO: Use correct id with `/` when issue will be solved: https://github.com/nelmio/alice/issues/284
AppBundle\Entity\PuppetPackage:
    puppet_package_app-admin_puppet:
        name: app-admin/puppet
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_dev-db_mysql:
        name: dev-db/mysql
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_dev-db_phpmyadmin:
        name: dev-db/phpmyadmin
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_dev-db/postgresql_server:
        name: dev-db/postgresql-server
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_dev-lang_php:
        name: dev-lang/php
        availableVersions: [5.3.0, 5.4.0, 5.5.5, 5.6.38]
        defaultVersion: 5.6.38
        availableFlags:
            - '@puppet_flag_php_targets_php54'
            - '@puppet_flag_php_targets_php55'
            - '@puppet_flag_php_targets_php56'
            - '@puppet_flag_php_targets_php70'
            - '@puppet_flag_use_debug'
        defaultEnabledFlags:
            - '@puppet_flag_php_targets_php56'
        defaultDisabledFlags:
            - '@puppet_flag_php_targets_php54'
            - '@puppet_flag_use_debug'
    puppet_package_kernel:
        name: kernel
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
        availableFlags:
            - '@puppet_flag_kernel_linux'
            - '@puppet_flag_kernel_darwin'
            - '@puppet_flag_kernel_freebsd'
            - '@puppet_flag_use_debug'
        defaultEnabledFlags:
            - '@puppet_flag_kernel_linux'
    puppet_package_mail-filter_spamassassin:
        name: mail-filter/spamassassin
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_mail-mta_postfix:
        name: mail-mta/postfix
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_net-dns_bind:
        name: net-dns/bind
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_net-misc_openssh:
        name: net-misc/openssh
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_sys-apps_baselayout:
        name: sys-apps/baselayout
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_sys-apps_openrc:
        name: sys-apps/openrc
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_sys-apps_portage:
        name: sys-apps/portage
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_sys-boot_grub:
        name: sys-boot/grub
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_www-servers_apache:
        name: www-servers/apache
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0
    puppet_package_www-servers_nginx:
        name: www-servers/nginx
        availableVersions: [1.0.0, 1.0.1, 2.0.0]
        defaultVersion: 2.0.0

AppBundle\Entity\PuppetClass:
    puppet_class_basepack:
        name: basepack
        base: true
    puppet_class_apache:
        name: apache
        packages:
            - '@puppet_package_www-servers_apache'
    puppet_class_php:
        name: php
        packages:
            - '@puppet_package_dev-lang_php'
    puppet_class_mysql:
        name: mysql
        packages:
            - '@puppet_package_dev-db_mysql'
            - '@puppet_package_dev-db_phpmyadmin'

AppBundle\Entity\PuppetTemplate:
    puppet_template_lamp:
        name: LAMP
        classes:
            - '@puppet_class_apache'
            - '@puppet_class_php'
            - '@puppet_class_mysql'
```

According to #355, hyphens are not allowed anymore.

I see many problems with this one:

1. Hyphens should be allowed IMHO, it produces valid fixture IDs
2. The error is not enough explicit. It says "Entity with ID @puppet_package_www-servers_apache" is not found. It should say before that the ID is not valid
3. This PR is targeting a minor branch. Invalid IDs should produce a deprecation error and should still working, not the reverse. Or maybe this was not wanted?

Anyway, we finaly found why this fail! :tada: 

If think `1.` (restore hyphens) should be resolve ASAP because this will solve 99% of user issue. Then, the deprecation way would ensure not error for everyone. :+1: 

Regards.
