### ISSUE TITLE
Support associative arrays when an addXXXX method exists

### ISSUE THREAD

**Issue by simshaun** [nelmio/alice#436]
I'm trying to hard-code some data in a couple fixtures, and it doesn't seem like associative arrays are supported when the object has an `add{XXXXX}` method.

``` yaml
AppBundle\Entity\Bucket:
    bucket_foo:
        name: Foo
        provider: foo
        providerData:
            apiKey: '123'
    bucket_bar:
        name: Bar
        provider: bar
        providerData:
            apiKey: '456'
```

My entity has a convenience method `addProviderData($key, $val)` as well as `setProviderData(array $data)`.

Alice is calling `->addProviderData('123')`, so I think it's dropping the array keys for some reason.

When I remove the `addProviderData` method, Alice calls `->setProviderData(['apiKey' => '123'])` as expected.
