### ISSUE TITLE
Random relationship NULL values

### ISSUE THREAD

**Issue by simshaun** [nelmio/alice#488]
I've got two entities, `Theme` and `StockHeader`. I'm trying to relate a random stock header to each theme. The problem is that when fixtures are loaded, some themes are getting a `NULL` value for stock header. I'd like all themes to have a stock header, so no NULL values.

I've tried changing the DB schema so that the stock header ID column isn't nullable, but then I just get an integrity constraint violation when I try to load fixtures.

```yaml
Entity\StockHeader:
    stock-header_1:
        headerImage: 'header_fpo_01.jpg'
    stock-header_2:
        headerImage: 'header_fpo_02.jpg'

Entity\Theme:
    theme_{1..20}:
        stockHeader: '@stock-header_*'
```
