### ISSUE TITLE
Cannot pass entity instance to a method

### ISSUE THREAD

**Issue by danjamin** [nelmio/alice#50]
I have an entity that I want to pass to a method on another entity (defined after the first entity).

**fixtures.yml**

``` YAML
Example\AcmeBundle\Entity\Foo:
    fooInstance:
        id: 0
        name: Bar

Example\AcmeBundle\Entity\Bar:
    barInstance:
        fooName: <myFormatter(@fooInstance)>
```

The provided example does not work, as I get a string in myFormatter(), rather than the expected Foo instance.  

**Possible work around in _most_ cases**

``` YAML
Example\AcmeBundle\Entity\Foo:
    fooInstance:
        id: 0
        name: Bar

Example\AcmeBundle\Entity\Bar:
    barInstance:
        foo: @fooInstance
        fooName: <myFormatter($foo)>
```

However, in my particular case, I don't have any property (like foo:) to use as a variable in the method call.  I need to be able to pass the @fooInstance to the method.

This does not currently appear to be supported.
