### ISSUE TITLE
How to set the same value for more than one field?

### ISSUE THREAD

**Issue by tomaszpolska** [nelmio/alice#517]
```yaml
AppBundle\Entity\UserAccount:
    UserAccount_{1..5}:
        emailConfirmed: '80%? 1 : 0'
        enabled: ????
```

How to set _enabled_ field to hold the same value as _emailConfirmed_ field. In other words - how to reference other field value in the same entity?

**Comment by theofidry** [comment]
[According to the doc](https://github.com/nelmio/alice/blob/master/doc/fixtures-refactoring.md#variables):

```yaml
AppBundle\Entity\UserAccount:
    UserAccount_{1..5}:
        emailConfirmed: '80%? 1 : 0'
        enabled: $emailConfirmed
# or
        enabled: @self->emailConfirmed
```

In the case of the second example, the difference is that it will try to retrieve the value via getter so the actual value might be different if you have a setter that changes your data.
