### ISSUE TITLE
Unable to pass references to provider when reference name contains a dash

### ISSUE THREAD

**Issue by simshaun** [nelmio/alice#520]
I created a new provider that turns an array into a Doctrine ArrayCollection.

While the dash in the reference name is fine if I'm simply setting a plain array on a property, it causes problems when Alice tries to pass a reference to a data provider.

```yaml
Entity\AdSpot:
    ad-spot_foo:
        name: 'Foo'
    ad-spot_bar:
        name: 'Bar'

Entity\Ad:
    ad_1:
        name: 'FPO 1'
        spots: <ArrayCollection([@ad-spot_foo, @ad-spot_bar])>
```

`Instances\Processor\Methods\Faker::replacePlaceholder` is converting that the arguments in to:

```php
[$this->objects->find('ad', NULL)-spot_foo, $this->objects->find('ad', NULL)-spot_bar]
```

It looks like the `$args` regex in that method just needs to have a dash added to `reference` capture group.
