### ISSUE TITLE
Functions for loading resources/files

### ISSUE THREAD

**Issue by kingcrunch** [nelmio/alice#53]
It would be useful to have additional functions to load strings and resources/streams from files. In a single example

```
Nelmio\Entity\Blog:
    post1:
        title: My title
        content: <file(blog/post1.html)>
        title_image: <resource(blog(post1.jpg)>
```

`file()` should return the content of the file as string (like `file_get_contents()`) and `resource()` as stream (like `fopen()`). Ideally both paths should get resolved relative to the yaml-file.
