### ISSUE TITLE
Better example of how current() works in documentation?

### ISSUE THREAD

**Issue by clemf** [nelmio/alice#546]
I've been having a lot of trouble with how current() works, and am confused by the example in the docs:

```
Nelmio\Entity\User:
    # ...

Nelmio\Entity\Group:
    group{1..10}:
        owner: '@user<current()>'
```

Is User supposed to be `user{1..10}`? I think having that part of the example would make it less confusing.

**Comment by theofidry** [comment]
`@something` is a reference to a fixture with the ID `something`. However this `something` can be dynamic, i.e. if `<current()>` returns `10` then `@user<current()>` results in `@user10`. Also there's the `*` operator to apply a mask, e.g. `@user*` will pick a random fixture with an ID matching this mask.

As a rule `<current()>` works in "collections":

```yaml
# Range
Nelmio\Entity\Group:
    group{1..10}:
        owner: '@user<current()>' # will result in `@user1` for `@group1`, `@user2` for `@group2` etc.

# List
Nelmio\Entity\Group:
    group{foo, bar}:
        owner: '@user<current()>' # will result in `@userfoo` for `@groupfoo`, `@userbar` for `@groupbar` etc.
```

Does that clear up your confusion?
