### ISSUE TITLE
Doctrine ReferenceOne and Alice

### ISSUE THREAD

**Issue by excentrik** [nelmio/alice#577]
First a quick description of my use case.

I have a Review class that follows the schema:
```yaml
ReviewBundle\Document\Review:
    collection: ReviewBundle_Review
    fields:
        id:
          type: id
          id: true

    referenceOne:
        # The id of the user that created this review
        authorId:
            targetDocument: UserBundle\Document\User
            storeAs: id
```
And I create fixtures with:
```yaml
UserBundle\Document\User:
    user_dev_test_user:
        id: <mongoId()>
        username: <uniqueUsername()>

ReviewBundle\Document\Review:
    review:
        id: <mongoId()>
        authorId: @user_dev_test_user->id
```

The loading is done with a `DataFaker` class:
```php
    $options = ['providers' => [new DataFaker()]];
    $objects = Fixtures::load($filePaths, $this->dm, $options);
```
```php
class DataFaker
{
    public function mongoId($str = null)
    {
        return new \MongoId($str);
    }
    public function uniqueUsername()
    {
        $id = new \MongoId();

        return 'datafixtures_test_' . (string)$id;
    }
```

Now, the issue is that when trying to load the fixtures, I get a
`The class 'MongoId' was not found in the chain configured namespaces UserBundle\Document, ReviewBundle\Document``

But if I replace the `referenceOne` part with:
```yaml
        authorId:
            type: id
            targetDocument: UserBundle\Document\User
```
everything seems to work fine, except I lose doctrine's reference support.

Any ideas on what is going on or how to solve this would be income. If you need more information, please let me know.
