### ISSUE TITLE
(Suggestion) Nested ranges

### ISSUE THREAD

**Issue by appeltaert** [nelmio/alice#579]
I'm currently falling back on PHP alot because of the amount of nested looping i need to do to keep fixtures as dry as possible.

```php
foreach($contentTypes as $type) {
    $return['Content']['content_'.$type.'{1..5}'] = [
        // ...
        'ctype' => '@ctype_' . $type
    ];
}
```

In YML this currently means:

```yml
Content:
    content_image_{1..5}:
        ctype: '@ctype_<current()>'
    content_video_{1..5}:
        ctype: '@ctype_<current()>'
    [...]
```

Could possibly be written as:

```yml
Content:
    content_{image, video}_{1..5}:
        ctype: '@ctype_<it|current|arg(1)>'
```
