### ISSUE TITLE
Dynamic faker parameter.

### ISSUE THREAD

**Issue by robotzero** [nelmio/alice#581]
In Alice 2.x branch I could do the following:

``` yaml
parameters:
    createdAt: <dateTimeBetween("-200 days", "now")>

MyBundle\Model\Character:
    character (template):
        __construct: ['<{createdAt}>']
```

Branch 3.x does not correctly resolve dynamic parameter and resolves it to string. Is this a missing feature or are there plans to implement this into 3.x branch?

**Comment by theofidry** [comment]
indeed functions can't be called in parameters for now, and I'm not sure if this should be ported or not to be honest, it does complexify a lot the parameters resolution as it's hard to deal with successive function calls `<f()> <g()>` and nested ones `<f(<g()>, <z()>)>`

**Comment by theofidry** [comment]
An easy workaround would be to have a "dummy" object:

```yaml
stdClass:
  parameters:
    createdAt: <dateTimeBetween("-200 days", "now")>

MyBundle\Model\Character:
    character (template):
        __construct: ['@parameters->createdAt']
```
