### ISSUE TITLE
Support constructor named properties

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#594]
For:

``` yaml
User:
    user0:
        __construct:
            - bob
            - Bob
            - '1980-10-10'
            - bob@example.org
            - 42
```

It would be better if we could do:

``` yaml
User:
    user0:
        __construct:
            username: bob
            fullname: Bob
            dateOfBirth:  '1980-10-10'
            email: bob@example.org
            favoriteNumber: 42
```

Besides being easier to understand (IMO), it also gives the possibility to re-order the properties. That said this does rely on the name of PHP variable, i.e. the constructor must look like this:

``` php
class User
{
  public function __construct($username, $fullname, $dateOfBirth, $email, $favoriteNumber)
  {
    //...
  }
}
```

And changing a variable name _can_ break the fixture code.

@tshelburne WDYT?
