### ISSUE TITLE
Casting values

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#597]
Besides escaping as mentioned in #569, I believe if would be useful as well to have a cast function:

```yaml
Dummy:
  dummy:
    isTrue: '<cast(<something()>, bool)>'
```

This is even more true as we are in PHP7 and with strict types having the wrong type may end to a failure.

@tshelburne any opinion on this?
