### ISSUE TITLE
Support immutable functions

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#629]
In https://github.com/nelmio/alice/issues/313#issuecomment-223916566, there was the question of supporting `with*` methods. After writing down #388 and the first beta, I would say that this can be added by:

- Either keeping this as it is and add a `configurator` flag to the method to say it returns the modified object
- Add a configuration step as in the spec. This does require to change a couple of things and introduce API breaks, so it would need to be done *before* the stable release.

@tshelburne @ogizanagi WDYT?

**Comment by tshelburne** [comment]
I'm not completely clear on the intention, even after reading the comment + issue from before. Can you paste an example + intended result?

**Comment by theofidry** [comment]
Sure. The idea is that you may have methods (be it from another service, a static method, or a method and the instance) which returns the result, for example:

```php
final class Dummy
{
    public function __construct($param)
    {
        //...
    }

    public function withParam($param): self
    {
        $clone = clone $this;
        $clone->param = $param;

        return $clone;
    }
}
```

```yaml
Dummy:
     dummy:
         __construct: ['foo']
         __calls:
             - (configurator) withParam: ['bar']

# Alternative to the configurator syntax:

Dummy:
     dummy:
         __construct: ['foo']
         __configurator:
             - withParam: ['bar']

```

If you take the example above, assuming `__calls` works (I still have to implement it), the fixture would be equivalent to `new Dummy('foo')`, because `Dummy#withParam()` doesn't modify the fixture itself, but returns the modified instance.

I'm aware this is a really dumb example, but there is a few use cases when using immutable objects and it was before something you could achieve with `__setter` which gave you all the flexibility you needed, although much more manual.

**Comment by theofidry** [comment]
@tshelburne I added the explanation in a rush, if it's not clear enough let me know I'll rephrase it when I have some time

**Comment by tshelburne** [comment]
@theofidry So would the Alice part remove the need for actually adding the `withParam` method to the class? If not, how is this different from just allowing method calls?

**Comment by ogizanagi** [comment]
@theofidry : I fear I'm unable to help from the implementation POV, because I know too few about Alice internals and didn't had time nor really the need to dig into it until now :/
But I definitively approve this feature request.

> If not, how is this different from just allowing method calls?

Because it'll return a new instance each time, so each subsequent call should take the new instance instead of the original one.

```yml
Dummy:
     dummy:
         __construct: ['foo']
         __configurator:
             - withParam: ['bar'] # returns a new instance based on the one returned by the previous construct call
             - withOtherParam: ['baz'] # returns a new instance based on previous one with "bar" param
             # ...
```
