### ISSUE TITLE
Using same entity multiple times

### ISSUE THREAD

**Issue by nlemoine** [nelmio/alice#646]
When creating fixtures, I can't use multiple times the same entity. 

```yaml
Nelmio\Entity\User:
    user{1..10}:
        username: '<username()>'
        fullname: '<firstName()> <lastName()>'
        birthDate: '<date()>'
        email: '<email()>'
        favoriteNumber: '50%? <numberBetween(1, 200)>'

Nelmio\Entity\User:
    user_test:
        username: '<username()>'
        fullname: '<firstName()> <lastName()>'
        birthDate: '<date()>'
        email: '<email()>'
        favoriteNumber: '50%? <numberBetween(1, 200)>'
```

Only the last identical entity can be found in the objects set. Is this the expected behaviour?

**Comment by theofidry** [comment]
Yes, it's not specific to alice but rather YAML, see http://yaml-online-parser.appspot.com/?url=http%3A%2F%2F. To do what you want:

```yaml
Nelmio\Entity\User:
    user{1..10}:
        username: '<username()>'
        fullname: '<firstName()> <lastName()>'
        birthDate: '<date()>'
        email: '<email()>'
        favoriteNumber: '50%? <numberBetween(1, 200)>'

    user_test:
        username: '<username()>'
        fullname: '<firstName()> <lastName()>'
        birthDate: '<date()>'
        email: '<email()>'
        favoriteNumber: '50%? <numberBetween(1, 200)>'
```
