### ISSUE TITLE
How to user multiple times relation?

### ISSUE THREAD

**Issue by cierzniak** [nelmio/alice#648]
I have system to organize events and for testing purposes i need to make fixtures with few inheritances of one entity. How to make it possible to eg. get one enttiy and use it multiple times in second?

````yml
AppBundle\Entity\Venue:
  venue_{0..9}:
    name (unique): '<text(30)>'
    address: '<address()>'
    description: '<sentence()>'
    maxSpace: '<numberBetween(400, 600)>'
AppBundle\Entity\Event:
  event_{0..499}:
    name (unique): '<text(80)>'
    description: '<sentence()>'
    image: '<imgName()>'
    totalTickets: '<numberBetween(150, @venue*->maxSpace)>'
    created: '<dateTimeBetween("-150 days", "now")>'
    dateOfEvent: '<dateTimeBetween($created, "+200 days")>'
    author: '@user*'
    venue: '@venue*'
````

When I check it by SQL:
````sql
SELECT a.*, b.*
FROM event a
JOIN venue b ON b.id = a.venue_id
WHERE b.max_space < a.total_tickets
````
I have eg. 40 records shown (so max tickets is more than max space in venue).

**Comment by cierzniak** [comment]
Or how to chec condition? If @user->isActive() assign him to this fixture

**Comment by theofidry** [comment]
I think you can do it by using variable references:

```yaml
AppBundle\Entity\Venue:
  venue_{0..9}:
    name (unique): '<text(30)>'
    address: '<address()>'
    description: '<sentence()>'
    maxSpace: '<numberBetween(400, 600)>'

AppBundle\Entity\Event:
  event_{0..499}:
    venue: '@venue*'
    # ...
    totalTickets: '<numberBetween(150, $venue*->maxSpace)>'
```

This should work, but I may not have accounted for that in the Expression Language... But if it doesn't, it something that should be added

**Comment by cierzniak** [comment]
````yml
    venue: '@venue*'
    ...
    totalTickets: '<numberBetween(150, $venue->maxSpace)>'
````
Gives error `Cannot access private property AppBundle\Entity\Venue::$maxSpace`

````yml
    venue: '@venue*'
    ...
    totalTickets: '<numberBetween(150, $venue*->maxSpace)>'
````
Gives error `Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) `

So still nothing :(
