### ISSUE TITLE
How to add information of same existing Entity

### ISSUE THREAD

**Issue by AmsTaFFix** [nelmio/alice#65]
Sorry for my english.

I have table, two columns which have ids of same Entity (not FK, only id)

Example.

```
Billing\Bundle\MiscBundle\Entity\TZone:
  tzone1:
    id: 0
    defZone: -1
    zoneReport: -1
    zoneType: 0
  tzone{2..6}:
    zoneName: <city()>
    id (unique): <current()>
    defZone: @tzone<numberBetween(1,$id-1)>->id
    zoneReport: @tzone<numberBetween(1,$id-1)>->id
```

But, if i want to make id like...

```
...
id (unique): <numberBetween(1,10000000)>
...
```

i will have problems with it. How I can solve this problem?
