### ISSUE TITLE
Make parameters accessible in identity

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#652]
In identity, I think it would be great if parameters could be accessed like for current:

```yaml
parameters:
    foo: 'bar'

stdClass:
    dummy:
        foz: <($foo)> # will be evaluated as `'bar'`
```
