### ISSUE TITLE
Smarter random value resolving

### ISSUE THREAD

**Issue by theofidry** [nelmio/alice#672]
As stated in https://github.com/hautelook/AliceBundle/issues/313, if you have:

```yaml
# app/Resources/fixtures/orm/product.yml
AppBundle\Entity\Product:
    product_{1..10}:
        name: <name()>
        dummy: '@dummy*'
```

```yaml
# app/Resources/fixtures/orm/dummy.yml
AppBundle\Entity\Dummy:
    dummy_{1..10}:
        name: <name()>
```

```yaml
# app/Resources/fixtures/orm/dummy_configuration.yml
AppBundle\Entity\DummyConfiguration:
    dummy_configuration_{1..10}:
        name: <name()>
```

`dummy*` may be resolved with the wrong value. Maybe there is a smarter way to do it, by either passing the typehint of the result wanted when resolving the value, retrying to resolve the value if does not match or calculating that upfront...

It is certainly doable, what I'm less sure of is what would be the performance cost of such magic would have and if it can be acceptable.

/cc Kwadz
