### ISSUE TITLE
 Could not find the fixture 'MyFixture'

### ISSUE THREAD

**Issue by nietzcheson** [nelmio/alice#678]
I'm used ^3.0@beta.

I have:
Customer:
```yml
AppBundle\Entity\Customer:
    customer:
        name: The Customer
```
Contact:
```yml

AppBundle\Entity\Contact:
    contact:
        name: The Contact
        telephone: 33333333
```
And CustomerContact:
```yml
AppBundle\Entity\CustomerContact:
    customer_contact:
        customer: "@customer"
        contact: "@contact"
```
And the issue it's: **Could not find the fixture "contact"**
