### ISSUE TITLE
Question for multi tenant example

### ISSUE THREAD

**Issue by cve** [nelmio/alice#704]
Hi,

First of all big thanks for develop such great library.

Suppose that we have 3 objects, a Product that has many Category and User entity that has many Product and Category.

Each User should have its own Products and Categories, so we should have user_id in Product and Category entities and each Product should have category_id for relation to Product. 

Let's say I want to fill the database with 100 Products, 6 Categories and 2 Users where each user has 50 Products and 3 Categories.

What I have now:
#### user.yml
````yml
AppBundle\Entity\User:
  user1:
    username: user
    email: user@example.com
    plainPassword: user
    enabled: true
  user2:
    username: user2
    email: user2@example.com
    plainPassword: user2
    enabled: true
````
#### product.yml
````yml
AppBundle\Entity\Product:
  product_{1..100}:
    name (unique): <name()>
    category: '@category*'
    user: '@user*'
````
#### category.yml
````yml
AppBundle\Entity\Category:
  category_{1..6}:
    name (unique): <name()>
    user: '@user*'
````

How to achieve that with .yml fixtures?
