### ISSUE TITLE
property of template not available in class as variable

### ISSUE THREAD

**Issue by thewholelifetolearn** [nelmio/alice#725]
First of all, for the context:
- Alice in version 2.3.1
- PHP 7.1.0
- Symfony 2.8.16

I'm want to create fixtures for my project by using [templates](https://github.com/nelmio/alice/blob/2.x/doc/fixtures-refactoring.md#fixture-inheritance) and [variables](https://github.com/nelmio/alice/blob/2.x/doc/fixtures-refactoring.md#variables).

As in the example for the variables, I have a date of submission that should be before a date of validation. The variable for the submission date is in the template and I want to use it in a class for the validation date. When I load the fixture, an exception is raised:
```
[Symfony\Component\Debug\Exception\ContextErrorException]
  Notice: Undefined variable: submitDate
```

For a better understanding, here a code example of what I wish:
```yaml
AppBundle\Entity\Request:
# Template for a request
  t_request (template):
    submitDate: <dateTimeBetween('-1 year', 'now')>
    submitter: '@user-ems*'

# Request taken in charge
  request-{101..110} (extends t_request):
    validateUser: '@user-esm*'
    validateDate: <dateTimeBetween($submitDate, '+1 month')>
```

And here, what I must do to get it work:
```yaml
AppBundle\Entity\Request:
# Template for a request
  t_request (template):
    submitDate: <dateTimeBetween('-1 year', 'now')>
    submitter: '@user-ems*'

# Request taken in charge
  request-{101..110} (extends t_request):
    submitDate: <dateTimeBetween('-1 year', 'now')> # redeclare the variable
    validateUser: '@user-esm*'
    validateDate: <dateTimeBetween($submitDate, '+1 month')>
```

I don't know if it is a bug or an enhancement but it would be great if it would be possible to use a property of a template as a variable in a class or an other template. That would avoid incoherence/bug if the property is changed in the template but forgotten in the class.
