### ISSUE TITLE
Using a parameter in the fixture range

### ISSUE THREAD

**Issue by jeremy-smith-maco** [nelmio/alice#730]
Is it possible to use a parameter in the fixture range in Alice 2.x?

Example:
```yaml
parameters:
  total: 150

User{1..<{total}>}:
  userId: '@UserId<current()>'
```

I have been trying several different methods to get this working but no luck. If it does not currently work, can I request it as a feature for 3.x? Also, the parameter, <{total}>, is dynamic so it will change all the time. I just set it to 150 for the example but you get the gist of it.

**Comment by theofidry** [comment]
This is not supported in neither 2.x and 3.x, and I'm not sure it should. But if people really find it a must then let's let them show their interest here.

**Comment by jeremy-smith-maco** [comment]
Darn. That's okay. I'll just have to have a static limit for the amount of users that can be created instead of being dynamic. Something like:

```yaml
parameters:
   usersToPersist: '@User{1..<{total}>}'
   total: [some user-specified number between 1 and 500]

User{1..500}:
    userId: '@UserId<current()>'
```
