### ISSUE TITLE
How to store the password encoded in symfony2 for fosuserbundle? 

### ISSUE THREAD

**Issue by Ziiweb** [nelmio/alice#74]
Hi,

how to store the password encoded in symfony2 for fosuserbundle? 

```
Sermovi\Bundle\UserBundle\Entity\User:
    user2:
        username: tirengarfio
        password: *******
        email: tirengarfio@gmail.com
```
