### ISSUE TITLE
Set field fetched from database

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [nelmio/alice#742]
I would like to set a field with an already existing field from the database imported with a dump for example.

I have tried with this for example like the issue #598 :

`<entity_reference("Some\Class\Name", 100)>`

But returns me an error that doesn't exist entity_reference

Does exist a way to fetch an entity from the database that already exists?

**Comment by theofidry** [comment]
That's because you need to write your own `<entity_reference()>`, it's a custom faker method cf. https://github.com/nelmio/alice/blob/master/doc/customizing-data-generation.md#custom-faker-data-providers

**Comment by AlessandroMinoccheri** [comment]
Thanks for the help! I will try It

**Comment by videni** [comment]
@AlessandroMinoccheri , did you create the entity_reference successfully?  I did as the example show , but it doesn't work.
```
class EntityReferenceProvider extends BaseProvider
{
    private $entityManger;

    public function entityReference(string $class, $name)
    {
        if (!class_exists($class, true)) {
            reuturn;
        }
        $repository = $this->entityManager->getRepository($class);

        return  $repository->findOne(['name'=>$name]);
    }

    public function setEntityManager(ObjectManager $entityManager)
    {
        $this->entityManager = $entityManager;
    }
}
```

```
services:
    Pintushi\Bundle\CoreBundle\Faker\Provider\EntityReferenceProvider:
        calls:
            - [ setEntityManager, [ '@doctrine.orm.entity_manager' ] ]
        tags:
            - { name: 'nelmio_alice.faker.provider' }

```

```
App\Bundle\CarBundle\Entity\CarBrand:
    car_brand{11..20}:
        name: "<name()>"
        image: "<name()>"
        organization: '<entityReference("App\Bundle\OrganizationBundle\Entity\Organization", "Second"))>'
```


it give me this error

> InvalidArgumentException: Unknown formatter "entityReference"


do you know why?
