### ISSUE TITLE
DateTime manipulation 

### ISSUE THREAD

**Issue by BrownSim** [nelmio/alice#745]
Hello, I have a question, I try to manipulate date and I do not think it is possible 

That can be usefull : 
```
MyEntity:
       startAt: '<(new DateTime("2017-06-02 12:00:00"))'
       endAt: '$startAt + 2 hours'
```

Thanks

**Comment by theofidry** [comment]
I understand that it looks nice on paper, but I see big issues regarding the DSL syntax which I don't think is worth.

You can always have a custom Faker provider to do:

```yml
MyEntity:
  dummy:
    startAt: '<(new DateTime("2017-06-02 12:00:00"))>'
    endAt: '<manipulateTime($startAt, "+ 2 hours")>'
```
