### ISSUE TITLE
Foreign key constraint on many to many relation

### ISSUE THREAD

**Issue by maches** [nelmio/alice#746]
Hi,
I have an error when I try to add elements to many-to-many relation.
There are fixtures:
```yaml
AppBundle\Entity\Subject:
    subjectTemp (template):
        createdAt: <dateTimeBetween("-5 days", "now")>
        updatedAt: <dateTimeBetween($createdAt, "now")>
    subject{1..9} (extends subjectTemp):
        name: '<subject_name(<current()>)>'

AppBundle\Entity\Activity:
    activityTemp (template):
        createdAt: <dateTimeBetween("-5 days", "now")>
        updatedAt: <dateTimeBetween($createdAt, "now")>
        executionControl: '85%? @control1 : @control2'
        shortDescription: '<realText(150)>'
        fullDescription: '<realText(1500)>'
        isImportant: '10%? 1 : 0'
        isOnline: '35%? 1 : 0'
        region: '@region_*'
        activityType: '@type*'
        subjects: '3x @subject*'
    activity{1..15} (extends activityTemp):
        name: 'Activity <current()>'
```
And error:
 ```
Integrity constraint violation: 1062 Duplicate entry '251-230' for key 'PRIMARY' 
```
I tried to solve this problem with (unique), but got another error. It's about 150 attempts.
Am I miss something? How I can solve this? 
Thanks.
