### ISSUE TITLE
featureId or current() without a list to set a property

### ISSUE THREAD

**Issue by tacman** [nelmio/alice#747]
I find myself writing a things like

```yaml
user_bob:
    username: bob
    name: ... (etc)
```

In this case, I don't want to use a template, but I'd like to set the username to the feature id or some part of it.  It appears that a one-item loop doesn't work.

```yaml
user_{bob}:
    username: <current()>
    name: ... (etc)
```

Ideally, I could match the featureId with something, e.g.

```yaml
user (template):
   username: <featureId()>
bob (extends user):
   name: Robert
carol (extends user):
   name: Carol
```

and have array "bob" have username set to "bob", 

Even better would be if I could do 

```yaml
user (template):
   username: <featureId()>
   name: "<featureId()>|ucfirst"
```

Are any of these possible?  I'm refactoring all our fixtures now that I've read (and re-read) the page on keeping your fixtures DRY.

**Comment by theofidry** [comment]
```yaml
user (template):
   username: '<featureId()>'
   name: '<ucfirst($username)>'
```

Should do the trick :)
