### ISSUE TITLE
Keep Your Fixtures Dry

### ISSUE THREAD

**Issue by Selion05** [nelmio/alice#750]
Hi, 

is something like the following possible? 

```
AppBundle\Entity\User:
    user (template):
        firstname: '<($username)>First'
        lastname: '<($username)>Last'
        plainPassword: '<($username)>'
        email: '<($username)>\@testing.dev'
        enabled: true
    admin (extends user):
        username: 'admin'
        roles: ['ROLE_SUPER_ADMIN']
    customer (extends user):
        username: 'admin'
        roles: ['ROLE_CUSTOMER']
```

**Comment by theofidry** [comment]
Never though about it, but should be in 3.x.

**Comment by theofidry** [comment]
This sorta works. The may issue you will encounter is that this kind of declaration depends on the order, i.e.:

```yaml
\stdClass:
    dummy
        foo: yo
        bar: $foo  # will be resolved fine
```

However:

```yaml
\stdClass:
    dummy
        bar: $foo  # will fail
        foo: yo
```

Which makes your fixtures extremely brittle as you have no guarantee of the order:

```php
// src/Definition/PropertyBag.php

public function mergeWith(self $propertyBag): self
    {
        $clone = clone $propertyBag;
        foreach ($this->properties as $name => $property) {
            $clone->properties[$name] = $property;
        }
        
        return $clone;
    }
```

As you can see it's a plain associative array, no special ordering is done.

So this *can* work, but is very fragile. Now can we make this better? We could find some ways, but I don't think they would be bulletproof either and would come with a non negligible performance impact + complexity.
