### ISSUE TITLE
Hot to generate OneToMany data using Nelmilo/Alice and Faker

### ISSUE THREAD

**Issue by wohral** [nelmio/alice#758]
Hello, I am stuck and don't know where to find a solution.

I have following [relationship](https://i.stack.imgur.com/WgOkD.png)

I would like to use Nello/Alice to generate language translations for each parameter.

I am stuck because I can't found how to do it dynamically. I have 3 languages and I want to generate N parameters, and for each parameter generate language translation in all 3 languages (of course lorem ipsum text).

Is it possible to do it and how?

**Comment by theofidry** [comment]
```yaml
Langs:
  langs_{en, fr, de}: {}

Parameters:
  params_{0...10}: {}

ParameterLangs:
  param_langs_{0...10}:
    parameter: '@param*'
    lang: '@lang*'
    some_value: 'ParamLang $current'
```

or something along those lines
