### ISSUE TITLE
Fixture not casting to string with quotes around parameter

### ISSUE THREAD

**Issue by jeremy-smith-maco** [nelmio/alice#770]
```
parameters:
  dateScheduled: 1481592275

DateTime:
  DateScheduled:
    __factory: { createFromFormat: ['U', '<{dateScheduled}>'] }
```

Complains about second parameter being integer and not string but should be casting to a string
