### ISSUE TITLE
Multiple dimensions array looping

### ISSUE THREAD

**Issue by aistis-** [nelmio/alice#771]
Hi, I am searching how to do something like this:

```yaml
My\Model\Lol:
    lol_{1..2}_sub_lol_{1..3}:
        content: '<current(1)> - current(2)>'
```

So, my expected result would be:

```yaml
My\Model\Lol:
    lol_1_sub_lol_1:
        content: '1 - 1'

    lol_1_sub_lol_2:
        content: '1 - 2'

    lol_1_sub_lol_3:
        content: '1 - 3'

    lol_2_sub_lol_1:
        content: '2 - 1'

    lol_2_sub_lol_2:
        content: '2 - 2'

    lol_2_sub_lol_3:
        content: '2 - 3'
```

Any ideas?
