### ISSUE TITLE
Pick value from provided list according to reference number

### ISSUE THREAD

**Issue by aistis-** [nelmio/alice#772]
Hi, I am searching how to do something like this:

```yaml
My\Model\Lol:
    lol_{1..3}:
        content: {5, 30, 12} # These are the values I should pick somehow according to <current()>
```

So, my expected result would be:

```yaml
My\Model\Lol:
    lol_1:
        content: 5

    lol_2:
        content: 30

    lol_3:
        content: 12
```

Any ideas?
