### ISSUE TITLE
TypeError: Argument 3 passed to FixtureDenormalizerRegistry::denormalize()

### ISSUE THREAD

**Issue by olvlvl** [nelmio/alice#792]
Hi,

I'm upgrading to v3 and I get a lot of these, not sure it is my fault or a bug:

```
TypeError: Argument 3 passed to Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\FixtureDenormalizerRegistry::denormalize() must be of the type string, integer given, called in /server/http/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/SimpleFixtureBagDenormalizer.php on line 75
```

`Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\SimpleFixtureBagDenormalizer::denormalize` receives the following array (excerpt):

```
array(2) {
  ["HelloFresh\RecipeService\Domain\Tag\Tag"]=>
  array(3) {
    [0]=>
    array(2) {
      ["localeData"]=>
      array(2) {
        ["en-US"]=>
        string(15) "@tag1LocaleData"
        ["de-DE"]=>
        string(15) "@tag1LocaleData"
      }
      ["numberOfRecipesByCountry"]=>
      array(1) {
        ["US"]=>
        int(10)
      }
    }
```

Indeed, `$reference` is an integer since the array has no associated keys.

Here follows the fixture definition (excerpt):

```yaml
HelloFresh\RecipeService\Domain\Tag\TagLocaleData:
  tag1LocaleData:
    name: tag1

HelloFresh\RecipeService\Domain\Tag\Tag:
  - localeData:
      en-US: "@tag1LocaleData"
      de-DE: "@tag1LocaleData"
    numberOfRecipesByCountry:
      US: 10
```

Is it mandatory to name fixtures since v3, should `$reference` be casted, or was I totally wrong to do that in the first place?

```php
                $fixtures = $this->fixtureDenormalizer->denormalize(
                    $fixtures,
                    $fqcn,
                    (string) $reference,
                    $specs ?? [],
                    $flags
                );
```
