### ISSUE TITLE
Chained method calls

### ISSUE THREAD

**Issue by aistis-** [nelmio/alice#794]
Hi, I am trying to call my embeddable object on a doctrine entity:

```yaml
My\Bundle\Entity\User:
    user_XXX:
        ...
        __calls:
            - options.updateSomeTimestamp: []
```

and it throws:

```php
Error: Call to undefined method My\Bundle\Entity\User::options.updateSomeTimestamp()
```

Is such a call supported?
