### ISSUE TITLE
Arithmetic action in property

### ISSUE THREAD

**Issue by aistis-** [nelmio/alice#796]
Hi, I am trying to set a current timestamp to property decreased by 100 seconds.

Something like that:

```yaml
My\Lol\Bundle\Whatever:
    something_1:
        timestamp: <(<time()> - 100)>
```

But I fail to do it properly. Any guidance on that guys? :)
