### ISSUE TITLE
Two fixture referencing to each other

### ISSUE THREAD

**Issue by Jir4** [nelmio/alice#798]
Hi, 

Is there a way to generate something like this ? :

```yml
AppBunle\Entity\User:
    user:
        email: <email()>
        client: @client

AppBundle\Entity\Client:
    client:
        name: <name()>
        createdBy: @user
```

I didn't find any reference to a similar needing :(
