### ISSUE TITLE
Circular reference issue

### ISSUE THREAD

**Issue by kermorgant** [nelmio/alice#801]
Hello,

I have two related entities User and Circle which have a "circular" relation via circle and leader properties. I am currently using nelmio/alice 3.0@RC and hautelook/alice-bundle 2.0@beta with doctrine 2.5.11

```yaml
AppBundle\Entity\User:
    member{1..50}:
        username: '<email()>'
        circle: '@circle<numberBetween(1,10)>' ## option A : comment here 

AppBundle\Entity\Circle:
    circle{1..10}:
        name: 'circle <name()>'
        leader: '@member<numberBetween(1,50)>'  ## option B : comment here
```

Unless I comment either "circle" or "leader" (options A or B), I get the following error  

```
  [Fidry\AliceDataFixtures\Exception\MaxPassReachedException]                  
  Loading files limit of 15 reached. Could not load the following files:       
  /var/www/app/Resources/fixtures/circle.yml:                                  
   - Nelmio\Alice\Throwable\Exception\Generator\Resolver\FixtureNotFoundException: Could not find the fixture "member38". in /var/www/vendor/nelmio/alice/src/Throwable/Exception/Generator/Resolver/FixtureNotFoundExceptionFactory.php:23    
```

Any idea of what is wrong ?
