### ISSUE TITLE
Templates - deep merge properties

### ISSUE THREAD

**Issue by nlemoine** [nelmio/alice#826]
Just discovered the template inheritance. This a great feature. 

However, I'm having an issue when property isn't single dimension. Consider the following example:

```yaml
Nelmio\Entity\User:
    default (template):
        username: '<username()>'
        fullname: '<firstName()> <lastName()>'
        birthDate: '<dateTimeThisDecade()>'
        email: '<email()>'
        hobbies:
            sports: 'volley-ball'
    user{1..3} (extends default):
        email: 'yoyo@email.com'
        hobbies:
            passions: 'cinema'
```

I would expect that `hobbies` from template would be deep merged with the current iteration. So I get this for `$user->hobbies`:
```php
'hobbies' => [
  'sports' => 'volley-ball',
  'passions' => 'cinema'
];
```

I'm currently getting:
```php
'hobbies' => [
  'passions' => 'cinema'
];
```

Would this be something doable?
