### ISSUE TITLE
object property undefined after referencing it

### ISSUE THREAD

**Issue by kermorgant** [nelmio/alice#841]
Hi,

I'm using hautelook/alice to load fixtures in my project. 

I got an issue on a particular one named "Instance" that takes a "InstanceOrder" as constructor argument.

```
    public static function constructFromOrder(InstanceOrder $instanceOrder)
    {
        // ...
        $instance->smtpConfiguration = $instanceOrder->getSmtpConfiguration();
        return $instance;
    }

```

Everything was working fine until I added this 

```
AppBundle\Entity\SubscriptionItem:
    sub1_item1:
        subscription: '@customer1_sub1'
        __construct: ['@plan2_v1', '@instance_order2->getUid()']
```

With that, the $instanceOrder's smtpConfiguration property is null instead of being set as it should.

And I get 

`  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'smtp_configuration_id' cannot be null   
`

Here.s the details of the packages in use https://gist.github.com/kermorgant/c247b4af4718b15fd89080f528efb956
