### ISSUE TITLE
use variables of relations 

### ISSUE THREAD

**Issue by jtkDvlp** [nelmio/alice#850]
Hi there,

is it possible to use variables of relations in yaml?

Example:
```yaml
my\entity\object:
      xyz:
            created: '<dateTime()>'

my\entity\objectLog:
      xyzLog:
            entryFor: '@xyz'
            timestamp: '<dateTimeBetween($entryFor->created)>'
```
Got the following error:
> Could not lex the value ">created"
