### ISSUE TITLE
Alice calls methods under __calls twice, in certain cases

### ISSUE THREAD

**Issue by norbert-yoimo** [nelmio/alice#851]
I'm not sure what exactly causes this behavior, but my observation is that if the following two requirements are met:

* You have a fixture A, that has a method listed under `__calls`
* Another fixture B has a `__construct`, where the argument is a reference to fixture A

Example:
```yaml
KN\Entity\Sporty:
    sporty1:
        __calls:
            - setOwningTeam: []

KN\Entity\SportyShareCode:
    code1:
        __construct: [ "@sporty1" ]

```

The method `setOwningTeam` will be called twice.

I have made a POC for this that you can clone easily:

https://github.com/norbert-yoimo/alice-poc-double-calls

If you run `php test.php`, you will see:

```
CALLED 1 times
CALLED 2 times
```

PHP version is 7.2.1, Alice version is 3.1.3.
