### ISSUE TITLE
date() expects at least 1 parameter, 0 given

### ISSUE THREAD

**Issue by slk500** [nelmio/alice#852]
First example on site with date() throws "date() expects at least 1 parameter, 0 given"

https://github.com/nelmio/alice#example

```yaml
Nelmio\Entity\User:
    user{1..10}:
        username: '<username()>'
        fullname: '<firstName()> <lastName()>'
        birthDate: '<date()>'
        email: '<email()>'
        favoriteNumber: '50%? <numberBetween(1, 200)>'

```
