### ISSUE TITLE
Reference in NativeLoader::loadFile

### ISSUE THREAD

**Issue by AntoineLemaire** [nelmio/alice#854]
I simplified my problem with an exemple of a theoretical `Article` entity.
My Article has a title, content category and a type

My fixtures are writed in separates YAML files

```yaml
# category.yml
AppBundle\Entity\Category:
    category_1:
        id: 1
        name: foo
    category_2:
        id: 2
        name: bar
```
```yaml
# type.yml
AppBundle\Entity\Type:
    type_1:
        id: 1
        name: baz
    type_2:
        id: 2
        name: qux
```
```yaml
# article.yml
AppBundle\Entity\Article:
    article_1:
        id: 1
        title: "Lorem ipsum dolor sit amet, consectetur"
        content: "Lorem ipsum dolor sit amet, consectetur"
        category: '@category_1'
``` 

The problem is I have a DoctrineListener on `Events::preUpdate` which update Article::type depends of Article::Category

```php
/**
* Doctrine Listener
*/
class ArticleListener
{
   // ...
    private function preUpdate(LifecycleEventArgs $args)
    {
        $article = $args->getEntity();

        // Get type from DB
        $type = $this->container->get('app.my.service')->getTypeFromCategory($article->getCategory());

        $article->setType($type);
    }
}
```

So load category & type fixtures first

```php

class BasicFixtures extends Fixture
{
    public function load(ObjectManager $manager)
    {
        $files = [
            'category' => __DIR__.'/../../../AppBundle/DataFixtures/category.yml',
            'type'     => __DIR__.'/../../../AppBundle/DataFixtures/type.yml',
            //... other yml files
        ];

        $loader    = new NativeLoader();
        $objectSet = $loader->loadFiles($files);

        foreach ($objectSet->getObjects() as $key => $object) {
            $this->addReference($key, $object);
            $manager->persist($object);
        }

        $manager->flush();
    }
}
```
And then I load my Article fixture with `DependentFixtureInterface::getDependencies` to be sure categories and types are already loaded
```php
class ArticleFixtures extends Fixture implements DependentFixtureInterface
{
    public function load(ObjectManager $manager)
    {
       // This give me my object
        dump($this->getReference('category_1'));

        $files = [
            'article' => __DIR__.'/../../../AppBundle/DataFixtures/article.yml',
            //... other yml files
        ];

        $loader    = new NativeLoader();
        $objectSet = $loader->loadFiles($files);

        foreach ($objectSet->getObjects() as $key => $object) {
            $manager->persist($object);
        }

        $manager->flush();
    }

    public function getDependencies()
    {
        return [
            BasicFixtures::class,
        ];
    }
}
```
But it seams with that, the reference of "@category_1" is lost inside NativeLoader::loadFile

```
In FixtureNotFoundExceptionFactory.php line 23:
                                                                                  
  [Nelmio\Alice\Throwable\Exception\Generator\Resolver\FixtureNotFoundException]  
  Could not find the fixture "category_1".
```

After search deeply, I saw that the FixtureReferenceResolver does not contain fixtures from previous dependencies
```php
    private function getReferredFixture(string $id, ResolvedFixtureSet $set): FixtureIdInterface
    {
        $fixtures = $set->getFixtures();
        // $fixtures does not contain fixtures from dependencies
        if ($fixtures->has($id)) {
            return $fixtures->get($id);
        }

        return new FixtureId($id);
    }
```
