### ISSUE TITLE
current() in combination with referencing properties broken

### ISSUE THREAD

**Issue by ChristianVermeulen** [nelmio/alice#879]
Hi There,

I've upgraded van 2.1.2 to 3.2.0 and I think I might've found a bug which is causing us problems right now.

This is an example of what I'm trying to do:
```yml
user (template):
  __construct:
    - '@user__*'
    - '<email()>'
    - '<uuid()>'

user_confirmed__{1..20} (extends user):
  confirm:
    - '@user_confirmed__<current()>->token'
```

The User entity has a token generated automatically on `__construct` which has its `getToken()`-method. However, when using this syntax I get:

```
Nelmio\Alice\Throwable\Exception\FixtureBuilder\ExpressionLanguage\LexException:
Could not lex the value ">token".
```

When I change it to e.g. `- '@user_confirmed__1->token'` it does work. Well, besides the fact that it uses the same token for all users then, but the syntax is accepted.

This makes me believe there is a problem with the `<current()>` function which causes it to not being able to be chained anymore.

I hope you either know what I'm doing wrong or where the bug is because this is causing us a few headaches 😅.
