### ISSUE TITLE
Symfony Bridge auto add current faker method to blacklist if is not included.

### ISSUE THREAD

**Issue by ixarlie** [nelmio/alice#884]
It is a really minor issue but if `<current()>` is an internal alice faker, when I edit blacklisted functions like this, `current` stop working because is trying to use PHP function instead.
```yml
nelmio_alice:
# ...
  functions_blacklist:
    - 'md5'
# ...
```

Ok, the solution is simple, add `current` to the list but I think it should be added by alice if it is not in the list.
