### ISSUE TITLE
unknown formatter "current"

### ISSUE THREAD

**Issue by VaN-dev** [nelmio/alice#889]
Hello,

i'm using alice fixtures ("nelmio/alice": "^3.1") and i want to build relations inside a loop. I have the following 2 fixtures :

```
<?php
# user_fixtures.php

return [
    \Domain\Model\Entity\User\User::class => [
        'user_{1..10}' => [
            '__construct' => [[
                'uuid' => '<uuid()>',
                'email' => '<userUniqueEmail()>',
            ]],
        ],
    ],
];
```
```
<?php
# external_user_metadata_fixtures.php
return [
    \Domain\Model\Entity\User\ExternalUserMetadata::class => [
        'external_user_metadata_{1..10}' => [
            '__construct' => [[
                'user' => '@user_<current()>',
                'creator' => '@user_superadmin',
                'department' => '@department_*',
            ]],
        ],
    ],
];
```
And my alice.yaml file :
```
# @link https://github.com/nelmio/alice/blob/master/doc/getting-started.md#symfony

nelmio_alice:
    locale: 'fr_FR'
    functions_blacklist:
        - 'current'
    loading_limit: 5
    max_unique_values_retry: 150
```
When I try to load the fixtures, I got the following error :

```
In Generator.php line 242:
                               
  Unknown formatter "current"
```

I read the doc, the examples, and it looks the right way to use `current()`. Am I missing something ?
