### ISSUE TITLE
List requires more than one item

### ISSUE THREAD

**Issue by matt-usurp** [nelmio/alice#891]
There is a use case that I think has gone under the radar where you may define a fixture that looks something like the following:

```YAML
MyClass:
  person_{alice}:
    name: '<current()>'
```

At first this looks stupid (and I can agree) however this is a common case when extending from a template that defines the usage of `<current()>`. For example we have a template that is used to define groups of something, to make this easier it uses the current marker but in the cases where a group only contains one we are left with `{single}`.

I am curious if this is was done on purpose?

On another note I see there is another issue where spaces are required too now? #872

**Comment by matt-usurp** [comment]
For clarify the use case I need to cover:

```YAML
SomeCategory:
  category_{1..3}:
    name: '<current()>'

SomeItem:
  item_template:
    name: '<current()>'

  item_cat1_{one, two, three} (extends item_template):
    category: '@category_1'

  item_cat2_{four} (extends item_template):
    category: '@category_2'
```

I hope this makes things clearer.
