### ISSUE TITLE
Circular reference issue in v3.2.1

### ISSUE THREAD

**Issue by JanisGruzis** [nelmio/alice#894]
Have circular reference issue in v3.2.1 . This issue doesnt happen in v3.1.3 . Fixtures file that causes the issue. (Names are anonymous.)

```
LI\AppBundle\Entity\Service:
    s1:
        name: S1
        allowedSenders: ["@s3", "@s1"]
    s2:
        name: S2
        allowedSenders: ["@s2", "@s10", "@s8", "@s9", "@s11", "@s6", "@s4"]
    s3:
        name: S3
        allowedSenders: ["@s2", "@s4", "@s3", "@s5", "@s8", '@s9', '@s6']
    s4:
        name: S4
        allowedSenders: ["@s2", "@s4", "@s7", "@s9", "@s11", "@s8", "@s6"]
    s5:
        name: S5
        allowedSenders: ["@s5", "@s6"]
    s6:
        name: S6
        allowedSenders: ["@s6"]
    s7:
        name: S7
        allowedSenders: ["@s7", "@s8"]
    s8:
        name: S8
        allowedSenders: ["@s8", "@s2", "@s9", "@s4", "@s3"]
    s9:
        name: S9
        allowedSenders: ["@s9", "@s2", "@s8"]
    s10:
        name: S10
        allowedSenders: ["@s10", "@s2", "@s8", "@s3", "@s4", "@s11"]
    s11:
        name: S11
        allowedSenders: ["@s11", "@s2", "@s8"]
    s12:
        name: S12
        allowedSenders: ['@s12']
```
