### ISSUE TITLE
Extending a fixture coming from a fixture list does not work anymore in 3.x

### ISSUE THREAD

**Issue by stof** [nelmio/alice#910]
In 2.x, the following would work, and merge settings of the fixtures (except the constructor arguments, which have to be repeated when extending):

```yaml

    challenge_{1A, 2A, 3A}:
        __construct: ['@galaxy_corp', '<{space_type.challenge}>']
        name: 'Prix <current()>'
        identifier: 'prix-<current()>'
        visibility: '<{space.visibility_public}>'
        administrators: ['@admin_user']
        individualTargetLevels:
            - '@agency_hierarchical_level'
        activate: []

    challenge_1A:
        __construct: ['@galaxy_corp', '<{space_type.challenge}>']
        name: 'Prix 1A / Agencies - All / Themed'
        identifier: 'prix-1a-team-only-themed'
        onlyTeamResults: true
        individualTargetLevels: []
        hierarchicalLevels:
            - '@agency_hierarchical_level'
        theme: 'sell_sell_sell'
```

In 3.x, this does not work anymore. Only settings from the explicit fixture are taken into account (I think it takes the last one into account so the one from the fixture list could win by swapping them). But this is not documented in the upgrade guide.
