### ISSUE TITLE
Functions and wildcards cannot be used in the middle of a reference anymore

### ISSUE THREAD

**Issue by stof** [nelmio/alice#912]
```yaml
Role:
    agency7_role:
        identifier: agency7
        assignees: '@member{131..140}'
        superiors: ['@dept2_role', '@product*_role']

Subject:
    challenge_ranking_family_custom_ranking_subject{4, 5, 7}:
        ranking: '@challenge_ranking_family_custom_ranking_dept2'
        team: '@agency<current()>_role'
```

None of these is working in 3.x (while they were fine in 3.x). `@agency<current()>_role` is parsed as the `@agency<current()>` reference, concatenated with `_role` (which of course breaks, as this reference is invalid in my fixtures, and then the concatenation would not work)

**Comment by theofidry** [comment]
I think we should be able to fix that one

**Comment by stof** [comment]
I would say that concatenating a reference to anything else is very unlikely to ever make sense. So we may want to change the  precedence of stuff (including all the following stuff in the reference, until reaching something not making it concatenated, like the comma separating arguments of a function)

**Comment by kalifg** [comment]
I'd like to add that referencing dynamic property names no longer seems to be possible.

Background: I'm updating a project that is using a very old fork of Alice 1.x.  It was capable of resolving references like the following:

```yml
    userGameTournamentToEarlyComplete2{1..2}:
        playerPosition: <current()>
        user: '@gameTournamentToEarlyComplete2->user<($playerPosition)>'
```

The `user` reference would resolve to either the `user1` or `user2`.  With Alice 3.4  it tries to pull the `user` property, which does not exist.

I've tried `'@gameTournamentToEarlyComplete2->user<current()>'` as well with the same results.  

I can't find documentation for this usage in the manual.  Dynamic reference names are documented, but not fields

Questions: 
1. Is this supposed to work and doesn't (bug) or not currently supported anymore (feature request)
2. Should I file a separate issue for this?

**Comment by kalifg** [comment]
I was using the debugger, looking for a work-around, and I found out that it was parsing it as `@gameTournamentToEarlyComplete2->user` and `<($playerPosition)>`, attempting to evaluate each and then concatenate them together — this mirrors the issue author's experience more closely than my earlier evaluation.

Also I did find this work-around in case it's useful:

```yml
    userGameTournamentToEarlyComplete1{1..2}:
        playerPosition: <current()>
        user: '<(@gameTournamentToEarlyComplete1->{"getUser${playerPosition}"}())>'
```

Not optimal but I like it better than my co-worker's previous attempt which involved creating a custom provider to forward a request `PropertyAccess` like so:

```yml
    userGameTournamentToEarlyComplete{1..2}:
        playerPosition: <current()>
        user: <getProperty(@gameTournamentToEarlyComplete1, 'user', $playerPosition)>
```
