### ISSUE TITLE
Event Dispatcher

### ISSUE THREAD

**Issue by gimler** [nelmio/alice#92]
I need a post callback so that i can run some code on the object after creation.

So waht do you think about a generell event dispatcher implementation https://github.com/symfony/EventDispatcher.

So that for example we can call methods with `__eventName` for example and also register globally come callbacks

```
callbacks:
  class:
    __post: { method: [parameter]}

class:
  __post: { method: [parameter]}
```
