### ISSUE TITLE
Reference in nested graph

### ISSUE THREAD

**Issue by lyrixx** [nelmio/alice#922]
Hello

It seems reference in a nested graph are not resolved:

```
AppBundle\CMS\Entity\Page:
    page:
        zones: []
    footer:
        zones:
            zone_1:
                page: "@page"
```

In the DB, I got `{}` instead of the id of `page`.

---

Note: I also tried via a custom faker provider, but in this case I got `@page` in the DB.
