### ISSUE TITLE
Refernce Wildcard

### ISSUE THREAD

**Issue by fredtro** [nelmio/alice#924]
Hello

When using wildcard in a reference name, always last fixture is used and not a randomly selected one. 

I am using v2.3.5.

```yaml
AppBundle\Entity\Security\GroupType:
    grouptype_1:
        name: "Sometype"
    grouptype_2:
        name: "Othertype"

AppBundle\Entity\Security\Group:
    group_1:
        name: "Group 1"
        type: "@grouptype*"
    group_2:
        name: "Group 2"
        type: "@grouptype*"
```

Or did i miss something...
