### ISSUE TITLE
Property reference combined with interpolated relation (<x>) fails with exception

### ISSUE THREAD

**Issue by ssaki** [nelmio/alice#925]
Here is the use case:
```yaml
Subject1:
    subject1_instace_{1..100}:
        prop: '<whatever>'
        
Subject2:
    subject2_instace_{1..100}:
        prop: '@subject1_instace_<current()>->prop'
```

results in: 
```
 [Nelmio\Alice\Throwable\Exception\FixtureBuilder\ExpressionLanguage\LexException]  
  Could not lex the value ">prop"
```

Using only the relation (`@subject1_instace_<current()>`) or only the property reference (`@subject1_instace_1->prop`) works as expected. 

Tested on v3.2.2 and v3.3.0
