### ISSUE TITLE
Using JSON string containing an array in Yaml fixtures

### ISSUE THREAD

**Issue by loic425** [nelmio/alice#935]
Using doctrine, we now have "json" type (https://www.doctrine-project.org/projects/doctrine-dbal/en/2.7/reference/types.html#json).

We can now have a json string and this works correctly with alice, but when we have an array in the json, we got an error.

**Exemple**
`data: '{"name":"Netflix", "types":["streaming", "video"]}'`

It throws that error: "Array to string conversion"

**Comment by theofidry** [comment]
Indeed this string would need to be escaped otherwise it's interpreted as for any value. So I would either recommend to try a custom faker provider or help out with https://github.com/nelmio/alice/issues/840 :)

**Comment by loic425** [comment]
@theofidry Thank you, it works with the workaround.

```
parameters:
     data: '{"name":"Netflix", "types":["streeming", "video"]}'

App\Entity\Test:
    test_1:
        __calls:
          - setData: [<{data}>]
```
