### ISSUE TITLE
Can not parse multiple chained reference

### ISSUE THREAD

**Issue by Soullivaneuh** [nelmio/alice#937]
With the following fixture file:

```
include:
    - hosting.yml

AppBundle\Entity\CloudFlareZone:
    cloudflare_zone_default:
        id: ThisIsNotRealCloudFlareId
        name: '@hosting_default->name'
        owner: '@hosting_default->server->owners->first'
```

I have the error:

```
  [Nelmio\Alice\Throwable\Exception\FixtureBuilder\ExpressionLanguage\ParseException]                   
  Could not parse the token "@hosting_default->server->owners->first" (type: METHOD_REFERENCE_TYPE).  
```

From this code part:

https://github.com/nelmio/alice/blob/16959632cd73c019e2ae4d3ccd88062056738cb7/src/FixtureBuilder/ExpressionLanguage/Parser/TokenParser/Chainable/FixtureMethodReferenceTokenParser.php#L50-L52

Why the chain reference should be limited to one call?
