### ISSUE TITLE
Conditional data between fields on a single entity

### ISSUE THREAD

**Issue by bastos71** [nelmio/alice#948]
Hi there !

I'm facing a big question here : is it possible to define conditional values for fields, depending on wich value is set in another field in the samze single entity ? 
Here is an example : 

```yaml
Namespace\Of\My\Entity:

    entity__{1,100}:
        #...
        # First possibility :
        first_field: '0'
        second_field: "Something"

        # Second possibility :        
        first_field: '1'
        second_field: "Something else"
        #...
```

Is it possible to do something for the field `second_field` like "if `@self::first_field` is `0`, then value is `something`. Else value is `something else`

And to go further : is it also possible to have more complexed conditionnal data ? 

Thx !

**Comment by theofidry** [comment]
It should be possible to some extend with [optional data](https://github.com/nelmio/alice/blob/master/doc/complete-reference.md#optional-data) and if the condition hits the limit of the lexer, a custom faker provider can do the job as well

**Comment by bastos71** [comment]
Concretly what should I do ?

**Comment by theofidry** [comment]
An example with a custom faker provider would be:

```yaml
Namespace\Of\My\Entity:
    entity__{1,100}:
        first_field: '0'
        second_field: <myFakerFunction($first_field, "Something", "else")>
```

and you handle the logic in `myFakerFunction()`. Sorry I can't really dig into it more than that at the moment
