### ISSUE TITLE
Question: how to pass all entities as reference?

### ISSUE THREAD

**Issue by Bogdaan** [nelmio/alice#952]
For example:
```yaml
App\Dict:
  dict_uuid:
    key: 'uuid'
    value: 1
  dict_key:
    key: 'key'
    value: 1

App\Model:
  model:
    dicts: '@dict*'  # How to pass ALL X dicts ?
```
