### ISSUE TITLE
Creating non-doctrine objects as fixtures and referencing to them

### ISSUE THREAD

**Issue by smilesrg** [nelmio/alice#959]
Hello!

Is it possible to create non-doctrine objects as fixtures and referencing to them?
I've faced with difficulties when moving one of doctrine entities to non-doctrine storage (actually, just objects-entities created from YML file data). Now I want to reference them from fixtures. Is it possible?

```yml
#statyc.yml
Foo\ValueObjects\Static:
    staticFixture1:
        __construct: ['foo', 'bar']

#referencing.yml
Bar\Entity\Referencing:
    referencingFixture:
        bar: ['@staticFixture']
```
