### ISSUE TITLE
how to reference id of entity ?

### ISSUE THREAD

**Issue by videni** [nelmio/alice#962]
```
App\Bundle\DeviceUserBundle\Entity\DeviceUser:
    device_user1:
        username: "test1"
        password: '\$2y\$13\$PqmWgJRBuvHFnxqNXdegW.HQ9C4mBwyWpJUSL8Q6KBnYwXFl8SdWG' #"123456"
        areaId: 10
        deviceType: "pad"
        channelId: 10
```

get the id of the device_user1  and set it to game_device1
```
App\Bundle\ChannelBundle\Entity\GameDevice:
    game_device1:
        deviceId: "@device_user1->id"
        deviceName: "big device"
```

but try to save  game_device1,  the device_id is  empty.
