### ISSUE TITLE
<numberBetween(0, 10000)> in __construct

### ISSUE THREAD

**Issue by leonardbos** [nelmio/alice#966]
Hi, I have some problems with adding data, when I try to add <numberBetween(0, 10000)> in my __construct I get the following error: 
**The value "<randomElement(<numberBetween(0" contains an unclosed function.**

`    client_contact_log (template):
        __construct: [<(<numberBetween(0, 10000)>]`

How can I make this work? Thanks :)

**Comment by leonardbos** [comment]
This bug appears to be only occurring when passing arguments in a single line.

```yaml        
__construct:
    - <numberBetween(0, 10000)>
```

Using the multiline notation seems to work properly.

**Comment by theofidry** [comment]
that is... really weird, from where does the error comes from exactly? Alice or the Yaml parser?

**Comment by leonardbos** [comment]
> that is... really weird, from where does the error comes from exactly? Alice or the Yaml parser?

The error comes from Alice:
```
.....FFFPHP Fatal error:  Uncaught Nelmio\Alice\Throwable\Exception\FixtureBuilder\ExpressionLanguage\MalformedFunctionException: The value "<numberBetween(0" contains an unclosed function. in /home/lbos/projects/client-log-entities/vendor/nelmio/alice/src/Throwable/Exception/FixtureBuilder/ExpressionLanguage/ExpressionLanguageExceptionFactory.php:59
```

**Comment by leonardbos** [comment]
> Does:
> 
> ```yaml
> client_contact_log (template): 
>     __construct: ['<numberBetween(0, 10000)>']
> ```
> 
> Works?

No, this has no effect, the same error appears as before.

**Comment by ghettovoice** [comment]
Hi for all!
I have same issue in this case

```yml
Glonass\SafeCity\App\UI\Resource\Tag:
    tag_{1..20}:
        tagId: <uuid()>
        name (unique): <words(<numberBetween(2, 4)>, true)>
        color: <hexcolor()>
        version: <randomDigit()>
        createdAt: <dateTimeImmutable('-1 month', 'UTC')>
```

```
In TolerantFixtureDenormalizer.php line 68:
                                                                                                                                                                        
  An error occurred while denormalizing the fixture "tag_{1..20}" (Glonass\SafeCity\App\UI\Resource\Tag): The value "<(numberBetween(2" contains an unclosed function.  
                                                                                                                                                                        

In ExpressionLanguageExceptionFactory.php line 59:
                                                                
  The value "<(numberBetween(2" contains an unclosed function.  

```
