### ISSUE TITLE
multi level inheritance not reaching all levels

### ISSUE THREAD

**Issue by mlojewski** [nelmio/alice#975]
Hi, 
this is the first time Im using Alice to help me with "live" project. Im preparing the yaml file as follows:

```yaml
App\Entity\Tenant\AuthorAge:
    authorAge:
        ageRange: 16-26 (was lazy and hardcoded only one value)

App\Entity\Tenant\Author:
    author_{1..10}:
        name: <firstName()>
        lastName: <lastName()>
        city: <text(10)>
        email: <email()>
        authorAge: '@authorAge*'

App\Entity\Tenant\Opinion:
    opinion_{1..10}:
        product: '@product*'
        author: '@author*'
        status: '@status*'
        isConfirmed: 1
        token: <text(24)>
        answers: '3x @answer*'
```

Whenever I want to load the fixtures I reveive the following: 

```
Expected argument of type "App\Entity\Tenant\Author or null", "App\Entity\Tenant\AuthorAge" given at property path "author".
```

To be 100% clear - there are relationships between author age and author + between author and opinion.
It seems Im doing everything as stated in the documentation and yet it does not work. Would really appreciate if you could tell me is there something Im doing wrong? Thank you
