### ISSUE TITLE
Templates and ranges

### ISSUE THREAD

**Issue by nVitius** [nelmio/alice#98]
I'm trying to do something like this:

``` yaml
Nelmio\Entity\User:
  date_template (template):
    insertDate: <dateTimeBetween(now, now)>
    modifiedDate: <dateTimeBetween($insertDate, now)
  user_template (template, extends date_template):
    username: <userName()>
  user{1..5} (extends  user_template):
    name: <firstName()>
    lastName: <lastName()>
```

When I use a range like that though, none of the templates get used. Note that if `user_template` didn't extend `date_template`, it will work. Also, if this was a single user (`user1`) instead of a range, it will work.
