### ISSUE TITLE
Creating non-doctrine objects & use them in fixtures

### ISSUE THREAD

**Issue by gkueny** [nelmio/alice#982]
Hi,

In v2 I was using local flag to create non-doctrine object & use them in my fixtures : 
```yaml
App\Chat\Value\OwnerId (local):
    owner_{1..2}:
        __construct: ['<current()>']
App\Auth\Entity\Credentials:
    credentials_1:
        id: '1'
        ownerid: @owner_1
        login: 'first-login-ever'
        password: 'password'

    credentials_2:
        id: '2'
        ownerid: '@owner_2'
        login: 'first-login-web'
        password: 'password'
App\Auth\Entity\Token:
    token_1:
        ownerid: '@owner_1'
        id: '<uuid()>'
        token: 'a token 1'

    token_2:
        ownerid: '@owner_2'
        id: '<uuid()>'
        token: 'a token 2'
```

My Credentials entity wait a `Condor\Chat\Value\OwnerId` class  for **ownerid** 

But in v3, we don't have **local** flag anymore & I'm not sure how to handle it. 
Do you now how to do this in v3 ?

Maybe related to #959
