### ISSUE TITLE
Can't use templates with ranges

### ISSUE THREAD

**Issue by morrislaptop** [nelmio/alice#99]
``` yaml
Lion\GuinnessMyPintBundle\Entity\EntryCode:
  entryCode (template):
    code: <lexify()>
    traction_ref: <numberBetween(1000, 9999)>
    pub: @pubStub

  entryCode{1..9} (extends entryCode):
    entry: @entryNextToWin

  entryCodeOne (extends entryCode):
    entry: @entryOneEntry
```

yields

[Doctrine\DBAL\DBALException]
  An exception occurred while executing 'INSERT INTO entry_codes (code, entry_id, pubs_id, traction_ref, created) VALUES (?, ?, ?, ?, ?)' with params [null,
  19, null, null, "2014-03-26 10:46:45"]:

  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'pubs_id' cannot be null

  [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'pubs_id' cannot be null
