### ISSUE TITLE
Referencing auto generated ids

### ISSUE THREAD

**Issue by sunglee** [nelmio/alice#999]
Hi,

I am new to this library and spend two days to figure out the issues I have. :(
I am trying to create a fixture for one-to-many relations and it is not a strange patterns at all.
Here is example schema.
```
Users
--
id (int, auto inc)
name

Comments
--
id (int, auto inc)
title
user_id (int)
```

And here is the fixture:
```
App\Entity\Users:
   user_{1..10}:
    name

App\Entity\Comments:
  comment_{1..20}:
    title
    user_id: '@user_*'
```

When I run this fixture, I got the following error:
```
In PropertyAccessor.php line 197:
Expected argument of type "integer", "App\Entity\Comments" given at property path "user_id".
```

How can I get a generated id from Users table? I tried `@user_*->id` and didn't work.

Thanks for your time.

**Comment by theofidry** [comment]
Maybe you can rely on a Faker provider instead. I would however recommend not to rely on auto-generated ID: alice won't persist your entities so the IDs won't be generated yet. What you are doing is pretty much:

```php
$user = Alice::generate(); // not persisted yet
$comment = Alice::generate(); // not persisted yet

$comment->setUserId($user->getId());

// later, e.g. with AliceDataFixtures
$em->persist($user);
$em->persist($comment);
$em->flush();
```

So IMO if you are relying on auto-generated ID: you don't set your relations through those IDs.

**Comment by sunglee** [comment]
Thanks for your reply.

That makes sense that why `comment` cannot get `user_id`.
In the Faker page, it is mentioned:
```
Faker does not populate autoincremented primary keys.
```
So my case cannot be solved with Faker either.
Anyway, I appreciate your explanation.

**Comment by videni** [comment]
I still think there should be a way to solve this problem,  this case it is quite common in my situation, I handle relation as a normal column instead of foreign key. 

```
group1:
        items:
            - { score: 'danger', itemId: '@item1_1->id' }
            - { score: 'none', itemId: '@item2_1->id' }
            - { score: 'good', itemId: '@item3_1->id' }
            - { score: 'warning', itemId: '@item4_1->id' }
```

the Item entity has auto increment id which is natural in my domain logic,  changing it to none auto increment  is intrusive which makes my domain more complext.

@sunglee, do you have a better solution please ?

I can generate the items with doctrine fixture ways, then reference these entities in alice with a custom identity provider, however , this seperate the fixtures into two places.

**Comment by theofidry** [comment]
@videni any domain object that relies on auto-generated IDs is objectively a bad domain object. The reason being that it will have an half-valid state until your persist it, making it unsuitable for domain usage in general.

That said, this doesn't prevent you to use a numerical suite as an ID. This however works well only if you are using PostgreSQL and not mySQL. The reason is that in PostgreSQL the auto-incremented IDs are done via _sequence_, which can easily be abstracted in your code (e.g. have an interface `Sequence` and then an in-memory adapter and a DB adapter) which allows you to generate the suitable sequence of IDs without having to persist your entities right away.

The only alternative I see with MySQL is either to generate those specific entities via another process and then pass them as references to alice later when loading the fixtures to allow your fixture definitions to refer to those entities.

**Comment by videni** [comment]
@theofidry, thanks for your very details expalin, fortunately I am using PostgreSQL, can you give me an exmple ?   

>  (e.g. have an interface Sequence and then an in-memory adapter and a DB adapter)

this phrase doesn't have too much sense for me.

**Comment by theofidry** [comment]
You could have:

```php
interface Sequence {
  function nextValue(): int;
  function reset(): void;
}

// I'm going an extra step here since generally 
// you have a sequence per aggregate. You could
// simplify it however if that's not the case
interface ItemSequence extends Sequence {}

abstract class InMemorySequence implements Sequence
{
    private $nextValue;
    private $startValue;
    private $increment;

    public function __construct(int $startValue = 1, int $increment = 1)
    {
        $this->startValue = $startValue;
        $this->nextValue = $startValue;
        $this->increment = $increment;
    }

    final public function nextValue(): int
    {
        $value = $this->nextValue;

        $this->nextValue += $this->increment;

        return $value;
    }

    final public function reset(): void
    {
        $this->nextValue = $this->startValue;
    }
}

final class InMemoryItemSequence extends InMemorySequence implements ItemSequence {}

abstract class ORMPsqlSequence implements Sequence
{
    private $connection;
    private $name;

    public function __construct(Connection $connection, string $name)
    {
        Assert::stringNotEmpty($name);

        $this->connection = $connection;
        $this->name = $name;
    }

    final public function nextValue(): int
    {
        return (int) $this->connection->fetchColumn(
            $this->connection->getDatabasePlatform()->getSequenceNextValSQL($this->name)
        );
    }

    public function reset(): void
    {
        $this->connection->executeQuery(sprintf('ALTER SEQUENCE %s RESTART', $this->name));
    }

    final protected function getConnection(): Connection
    {
        return $this->connection;
    }

    final protected function getName(): string
    {
        return $this->name;
    }
}

final class ORMItemSequence extends ORMPsqlSequence implements ItemSequence {}
```

Then in your domain, when creating `Item`, you can assign the ID via `ItemSequence`. Then in your fixtures, you can have a `<itemSequence()>` call for example that will call the DBSequence, effectively ensuring the ID will be unique since correctly incremented without requiring the entity to be persisted

**Comment by videni** [comment]
haha, thanks a lot 🙏

**Comment by videni** [comment]
@theofidry , excuse me , I have to ask another question,  how to use the InMemoryItemSequence  and  ItemSequence class?   the following are what I try, however it seems not correct.
```

App\Entity\Item:
    item1:
        name: "item1"
        group: "@group1"
    item2:
        name: "item2"
        group: "@group1"
   
App\Entity\Group:
    group1:
        name: "group1"
        items: 
            - { property1: 'danger', itemId: '<sequence("item1")>' }    # how to reference item1?
            - { property1: 'none', itemId: '<sequence("item2")>' } 
          
```

```
class ORMPsqlSequenceProvider
{
    private $doctrine;

    public function __construct(ManagerRegistry $doctrine)
    {
        $this->doctrine = $doctrine;
    }

    public function sequence($name)
    {
        $connection = $this->doctrine->getConnection();
        $sequence = new ORMPsqlSequence($connection, $name);

        return $sequence->nextValue();
    }
}

```

## Register itemSequence function to alice via DI
```
    App\Faker\Provider\ORMPsqlSequenceProvider:
        arguments:
            - '%kernel.project_dir%'
        tags:
            - { name: 'nelmio_alice.faker.provider' }

```

**Comment by theofidry** [comment]
Assuming it is not better to pass the `Item` objects to `Group` directly instead of passing IDs, I think it should rather be:

```yaml
App\Entity\Item:
    item1:
        id: "<itemSequence()>"
        name: "item1"
        group: "@group1"
    item2:
        id: "<itemSequence()>"
        name: "item2"
        group: "@group1"
   
App\Entity\Group:
    group1:
        name: "group1"
        items: 
            - { property1: 'danger', itemId: '@item1->id' }
            - { property1: 'none', itemId: '@item2->id' } 
```

**Comment by videni** [comment]
@theofidry,nice, it works now, even though  the strategy is 'auto' for item table in doctrine,  assign id like this works. 
```
item1:
        id: "<itemSequence()>"
        name: "item1"
        group: "@group1"
```
just the `setId` method is required, seems the persistence for alice doesn't use reflection.
